pages/integrations/gitlab.md.erb

We've had a few support questions about gitlab commit statuses but unfortunately, we don't support them at the moment. So this is to clarify that.
I'm not sure if we want to put any reason or other information in here though

Add note about not supporting gitlab commit status

---

pages/agent/v3/help/_artifact_download.md

Currently it states step name but there is no concept of name for a step. It should be either step label, key or job id which needs to be used as input to --step flag.

update the step flag explanation

---

app/models/test_analytics_json.rb
data/test_analytics_json_fields_detail.yaml
data/test_analytics_json_fields_span.yaml
pages/test_analytics/importing_json.md.erb

PIE-1010
The docs are missing attributes for span objects (for HTTP and SQL).
A customer reached out about this as they were trying to figure out how
to POST the URL, method, and library details to the span object.
Customer message
https://buildkite-community.slack.com/archives/C03HXN4ARB5/p1660262430972669?thread_ts=1660256140.870549&cid=C03HXN4ARB5
Relevant code
https://github.com/buildkite/buildkite/blob/1e04bd5774c1c54927d15668b35c9bdfeae479f9/app/models/analytics/execution/ingestion_result.rb#L123
Docs page
https://buildkite.com/docs/test-analytics/importing-json#json-test-results-data-reference-test-result-objects

Add missing documentation on span objects 'detail' attribute

---

app/assets/stylesheets/public/utils/_text_content.scss

Following up with https://github.com/buildkite/docs/pull/1698 I think occasionally we may need deeper nested lists. In light of this, I've added up to 6 levels of nested lists to the CSS.
Unfortunately, CSS doesn't do something like `nth-level` selector, I think JavaScript is an overkill, and good content design shouldn't need to go beyond 6 levels of list nesting.

💄 Provide up to 6 levels of nesting for lists

---

pages/integrations/amazon_eventbridge.md.erb

We sometimes get customer queries about adding more details to EventBridge payloads. But we are somewhat limited by the size we can include.
So this adds an explanation to the docs about the reasoning and workaround.

Add info about limited EventBridge payload size

---

app/assets/stylesheets/public/_docs.scss
app/views/pages/index.html.erb
pages/apis/webhooks.md.erb
styleguide/STYLE.md

Linear: https://linear.app/buildkite/issue/ONB-16/
Docs [Webhooks Overview page](https://buildkite.com/docs/apis/webhooks) content overflows to the right. This introduces a horizontal scrollbar where one is not expected or desired. Not identified on any other pages.
Impacting all viewport widths. Present with and without new nav banner.
Tracked root cause to the second HTTP headers table which has a long string of example text in it: `timestamp=1619071700,signature=30222eb518dc3fb61ec9e64dd78d163f62cb134a6ldb768f1d40e0edbn6e43f0` This doesn't have any whitespace in it and therefore isn't wrapping nicely
Tried a few options to fix, including adding spaces to the string (fixed the issue but traded off accuracy of the documentation) and trying unsuccessfully to get the text to wrap through …

Fix webhooks overview overflow bug

---

pages/integrations/pagerduty.md.erb
pages/integrations/sso/adfs.md.erb
pages/pipelines/build_meta_data.md.erb
pages/pipelines/job_minutes.md.erb
pages/pipelines/notifications.md.erb
pages/pipelines/permissions.md.erb
vale/styles/Buildkite/existence-case-sensitive.yml
vale/styles/Buildkite/h2-h6_sentence_case.yml

~~This PR has a little bit of overlap with https://github.com/buildkite/docs/pull/1730. It might be better to review that one first.~~
Cleaning up some branches revealed this being more or less ready to go. Fixes mostly the `pipelines` folder. Highlights:
- 📟 PagerDuty "change events" are not capitalized
- "Teams" is no longer capitalized in one heading. This will get us passing lint, though it doesn't make this consistent throughout ("Teams" versus "teams" is mixed up everywhere, including the UI).

H2 sentence-case linting (round 5)

---

pages/test_analytics/elixir_collectors.md.erb
pages/test_analytics/golang_collectors.md.erb
pages/test_analytics/javascript_collectors.md.erb
pages/test_analytics/python_collectors.md.erb
pages/test_analytics/ruby_collectors.md.erb
pages/test_analytics/rust_collectors.md.erb
pages/test_analytics/swift_collectors.md.erb
pages/tutorials/parallel_builds.md.erb
vale/styles/Buildkite/existence-case-sensitive.yml

This is an incremental piece of DOC-369. It attempts to improve the collector intros for increased clarity (avoiding some nerdview around "shipping") and maintainability (making them look alike).
Unfortunately, collectors aren't very alike yet. There's four likely patterns available to collector docs authors:
> To use Test Analytics with your [language] projects use [link to package] with [testing framework].
>
> You can also upload test results by importing [JSON](/docs/test-analytics/importing-json) or [JUnit XML](/docs/test-analytics/importing-junit-xml).
> To use Test Analytics with your [language] projects use [link to package] with [testing framework 1] or [testing framework 2].
>
> You can also upload test results by importing [JSON](/docs/test-analytics/importing-json) or [JUnit …

Regularize test collector intros

---

pages/apis/webhooks.md.erb

Change the variable name for the example webhook signature validation code from `payload` to `webhook_request_body`.
The variable name `payload` here could be misconstrued to be some kind of automatically deserialized request body data, when we actually want webhook recipients to use the raw body string itself.

Hint that the webhook signature be generated off the request body

---

pages/test_analytics/ci_environments.md.erb

`run_env[commit]` > `run_env[commit_sha]`
`commit_sha` is correct. For other CI providers, we have documented `commit_sha`. 
`commit_sha`  is also used in the Ruby Collector.
https://github.com/buildkite/test-collector-ruby/blob/8cb402152a03fbefbdf8cddd0632284a700e3e20/lib/buildkite/test_collector/ci.rb#L58

Fix TA documentation error (Git Commit SHA) 

---

docker-compose.production.yml

The goal is to be able to decide whether Segment script is included in the views.
So that Segment only captures activity in production only.
env var settings in the `Dockerfile` (or more accurately `docker-compose.yml`) override the env vars that are set in Render UI.
Therefore, we set `RENDER_PR_APP` in the Render UI to be true, and this value will propagate to all the review apps. We then set `RENDER_PR_APP` to be false in `docker-compose.yml`
This can be a bit confusing if someone only looks at the Render UI. So hopefully this commit message will help explain the idea. More details and explorations are available in the Linear issue.
Linear: https://linear.app/buildkite/issue/ONB-29/🔗-integrate-docs-with-segment

Set an env var on prod to flag this is not a review app

---

pages/agent/v3/elastic_ci_aws.md.erb

This is what I get from the AMI
```
Starting session with SessionId: 1666063183331033225-000b3f9aa6e7623ec
sh-4.2$ buildkite-agent --version
buildkite-agent version 3.39.1, build 4608
sh-4.2$ docker --version
Docker version 20.10.17, build 100c701
sh-4.2$ docker-compose --version
docker-compose version 1.29.2, build 5becea4c
```

Update documented versions of buildkite-agent, docker, docker-compose

---

Dockerfile
Dockerfile.render

Again with ONB-29.
Setting `RENDER_PR_APP` to `false`
This sets the ENV VAR to `false` in every environment. In Render,
the ENV VAR has been set to `true` via the Render UI. This inherits
to all PR environments inside Render, but can be overridden on
individual PRs via the PR-specific environment settings.
@elle I think this means you can set the tracking VARs appropriately for Render or not. It doesn't solve setting them for other environments like TEST or DEVELOPMENT etc

Set ENV VAR for Render PR Apps to `false`

---

app/controllers/pages_controller.rb
app/views/layouts/_algolia.html.erb
app/views/layouts/_head.html.erb
app/views/layouts/application.html.erb
app/views/layouts/graphql.html.erb
app/views/layouts/homepage.html.erb
app/views/pages/show.html.erb
config/application.rb
config/initializers/generators.rb

... and other small cleanups
What has been done:
- Make `layout_by_path` private
- This is a helper method that should not be accessed externally
- Disable auto generated files when using Rails generators
- Remove temp checks for `ENV` variables
- Define index action for homepage
- To remove the confusion of where the home page is defined,
making it easier to understand what is happening
- Also removing one branch in the layout conditional
- Switch from `provide` to `content_for`
- since we are not using or calling streaming anywhere in the app
- Ref: https://api.rubyonrails.org/classes/ActionController/Streaming.html
- Match title in both layout files
- in prep to clean up the layout views even more
- Pull out the head section in the three layout templates
- to dry the duplication and to …

DRY layout files

---

spec/features/emojicom_rendering_spec.rb

i.e. Emojicom should not be rendered on landing pages
Taken from https://github.com/buildkite/docs/pull/1609

Add specs to confirm Emojicom rendering

---

data/content/environment_variables.yaml

Add some docs for a new environment variables which lists teams for pipelines:

Add BUILDKITE_PIPELINE_TEAMS to env docs

---

pages/pipelines/conditionals.md.erb

We are missing the `failing` state in a table on conditionals for `build.state`, this PR will fix that :)

update build.state available states table

---

pages/integrations/pagerduty.md.erb

- `secretes` -> `secrets`
- Also removed a superfluous `your` that was making the sentence a little awkward

Fix typo (secretes) in pagerduty integration docs

---

pages/pipelines/command_step.md.erb
pages/pipelines/job_minutes.md.erb
pages/test_analytics/monitors.md.erb

**Context**
- On Tuesday (2022-11-15) we [launched the developer plan](https://3.basecamp.com/3453178/buckets/29865999/messages/5526387953)
- The deadline was moved up 2 days to get in ahead of the [funding announcement](https://buildkite.com/blog/buildkite-series-b)
- In all the hubbub updating the docs was missed.
**Actions**
- This updates the docs to reflect:
- the **_Developer Plan_** in place of _**Free Plan**_
- Updated job minutes inclusions to reflect pricing page

Update docs for developer plan nomenclature and limits/inclusions

---

pages/apis/managing_api_tokens.md.erb

After this change: https://github.com/buildkite/buildkite/pull/10259 this comment is no longer correct.
We will prohibit an org being added back to an API access token in the following situations:
- An organization revokes the token
- The User is removed from an organization
basecamp context: https://3.basecamp.com/3453178/buckets/3258372/messages/4855872984#__recording_5456583703

🛎 reword API token comment

---

pages/agent/v3/cli_annotate.md.erb

Buildkite imposes a maximum body size of 1MiB. I couldn't find this documented anywhere.
The `buildkite-agent annotate` CLI help will also be updated if https://github.com/buildkite/agent/pull/1844 is merged.

Document maximum annotation body size

---

pages/pipelines/conditionals.md.erb

`soft_failed` is actually a job state and does not apply at the build level so trying to compare to `soft_failed` results in an error

Remove `soft_failed` from available states

---

pages/integrations/sso/okta.md.erb

We recently learned more about how okta works and this section confuses our customers.
They are two options to provision existing users:
1. Remove and reassign users on okta; or
1. Use "Provision users" function (requires okta Lifecycle Management SKU feature)
More context at [this ticket](https://linear.app/buildkite/issue/FDN-1334/display-scim-panel-on-sso-page-for-all-orgs-with-an-appropriate-plan) (internal only)

Improve the Provisioning existing users section for SSO Okta docs

---

.buildkite/pipeline.yml
docker-compose.yml
pages/agent/v2/gcloud.md.erb
pages/agent/v3/gcloud.md.erb
pages/integrations/docker_hub.md.erb
spec/features/reading_pages_spec.rb

This makes https://github.com/buildkite/docs/pull/1546 work.
Muffet is much faster. The builds used to take ~14-16 min. They are now around 2.5 min. (If the docker images are cached)
However, because rails is so slow to start up, I had to make the `muffet` container wait for a bit before running. Docker-Compose does not have a good way to say that a container should depend on the “readiness” of another container before it starts. So I simulated that with a loop polling the endpoint until it responds 2xx. Unfortunately, just polling the `/` route is not sufficient, as other routes seem to take a while to become “warm” (see some failed builds on this branch). So I chose a route that failed frequently and used it as the test to see if the server is “ready”.
Closes …

Replace link following test with `muffet`

---

pages/agent/v3/help/_artifact_download.md
pages/agent/v3/help/_artifact_search.md
pages/agent/v3/help/_artifact_shasum.md
pages/agent/v3/help/_meta_data_get.md
scripts/cli2md.rb

We're annotating the agent docs with environment variables that don't exist in some cases:
So skip that bit when there is no variable:

Remove empty env vars

---

.buildkite/pipeline.deploy.yml

The rebuild happens once a day so may miss significant new content for up to 24 hours, so trigger a rebuild on deployment.

Rebuild search index after deployment

---

pages/tutorials/getting_started.md.erb

The main point of this PR is to give me a chance to walk through the process of contributing a change to the documentation. The side benefit is fixing up a couple of typos on the Getting started page.

Fix typos in getting started guide

---

app/views/application/_footer.html.erb
config/initializers/content_security_policy.rb

This resolves ONB-108:
https://linear.app/buildkite/issue/ONB-108/csp-issues-with-emojicom-in-docs
This PR replaces https://github.com/buildkite/docs/pull/1798 because git

Update CSP for Emojicom

---

pages/test_analytics/importing_junit_xml.md.erb

PIE-1252 
https://linear.app/buildkite/issue/PIE-1252/document-mandatory-junit-properties
A customer, Robinhood were having issues with uploading their JUnit
XML file. They were missing the mandatory attributes from the
testcase element.
https://3.basecamp.com/3453178/buckets/20365997/messages/5611360141#__recording_5459384344
https://3.basecamp.com/3453178/buckets/20365997/card_tables/cards/5611354161

Add 'Mandatory JUnit XML Attributes' section

---

pages/pipelines/group_step.md.erb

This PR adds `if` and `skip` optional attributes to the group step.
Updated after a Slack inquiry.

Adds if and skip attributes

---

app/assets/javascripts/application.js
app/assets/javascripts/copyToClipboardButton.js
app/assets/stylesheets/public/_copy-to-clipboard-button.scss
app/assets/stylesheets/public/_variables.scss
app/assets/stylesheets/pygments.scss
app/models/page/renderer.rb

It's annoying having to manually copy code snippets from the docs into a shell / editor. 
This PR adds the most basic version of a "Copy to clipboard" button that becomes visible on hover and focus for all code blocks. 
This change still needs a round of design but you get the gist. There's currently no success state (i.e. "Copied 👍🏻) and I've totally guessed my way around icons! 
https://user-images.githubusercontent.com/656826/211252617-a90917cf-2424-4fd5-a973-ecabdefb80b9.mov

Add copy button on code examples

---

pages/agent/v3/elastic_ci_aws.md.erb

This PR updates the documentation to reflect the latest Buildkite Agent version within the Elastic CI Stack for AWS.

Update documented versions of buildkite-agent to v.3.42.0

---

data/content/agent_attributes.yaml

Tiny fix to update a typo in https://buildkite.com/docs/agent/v3/configuration#tags-from-host

Fix typo in tags-from-host default value

---

pages/agent/v3/hooks.md.erb

As part of [Agent v3.42.0](https://github.com/buildkite/agent/releases/tag/v3.42.0), we added a new hook to the agent, `agent-startup`. This hook runs at agent startup, immediately prior to the agent being registered with Buildkite.

Add docs for agent-startup hook

---

README.md

The `git clone` command currently in the README uses HTTPS, and I think most buildkiters are authenticating using SSH. Using the HTTPS command resulted in this error when I tried to push up a branch: 
```
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/buildkite/docs.git/'
```
It took me a minute to realise the issue as I'd just sort of auto-pilot copy+pasted the command. This change will help ensure others don't get caught out in the same way 🌻

Readme Update: Use git clone ssh command in readme.

---

pages/pipelines/environment_variables.md.erb

While using this documentation today I was unsure if the attribute at the top of the yaml file was named the same (`env`).

Be explicit about the yaml file attribute

---

pages/pipelines/block_step.md.erb
pages/pipelines/input_step.md.erb

Going through PR's for https://github.com/buildkite/pipeline-schema there was one for adding underscores to the schema definition for the meta-data key field.
This PR updates the docs to say 'underscore' is an allowed character in the key field.

Add underscores to the list of allowed characters for key

---

pages/apis/rest_api/pipelines.md.erb

Make it clear that if your organisation has enabled teams, that the property becomes required for pipeline creation, not just that it becomes available.  
Trying to create a pipeline without passing the teams property in an org with teams enabled results in a 422 error.

Update requirements for teams property

---

pages/pipelines/block_step.md.erb
pages/pipelines/input_step.md.erb

Recently Pipelines Edge had an [escalation](https://3.basecamp.com/3453178/buckets/23112918/card_tables/cards/5744680321) where a customer was confused as to why the BlockFieldsModal was rendering a dropdown when they had less than 6 options provided. Turns out it's because the `required` field was set to `false`. It's expected behaviour in that it's purposely build into the code, but it also took us a minute to figure out whether this was a bug or not, and why it was implemented this way, as this behaviour is not currently mentioned in the docs! 
The reason is this:
If required == false and radio buttons are rendered, the user cannot "unselect" once an option has been checked. 
This PR adds a bit of extra context to the docs to avoid this confusion in the future.
[Linear …

Block step and input step docs: always render dropdown on blockfieldmodal if required: false

---

pages/apis/rest_api.md.erb

This change updates a link in the REST API docs to use a revised codepen with a valid access token + organisation. 
_Note:_ The access token used has been scoped to a single organisation (buidkite-docs-examples) with no read/write permissions.

Link to a working Codepen example for the Emojis API

---

data/content/environment_variables.yaml

This PR adds BUILDKITE_PLUGIN_CONFIGURATION environment variable according to https://github.com/buildkite/agent/pull/1382. 
It also adds the information about BUILDKITE_PLUGIN_NAME from the same PR. This part is a separate commit and can be removed.

Adds BUILDKITE_PLUGIN_CONFIGURATION env var + more

---

.github/labeler.yml
.github/workflows/labeler.yml

After recently browsing through PRs in this repository I thought it might be nice to add some basic categorisation in the form of GitHub labels. 
This PR adds a new GitHub Action Workflow to automatically apply labels (ie. `pipelines`, `test-analytics`, `agent`, etc). 
I'm sure there's plenty more labels we could add but these seem like the most useful.

Add GitHub Action for labelling PRs

---

.buildkite/pipeline.graphql.yml
.buildkite/update_graphql_docs
Dockerfile
Gemfile
Gemfile.lock
lib/tasks/graphql.rake

This PR adds a new pipeline for auto-generating a pull request with content generated from the latest Buildkite GraphQL schema.
The [pipeline](https://buildkite.com/buildkite/docs-graphql) is currently setup to fetch the latest/active introspected GraphQL schema from buildkite.com which to start with will be triggered on a schedule. This is only temporary as I'm keen to fast follow to instead trigger the pipeline when schema changes are being deployed.
Here's an [example build](https://buildkite.com/buildkite/docs-graphql/builds/44#) and [PR](https://github.com/buildkite/docs/pull/1856) (ignore all the commits from this branch).
Keen to see how this goes. I decided to lean into the PR for visibility in changes but once we're more comfortable then perhaps merging directly into main may …

[ONB-136] Add pipeline for keeping GraphQL docs up-to-date

---

CODEOWNERS

This PR assigns myself as the default reviewer for everything non-content related, @mbelton-buildkite for everything content related, and the onboarding team for everything that's mostly related to the frontend. 
Does this seem about right @mbelton-buildkite?

Add CODEOWNERS file to auto-assign reviewer

---

.buildkite/pipeline.yml
app/assets/javascripts/nav.js
package-lock.json
package.json

To ensure our text editors are all doing the same thing, this change bring in [Prettier](https://prettier.io/) to keep javascript formatting consistent in addition to linting as part of CI.

Use `prettier` for linting Javascript files

---

pages/plugins/writing.md.erb

After some comments in [issue 372 in the plugin linter](https://github.com/buildkite-plugins/buildkite-plugin-linter/issues/372) I believe that some clarifications are necessary on the documentation to write plugins with regards to the `builkite-plugin` suffix and vendored plugins.

Minor clarifications

---

pages/apis/rest_api/builds.md.erb

Now is also possible to send a cancellation signal when the build is in a `failing` state

Update states of cancel builds via API

---

pages/tutorials/github_merge_queue.md

This should help clarify the purpose of the `skip builds with existing commits` option in the pipeline settings, and why it might be used when setting up merge queues in a repo.
It is not a required option, but is useful if you don't want to be creating multiple builds on the same commit, since GitHub will create a temporary branch that will kick off a new build.

add clarification in merge queue tutorial around the "skip builds with existing commits" option

---

pages/pipelines/build_matrix.md
pages/pipelines/command_step.md

We're updating command steps to allow using matrix interpolation within plugin configuration. Adjust the docs to match.
Not ready to merge — the supporting change is yet to be deployed.

Matrix values can now go into plugin config

---

app/views/application/_footer.html.erb

This PR fixes a broken Slack link following the lead of our marketing site https://github.com/buildkite/site/pull/2285

Update footer link to point to the correct Slack channel

---

app/views/application/_analytics.html.erb

This PR adds an additional `firstSource` attribute to page views to help attribute traffic from first-time users visiting the docs.
This code is a direct port of the first source code from `buildkite/site`.

Track first source on /docs page views

---

pages/test_analytics/ruby_collectors.md

Relishapp has historically been an official source of ruby documentation. However, the maintainer was recently made redundant from his job and the website is currently returning a 503. The ruby community will probably either fix the website or find a new site to host this content; however, in the mean time we're linking to the Internet Archive as a stop gap.

Fix Rspec link to instance_of

---

app/views/application/_head.html.erb
app/views/application/_helpscout.html.erb
config/initializers/content_security_policy.rb

Add [HelpScout Beacon](https://secure.helpscout.net/settings/beacons/fe786ba2-4f17-4f4a-a70b-3c79fbf468fe/customize) as an alternative approach for eliciting feedback from within the docs.
The beacon can be controlled indirectly via events in HelpScout or directly by using the JavaScript API.

Add HelpScout Beacon 

---

.github/dependabot.yml

Configure dependabot as per this [helpful suggestion](https://github.com/buildkite/docs/pull/1904#issuecomment-1447543720).

Use dependabot for managing docker image upgrades

---

pages/pipelines/notifications.md

This PR adds an example (step/build levels) for how to mention users within a custom message using the `notify` command in their pipelines.
If any wording changes are needed, let me know!!

Added Slack user mentions example

---

pages/apis/graphql/graphql_cookbook.md

I saw [your discussion on Basecamp](https://3.basecamp.com/3453178/buckets/1713315/chats/269048534@5899272373) and thought it would make a good entry into the cookbook. What do you think?
**Preview:** [Get pipelines by team](https://bk-docs-pr-1913.onrender.com/docs/apis/graphql/graphql-cookbook#get-pipelines-by-team)

Add GraphQL cookbook entry for getting pipelines by team

---

data/nav_graphql.yml
scripts/graphql_api_content/nav_data.rb
spec/scripts/graphql_api_content/nav_data_spec.rb

Looks like some of the recent nav restructures broke the script that generates the GraphQL nav.
This PR fixes the problem and makes the script marginally more robust. Me thinks we should circle back on how this one is generated / rewrites nav items. Seems like we might be missing a level of sub-navigation which is why we need to do this.

Fix GraphQL nav generation

---

.buildkite/pipeline.yml

Asset compilation can fail during deployment, this change tests it earlier.

Add CI step for compiling assets

---

app/helpers/application_helper.rb

Mardi Gras and WorldPride has ended in Sydney, so changing the logo to only display in February for future Sydney Mardi Gras.festivals.

ONB-192: Undo pride logo in March

---

pages/pipelines/build_matrix.md
pages/pipelines/command_step.md

We've updated matrices to support use in agent query rules. This updates the docs to reflect that, as well as adding in an example use.
The code change has hit production, so this can be merged when approved

[PDP-603] Update build matrix docs to list use in agent query rules

---

pages/pipelines/managing_log_output.md

Changed the description of our Private S3 Bucket logging docs to say that it is exclusive: basically Buildkite managed logs are default, but tenants can choose to have logs located in their own S3 bucket instead.
**Original Issue**
Customer asked us if turning this on would be exclusive or inclusive: i.e if logs are duplicated across BK and private buckets, or if it is a cutover.

Clarified exclusivity for Private S3 bucket logging

---

pages/integrations/sso.md

The docs currently state that SSO can be set as `Optional` in the team settings, it's actually in the `User` settings for individual users in the organization's global settings.

Correct location for setting SSO as optional for users.

---

pages/pipelines/scheduled_builds.md

We received a few questions from the customer on the delays of the scheduled builds running. Updating the docs with better explanation would help our customers understand this behaviour.

Update Interval Granularity

---

data/nav.yml

This page is still linked from the product, but not included in the docs nav. I believe this was a mistake, so I'm fixing it.
Adding it to previous location shown in: https://web.archive.org/web/20201125105028/https://buildkite.com/docs/pipelines/emojis

DOCS-573: Add emoji page to the nav

---

data/nav.yml
pages/agent/v3/cli_annotation.md

This was already being linked to from the annotate page.

DOCS-573: Add CLI annotation reference back to the nav

---

data/nav.yml

[Discussed on Basecamp](https://3.basecamp.com/3453178/buckets/1713315/chats/269048534@5949815373)

DOCS-573: Add Docker Hub page back to the nav

---

pages/integrations/amazon_eventbridge.md

This is to replace the PR https://github.com/buildkite/docs/pull/1918 which is to expand add details about Eventbridge notifications job results.
Reference: https://secure.helpscout.net/conversation/2174018311/47841 - asked recently, and another one https://secure.helpscout.net/conversation/1010246694/7911/ asked from 3 yrs ago

Add details on a job finished event

---

app/assets/stylesheets/base/_fonts.scss
app/views/application/_head.html.erb

There's a diagram that's expecting a bold font that doesn't currently exist.
https://buildkite.com/docs/agent/v3
Similar to https://github.com/buildkite/docs/pull/1941 this PR adds the necessary bold font variant in addition to removing a few other unused/invalid fonts.

Fix docs diagram

---

pages/apis/rest_api/analytics/flaky_tests.md

`{:toc}` appears to have been removed since the original PR was created, and no longer renders correctly. This PR removes that random string from the API page for Flaky Tests
[PIE-1458](https://linear.app/buildkite/issue/PIE-1458/release-flaky-test-tracker-api-documentation)

PIE-1458: Remove errant {:toc} from Flaky tests API page

---

pages/test_analytics.md

Jasmine and Mocha support was added to TA last year. The JS test collector README and docs were updated recently, but these test suites had not been listed on the "Get Started" page.
[PIE-1508](https://linear.app/buildkite/issue/PIE-1508/add-jasmine-and-mocha-support-to-docs-overview-page-and-in-app)

PIE-1508: Add mocha and jasmine to TA Get Started page

---

pages/pipelines/command_step.md

Add reference documentation for the signal and signal reason attributes which will soon be available in automatic retry rules.
Fixes PDP-211.

Add signal and signal reason in retry rules

---

pages/apis/managing_api_tokens.md
vale/styles/vocab.txt

we've just added this feature to the UI / Graphql, so just getting the docs site in order 😁
The `http://localhost:3000/docs/apis/managing-api-tokens` page seems like the most logical location.
https://bk-docs-pr-1924.onrender.com/docs/apis/managing-api-tokens#limiting-api-access-by-ip-address

feat: add docs about limiting API access by IP

---

pages/apis/api_differences.md

Adds a line about cancelling jobs, which can only be done with the GraphQL API

Update to GraphQL only functionality on Jobs

---

pages/pipelines/command_step.md

- Adds `signal` and `signal_reason` defaults
- Adds `agent_stop` as an example value for `signal_reason`, so that I can point to it in the changelog (it's commonly used for handling instance spot termination)
Extends https://github.com/buildkite/docs/pull/1883

[PDP-211] Add signal and signal_reason to the default value for automatic retries

---

pages/test_analytics/importing_json.md

When troubleshooting, I noticed we missed a double quotation mark in our HTTP example in the docs. This commit adds the missing double quotation mark.

fix missing quotation mark in HTTP example

---

pages/apis/graphql/graphql_cookbook.md
pages/integrations/sso.md

This PR adds docs for SSO Session IP Address Pinning feature.
`/docs/integrations/sso#sso-session-ip-address-pinning`:
The `GraphQL API` link goes to following GraphQL cookbook `/docs/apis/graphql/graphql-cookbook#update-the-sso-provider-session-ip-address-pinning`:
FDN-2327

Docs for SSO Session IP Address Pinning

---

data/content/test_analytics_json_fields_test_result.yaml
pages/test_analytics/importing_json.md

PIE-1519
We recently removed support of the 'identifier' attribute and
made the 'name' attribute mandatory.
This PR updates the documentation on importing JSON to reflect
this recent change.
For additional context, the collectors have been updated to
remove support for the 'identifier' attribute.
Importing JUnit XML never support the 'identifier' attribute so
no documentation changes are required for that page.

[PIE-1519] Update TA docs on 'Test result objects' when importing JSON

---

pages/agent/v3/macos.md

I've also updated the formatting to make the instructions clearer.
**Preview:** [Installing Buildkite Agent on macOS
](https://bk-docs-pr-1991.onrender.com/docs/agent/v3/macos)

Add starting the agent to macOS agent instructions

---

pages/agent/v3/securing.md

When I tried to use the example syntax for the `pre-bootstrap` script, it failed because it didn't strip the leading and trailing quotes when extracting the value of a Buildkite env var from `BUILDKITE_ENV_FILE`. Adding the appropriate `sed` call made my script work.

Fix bug in pre-bootstrap example in securing.md

---

pages/pipelines/trigger_step.md

/docs/pipelines/trigger-step
Adding soft_fail attribute to trigger step (soft_fail is already existing for [command step](https://buildkite.com/docs/pipelines/command-step))

PDP-699 updating documentation for trigger steps to include soft_fail attribute

---

pages/agent/v3/cli_oidc.md

The URIs for using OIDC are missing from the documentation, adding them in will enable folks to adopt OIDC more easily. The `kid` should also be present in the JWK payload.

Add additional info for OIDC endpoints

---

pages/plugins/using.md

We occasionally get questions around setting plugins on a pipeline rather than a step, this isn't possible but one can use yaml anchors in order to avoid repetition.

Added information around using YAML anchors

---

pages/integrations/sso/okta.md

We support JIT provisioning with Okta, so I think it's important that is clarified in our docs (rather than just as an FAQ).
@mbelton-buildkite I'm not sure this is entirely the right spot for this, but I do think it's something we should have written down, so if you have other suggestions for where this information can go, please suggest!

update sso docs (okta) with extra detail around account provisioning

---

pages/pipelines/command_step.md

The current syntax isn't valid, it triggers the error
> `reason` is not a valid property on the retry ruleset. Please check the documentation to get a full list of supported properties.
The updated file matches the correct syntax used lower down on the page.

Fix example in retry docs

---

pages/apis/graphql/graphql_tutorial.md
pages/apis/graphql_api.md
pages/apis/rest_api.md
pages/apis/rest_api/agents.md
pages/apis/rest_api/builds.md
pages/apis/rest_api/jobs.md
pages/apis/rest_api/pipelines.md
pages/integrations/git.md
pages/pipelines/secrets.md

By default curl will set the content type header to application/x-www-form-urlencoded. This PR updates our curl examples to explicitly set the content type header to application/json.

Add json content type header to all curl examples with json data

---

pages/pipelines/defining_steps.md

This only works as expeted for pipelines with legacy (UI-defined) steps, not for pipelines with YAML steps.
Remove this for now to avoid customer confusion.

Remove "Cloning a pipeline" section

---

pages/integrations/bitbucket.md

Bitbucket support for Mercurial was removed in 2020: https://bitbucket.org/blog/sunsetting-mercurial-support-in-bitbucket

DOC-529: Remove Mercurial support from Bitbucket page

---

app/assets/javascripts/nav.js
app/views/application/_nav_link.html.erb

This change updates pre-expanded navigation to render the expand/collapse toggle.
To render navigation expanded navigation you can use the following:
```
start_expanded: true
```
| Before | After |
| --- | --- |
| <img width="786" alt="Screenshot 2023-04-17 at 3 39 14 pm" src="https://user-images.githubusercontent.com/656826/232392730-36f5a4ab-3f04-432d-b6b2-c5c858791ec3.png"> | <img width="786" alt="Screenshot 2023-04-17 at 3 39 27 pm" src="https://user-images.githubusercontent.com/656826/232393125-95d03ddd-9792-41ce-8c30-5d47273e7cfc.png"> |

Render toggle for pre-expanded navigation

---

app/assets/stylesheets/base/_text_content.scss
app/assets/stylesheets/base/_variables.scss
app/assets/stylesheets/components/_copy_to_clipboard_button.scss
app/assets/stylesheets/pages/_docs.scss
pages/tutorials/getting_started.md

I'm packaging numerous styling tweaks planned for Docs Week into one PR. The changes are:
- Code styling improvements:
- DOC-519: Make inline code more visually distinct
- DOC-578: Fix headings with monospaced font
- DOC-602: Match internal link style with .com site and app (use purple)
- DOC-603: Fix copy button style (position alignment)
Manually tested in macOS Webkit and Windows Edge.

💄 Design styling fixes for Docs Week Q2

---

app/assets/javascripts/toc.js
app/assets/stylesheets/components/_toc.scss
app/models/page.rb
app/models/page/data_extractor.rb
app/views/application/_toc.html.erb
app/views/pages/show.html.erb
spec/models/page/data_extractor_spec.rb

Extract H3s from page content and optionally render them into the table of contents for pages that opt-in.
e.g. example.md
```markdown
---
h3s: true
---
```
I've used `h3s: true` as the configuration attribute but totally open to something more descriptive. Perhaps `toc_depth` or something along those lines? 
I've also left the styling wide open, perhaps @olyism has some feels on this one.

Add ability to render H3s in Table of Contents

---

pages/apis/rest_api.md

Add a missing ability to the documentation about authentication using the Rest API.
Clarifies that auth tokens can be used as a query parameter by going `...?access_token=$TOKEN`.
Please check I'm using language properly.
https://linear.app/buildkite/issue/DOC-561/document-auth-in-query-parameter

DOCS-561 Add URL Query Param auth method for rest API

---

pages/pipelines/command_step.md

Whenever command steps have timed out and if the hooks or artifact upload needs more time customers can define cancel-grace-period flag to extend the grace period.

Add note for build timeout

---

app/models/page.rb
pages/agent/v3/aws.md
pages/agent/v3/elastic_ci_aws.md
pages/integrations/sso.md
pages/integrations/sso/sso_setup_with_graphql.md
pages/pipelines/notifications.md
pages/pipelines/scheduled_builds.md

This change switches the default behavior of the on-page nav to include H3s by default. Almost all pages benefit from showing their H3s. Those that don't have been excluded in this PR.
I've also removed any usage of `toc_include_h3: true` now that it's the default behavior.

Add H3s to the on-page nav by default

---

app/models/beta_pages.rb
data/nav.yml

I noticed that we forgot to label this as a beta feature:
**Live preview:** [Clusters](https://bk-docs-pr-1989.onrender.com/docs/agent/clusters)

Add beta lozenge to clusters

---

app/controllers/application_controller.rb
app/models/nav.rb
app/views/application/_nav.html.erb
app/views/application/_sidebar.html.erb
config/initializers/nav.rb
spec/models/nav_spec.rb

The navigation data is loaded from YAML and transformed into a structured for fast lookup when highlighting the active path. This data never changes so we can do this once on app startup.

Load nav into memory on app startup

---

config/environments/development.rb

There seems to be an issue with the listen gem running on linux/amd64 which prevents the app from running on docker. 
I found a [workaround](https://github.com/evilmartians/terraforming-rails/issues/34#issuecomment-1347442704) which seems fine since we're likely to stop using sprockets (https://github.com/buildkite/docs/pull/2064)

Work around listen gem issue

---

README.md
bin/setup

Now that docs uses Vite for assets we need to install node deps (via yarn) as part of setup. 
cc / @123sarahj123

Update dev docs for installing dependencies

---

pages/pipelines/links_and_images_in_log_output.md

Before this documentation change, the `inline_link` method:
- Generated a link for a decoded URL
- Generated a link for a decoded URL and a custom label
- Generated a link for an encoded URL
- Could not generate a link for an encoded URL and a custom label
This documentation change allows the `inline_link` example function to generate links for encoded URLs and custom labels correctly.
When using the current example function:
```sh
inline_link "https://buildkite.com/"
inline_link "https://buildkite.com/%20"
inline_link "https://buildkite.com/" "test"
inline_link "https://buildkite.com/%20" "test"
```
When using the new example function:
```sh
inline_link "https://buildkite.com/"
inline_link "https://buildkite.com/%20"
inline_link "https://buildkite.com/" "test"
inline_link …
```

Update `inline_link` method example to work with encoded URLs

---

data/content/environment_variables.yaml

This PR updates the explanation of environment variable BUILDKITE_MESSAGE where it can be empty of build is triggered from UI and user does not set the message in the build dialog box

Update BUILDKITE_MESSAGE empty scenario

---

pages/pipelines/build_matrix.md

This update adjusts the section in our docs that relates to matrix limits. The current limits have changed and our documentation still provides the old values. This update will bring the limits in line with the code base.

update matrix limits to correct values

---

pages/pipelines/controlling_concurrency.md

Currently if concurrency gates have block/input step then it wont support it

Add note about block/input step not supported

---

app/assets/stylesheets/base/_article.scss

Similar to https://github.com/buildkite/docs/pull/2073 this fixes long code snippets from overflowing content.

Wrap long inline-code blocks

---

app/assets/stylesheets/base/_article.scss
app/assets/stylesheets/utilities/_responsive_image_container.scss
app/models/page.rb
pages/tutorials/getting_started.md

I noted we're rendering some `<!-- vale` comments and applying some global image styles to the [getting started page](https://buildkite.com/docs/tutorials/getting-started).
This PR does some housekeeping to remove the need to opt-out of certain image styles hopefully preventing images from breaking in the future.
Before:
After:

Fix broken image styles

---

pages/apis/webhooks.md

We have build.failing event now present for webhooks but documentation is missing for this.

update events to include build.failing event

---

pages/agent/v3/hooks.md

This is to add a note that agent-startup hook is support from agent version 3.42.0 or above as we recently saw a user had issues and it turned out they are running on version older than v3.42.0 where hook did not run

Add note that agent-startup hook is supported

---

pages/test_analytics/test_suites.md

Test Analytics has just shipped a change to the way flaky tests are detected. Previously, this was done on a once-a-day cron. Now, detection happens on run finish (throughout the day).
This PR updates our documentation to reflect this change.

Update flake detection time period

---

app/assets/stylesheets/pages/_docs.scss

A small frontend PR to fix the overuse of 'beta' tags on Docs article pages.
- Current behavior: when I set a page to beta, all headings on that page gets the 'beta' tag appended.
- Expected behavior: the beta tag is only needed on the nav item and the first heading for the user to become aware that it's beta 
This fix resolves the problem for the Clusters page and five Test Analytics pages (beta collectors and flaky test API).
This is fixed with a small styling change. However, it'd be worth to change how tags like 'beta' and 'deprecated' are handled throughout Docs, because currently it involves double-handling specifying it in `nav.yml` and `beta_pages.rb`.
Furthermore, the 'deprecated' tag is handled differently and defined only in `nav.yml` and it doesn't get appended to deprecated …

🐛 Only the `h1` need beta tag

---

README.md
config/initializers/nav.rb
data/nav_graphql.yml
scripts/generate_graphql_api_content.rb
scripts/graphql_api_content/nav_data.rb
spec/scripts/graphql_api_content/nav_data_spec.rb

The current workflow for modifying the nav is a little clunky. This PR wires up the nav data on boot so that now there's no requirement to regenerate the nav when moving around items. 
The GraphQL generation script now generates a file with _only_ the GraphQL items rather than a consolidated nav.yml file.

Simplify nav generation

---

data/content/agent_attributes.yaml
pages/plugins/writing.md

We had a user who was trying to use `BUILDKITE_PLUGINS_ALWAYS_CLONE_FRESH` but it did not work as this feature was introduced in agent release v3.37.0 or above. This PR updates the pages to include a note that mentions release this configuration is introduced.

Added note about the agent release in which `BUILDKITE_PLUGINS_ALWAYS_CLONE_FRESH` is introduced

---

pages/integrations/slack.md.erb

Currently the only definition I could find for what 'fixed' means in the context of Slack notifications was [here](https://buildkite.com/docs/integrations/slack#adding-a-notification-service), which is confusing and very difficult to find.
We should clarify what is meant by fixed as well as how it functions at the pipeline outcome level and not the step level.
:smile_cat:

Added description for what 'fixed' means for Slack

---

pages/plugins/writing.md

Referring to the documentation in https://github.com/buildkite-plugins/buildkite-plugin-tester, the path for `load.bash` needs to be updated.

Update sample test in pages/plugins/writing.md

---

data/content/aws-stack.yml
pages/agent/v3/elastic_ci_aws/parameters.md

The documentation for the elastic ci stack parameters was derived from a vendored stack template, which needs to be manually updated. We had not done this in a while, and we had added a few new parameters since then.
Also, the page was attempting to render everything between `:` as emojis. As `:aws:` is a valid Buildkite emoji, if any stack parameter value were an ARN, it would render part of it as an emoji. It's necessary to do this as there is as a new stack parameter default value that is `arn:aws:serverlessrepo:us-east-1:172840064832:applications/buildkite-agent-scaler`, which was being rendered as in the screenshot below prior to this change.
Now, it is rendered as:

Update docs on Elastic CI Stack Parameters to v5.20

---

pages/apis/rest_api/annotations.md

Just ran into this - it points to the [`pipeline` subcommand](https://buildkite.com/docs/agent/v3/cli-pipeline) when it should point to the [`annotate` subcommand](https://buildkite.com/docs/agent/v3/cli-annotate).

Fix link to `annotate` subcommand in annotation API doc page

---

app/models/page.rb
spec/models/page_spec.rb

Partial templates (markdown files prefixed with `_`) are not intended to be rendered directly and should not be included in the sitemap.

Remove partial template routes from sitemap

---

data/content/agent_attributes.yaml

This adds documentation for metrics-datadog-distributions, which was added in https://github.com/buildkite/agent/pull/1433.
Please note that I don't actually know how to test this at all -- do I get a rendered version of the site in the PR?

Add metrics-datadog-distributions documentation

---

pages/integrations/github.md

This add information on how users can prefix third-party fork branch names

Add documentation around prefix third-party fork branch names

---

pages/agent/v3/queues.md

Responds to [EDGE-882](https://linear.app/buildkite/issue/EDGE-882/update-queue-docs-to-point-to-cluster-queues) 
- Adds a link to point the user to cluster queue setup from the agent queues page, and lets them know that for cluster queues they'll need to explicitly create the queue first for it to work.

Add link to cluster queues documentation from agents queues

---

pages/agent/clusters.md

This PR is to get the ball rolling on the documentation for Pausing Cluster Queues. This is an upcoming feature that allows users to "Pause" a cluster queue. When paused, job dispatch to agents associated with that queue is prevented. When resumed, job dispatch picks up where it left off. At first, pausing queues will be possible via the Buildkite UI and GraphQL API only. We will be adding REST API support for this as part of upcoming Clusters work later on.
For this first draft I've made a 'best guess' at what to include, given the existing structure of the Clusters docs. I'm sure there's lots of room for improvement, so would love feedback on this.

Add Pausing Cluster Queues documentation

---

pages/apis/graphql/graphql_cookbook.md

The "input" of the `concurrency` doesn't take an unnamed string as an argument, it must be defined as `group`.

Correct the recipe for concurrency group filter

---

pages/apis/rest_api.md

Adds link to Java based REST API Client library [Buildkite-Api-Client](https://github.com/SourceLabOrg/Buildkite-Api-Client)

Include Java api rest client link

---

pages/pipelines/_block_wait.md

It is possible to use a `wait` with a `block`, but conditionals need to be used and the `wait` must come before the `block` in order to ensure it's not considered part of the blocked steps.
This makes sense where scheduled pipelines deploy some infrastructure, but when a human makes a change we want that deploy to be verified.

Additional info on using WAIT with BLOCK

---

pages/apis/rest_api/analytics/flaky_tests.md

PIE-1681
The web_url attribute of the flaky tests API is incorrectly a 'path'
rather than a full URL.
```
"web_url":
"/organizations/my_great_org/analytics/suites/my_suite_name/tests/01867216-8478-7fde-a55a-0300f88bb49b"
```
To be consistent with the other APIs (e.g.
https://buildkite.com/docs/apis/rest-api/builds#list-builds-for-a-pipeline),
the web_url attribute should be a URL
"web_url":
"https://buildkite.com/organizations/my_great_org/analytics/suites/my_suite_name/tests/01867216-8478-7fde-a55a-0300f88bb49b"

[PIE-1681] Fix Fix web_url attribute on Flaky Tests API

---

pages/pipelines/build_meta_data.md

Meta-data can only be **set** via the `buildkite-agent meta-data set` command, as it requires an agent token for auth and can't be used outside of the agent context. 
I think this could be worded better, but wanted to get something started :)

add clarity around methods that can be used to set meta-data

---

pages/apis/graphql/graphql_cookbook.md

This will add a GraphQL query to the cookbook that will query for all builds on a pipeline

Get all builds for pipeline graphql

---

pages/pipelines/trigger_step.md

This pull request removes mention of `exit_status` from , since trigger steps don't run a command, so they don't have an exit status.
The pipeline parser fails with this error if `exit_status` is provided:
> The `soft_fail` ruleset on a `trigger` step must either be `true` or `false`
Because there's no remaining optional Soft fail attributes, I've deleted that entire section.

Trigger step `soft_fail` doesn't accept `exit_status`

---

.buildkite/pipeline.preview.yml
bin/deploy-preview

Now that I've better configured the Github triggers I think we should always use the pull request ID in the preview URL.
This change updates the preview script to require a pull request ID.

Only deploy previews for pull requests (not branches)

---

pages/apis/rest_api/clusters.md

Document ability to set `default_queue_id` for clusters implemented in https://github.com/buildkite/buildkite/pull/12463

document setting default queue for clusters with the REST API

---

pages/pipelines/defining_steps.md

When using multiple dynamic pipelines from the same step, these are shown in reverse order in the UI (i.e. steps uploaded in the second call to pipeline upload show up before the first call). This is confusing for some people and there's a workaround if they want to see them in the "expected" order

Clarification on pipeline upload order

---

data/content/environment_variables.yaml

In my plugins and pipelines, I want to be able to augment the behavior if the step is running via a `bk local run` command. An example of this would be a "docker push" plugin, which might look like
```yaml
steps:
- command: docker pull alpine
plugins:
- example/docker:
push_local_image: alpine
```
When executing via the actual agents, this would take the local alpine image, get some credentials, and push the image to the company's registry.
However, having a plugin like this now makes it so that this step _cannot_ be run in a `bk local run` context. As far as I can tell from the docs, there is no way for the plugin to augment its behavior to make it acceptable to run locally, and it's common to make it so users _can't_ just push from their laptops.
This PR updates the possible values for …

Make "local" an official BUILDKITE_SOURCE

---

pages/apis/rest_api/clusters.md

Add documentation for [listing and getting cluster queues](https://github.com/buildkite/buildkite/pull/12402) with the REST API. This should only be merged once the API implementation is live.
Preview docs: https://bk-docs-pr-2140.onrender.com/docs/apis/rest-api/clusters
Linear: [EDGE-988](https://linear.app/buildkite/issue/EDGE-988/rest-api-list-and-get-cluster-queue)

REST API: Clusters Queues list/get documentation

---

pages/pipelines/notifications.md

If you omit this, you get the following error message when editing pipeline steps:
```
The `slack` notification is invalid: Each channel should be defined as `#channel-name`, `team-name#channel-name`, 'team-name@user-name', '@user-name'` message 
```

Add missing "#" to notify -> slack -> channels example for step-level Slack notifications

---

.buildkite/pipeline.preview.yml
bin/deploy-preview

We'd like to be able to manually trigger previews either via API or dashboard. 
This change removes usage of `BUILDKITE_PULL_REQUEST` in favour of looking up the pull request number via the Github API.

Find pull request number for the current branch

---

pages/apis/rest_api/clusters.md

Builds on #2155.
Add docs for https://github.com/buildkite/buildkite/pull/12395 which implements REST API support for pausing and resuming cluster queues. This should only be merged after the API endpoints are deployed.
I updated the existing response examples for cluster queues to omit dispatch attributes to make it clear they're only set once a queue is paused (and it makes them a bit less noisy too).
Preview docs: https://bk-docs-pr-2166.onrender.com/docs/apis/rest-api/clusters#cluster-queues-pause-a-queue

add documentation for pausing and resuming cluster queues with the REST API

---

app/models/beta_pages.rb
data/nav.yml
pages/apis/rest_api/analytics/suites.md

Add information about analytics Suite#show API endpoint
**Linear:** https://linear.app/buildkite/issue/PIE-1675/rest-api-endpoints-documentation-suiteshow
The endpoint is currently behind a feature flag. I'm not sure if I can also hide the link to this doc page behind a feature flag, or hold off releasing this PR until the endpoint is publicly released.

PIE-1675 Analytics rest api suite#show docs 

---

app/models/beta_pages.rb
data/nav.yml
pages/apis/rest_api/analytics/tests.md

Add documentation on a new Test Analytics REST API endpoint which displays
basic information about a test (beta).
PIE-1710
https://linear.app/buildkite/issue/PIE-1710/rest-api-endpoints-documentation-testshow
This PR merges into a long-living branch/PR [pie-1713-release-ta-rest-api-documentation](https://github.com/buildkite/docs/tree/pie-1713-release-ta-rest-api-documentation), https://github.com/buildkite/docs/pull/2189
That PR will be released when we are ready to publish the new pages.

Add documentation on tests#show Test Analytics REST API endpoint

---

app/assets/stylesheets/components/_search.scss

Just a small suggestion to adjust the optical appearance of the `/` keyboard affordance in the search bar 🙂

Remove light grey border from search kbd widget

---

.buildkite/pipeline.preview.yml
bin/deploy-preview
bin/prepare-preview
bin/utils.sh

Post placeholder site and Github comment to let users know something is happening. 
1. Deploy a lightweight placeholder site to get a preview URL (it might even be worth making this nice one day)
2. Avoid dependencies and interact with REST APIs so that we can post a Github ASAP, rather than waiting for docker images to build which takes aaaaaaages.
Seems to work alright...
Placeholder site:
It's worth noting that I'm blowing away the preview website on every deployment. I think that's probably fine but if not then I'm sure could also do some extra checks using some Netlify APIs.

Add placeholder preview URL comment

---

pages/apis/rest_api/clusters.md

I noticed a typo in the docs for pausing cluster queues - here's a quick PR to fix it

Fix typo in cluster queue pausing REST API docs 

---

pages/apis/rest_api/analytics/runs.md

**Description**
Add documentation about test analytics runs#index API endpoint
Linear https://linear.app/buildkite/issue/PIE-1719/rest-api-endpoints-documentation-runindex
This branch will be merged into a long living branch [pie-1713-release-ta-rest-api-documentation](https://github.com/buildkite/docs/tree/pie-1713-release-ta-rest-api-documentation) as the endpoint is behind a feature flag.

PIE-1719 Test analytics rest api runs#index docs

---

pages/pipelines/build_exports.md
pages/pipelines/build_retention.md

Behind the scenes, we've been working on a project that will allow Enterprise organizatons to configure a Google Cloud Storage bucket as a location for us to export build data to. This PR update the _build retention_ and _build exports_ pages to reflect this change.
Preview URL: https://2200--bk-docs-preview.netlify.app/
- Project page: [Build exports to GCS](https://3.basecamp.com/3453178/buckets/27608512/messages/6225252145#__recording_6235033131)
- Resolves https://linear.app/buildkite/issue/PDP-1081/update-build-exports-documentation
- Resolves https://linear.app/buildkite/issue/PDP-1082/update-build-retention-documentation

Update/Document GCS support for build retention and build exports

---

pages/apis/managing_api_tokens.md
pages/apis/rest_api/analytics/flaky_tests.md

This is the first step in removing read_flaky_tests. Next steps will include migrating existing tokens and updating terraform providers etc. At some point we aim to remove it from the docs completely.
https://linear.app/buildkite/issue/PIE-1800/demote-flaky-tests-scope-and-promote-read-suites-scope

Deprecate read_flaky_tests scope in favour of read_suites

---

pages/apis/managing_api_tokens.md

I forgot to add this in 9b6accd6a09af7121e42ff10b0236c3ebc36fe7e. Technically we don't have the ability to update or delete suites via the api at present. However, it's coming very soon. I think it's important to include because any tokens with the write_suites scope will soon have the ability to update and delete them.

Document write_suites scope

---

pages/apis/rest_api/analytics/suites.md

I just spotted a bug on our docs:
I think it should be buildkite.com rather than buildkite.localhost

Bugfix curl command for Suite#create (localhost => com)

---

pages/apis/rest_api/analytics/suites.md

PIE-1810
The documentation for creating a suite via API [1] uses HTTP rather than
HTTPS.
Attempting to make a request via HTTP will result in a 301 Move
Permanently response which will ultimately fail as the HTTP client may
make a GET request when following the redirect.
[1]
https://buildkite.com/docs/apis/rest-api/analytics/suites#create-a-suite

[PIE-1810] Fix typo in suites#create documentation (http->https)

---

.buildkite/pipeline.yml

To avoid DockerHub's rate limiting.
We want to use the public ECR so we don't need to authenticate during
the build.
Guide
https://guide.buildkite.net/engineering/getting-started/ci/docker/index.html#use-a-pull-through-cache

Update pipeline.yml to pull from AWS ECR

---

pages/apis/api_differences.md

We don't currently have any mutations to create API tokens via GraphQL, so this will remove misleading entries on the differences page.

Remove graphql create and remove token entry in api differences

---

data/content/agent_attributes.yaml
data/content/environment_variables.yaml
pages/agent/v3.md

This change suggest a pattern for handling agent experiments that have been promoted:
- Note version it became a full feature in the configuration reference.
- List them in a new section on the agent overview, newest first.
I'd like to come back to this in the future, but think it solves the immediate need from #2196. What do you think?

Pattern for promoted experiments

---

pages/tutorials/parallel_builds.md

A new section of the parallel builds guide.
Note to self: this will need updating for the next agent release.

Add 'coordinating multiple agents'

---

pages/apis/graphql/graphql_cookbook.md
pages/pipelines/job_minutes.md
pages/test_analytics/test_executions.md

We've recently added the ability to query Usage data via the GraphQL API. 
- [Project Page](https://3.basecamp.com/3453178/buckets/29554282/messages/6006048651)
- [Coda](https://coda.io/d/Buildkite-Roadmap_dUWyuyLHsQw/Marketing-Release-Train_su-L0#June-Release_tuTsj/r1&view=modal)

Document the GraphQL Usage API

---

data/nav_graphql.yml
pages/apis/graphql/graphql_resource_limits.md

Public documentation of GraphQL resource limits.
More context:
https://3.basecamp.com/3453178/buckets/1933834/messages/6221093655
https://3.basecamp.com/3453178/buckets/23328660/messages/6161786100#__recording_6176276293
This PR 
* adds a nav item under API > Graphql > Limits
* Adds markdown file with graphql rate limits documentation

rate limits documentation

---

pages/apis/rest_api/analytics/suites.md

Add documentation about test analytics Suites#update and Suite#destroy API endpoints
Suites#update:
Suite#destroy:

[PIE-1819] Documentation for Analytics REST API Suites#update and Suite#destroy

---

pages/test_analytics.md

The TA page needs a lot of updates, but something quick we can add, and customers asked, is about the details of the data retention, which is currently of 6 months.

Add data retention

---

data/nav.yml
pages/pipelines/governance.md

Pipeline templates is a new feature in the upcoming release. We're including documentation for it in a new section of the docs called "Governance" in #2255. I thought it would be good to include any existing pages that would fit better in that section and @ozdenyilmaz mentioned that Build exports would be a good candidate.
What do you think?

Proposal: Move Build exports page into Governance section

---

data/nav.yml
pages/apis/webhooks.md
pages/apis/webhooks/_agent_events_table.md
pages/apis/webhooks/agent_events.md
pages/apis/webhooks/cluster_token_events.md
pages/clusters/manage_clusters.md
pages/integrations/amazon_eventbridge.md

- Update Event Bridge docs with two new notifications
- Update Webhook docs with two new notifications
- Update allowed IP addresses docs to note it doesn't apply to metrics API

Add webhook + eventbridge docs for new CIDR locked tokens

---

pages/apis/webhooks/build_events.md
pages/apis/webhooks/job_events.md

This formatting change is to help make the object types more obvious. Rather than reproducing them in the webhook event pages, we'll keep the REST API as the source of truth for ease of maintenance. 
These changes match a recent change in the Agent and Cluster token event pages.

Update event formatting of webhook data

---

scripts/graphql_api_content/nav_data.rb
spec/scripts/graphql_api_content/nav_data_spec.rb

Limits doc was introduced in https://github.com/buildkite/docs/pull/2229 and it should have updated this `scripts/graphql_api_content/nav_data.rb` instead of the resulting `data/nav_graphql.yml`.

Add Limits to GraphQL nav data

---

pages/pipelines/notifications.md

The specifics of how to tag a user on Slack were wrong. Also added some info on how to tag user groups, with links to the appropriate Slack docs.

Correct documentation on mentioning users in Slack notification custom messages

---

pages/apis/graphql/graphql_cookbook.md

querying audit events is possible via GraphQL, for Enterprise customers.

add GraphQL query for audit events

---

pages/agent/v3/tokens.md

With a recent [security update](https://buildkite.com/changelog/207-agent-token-being-deprecated-from-graphql-apis) from Buildkite, the `token` field in `agentTokenEdge` is deprecated but is now changed to `tokenValue` to retrieve the token when creating one through `agentTokenCreate` mutation.
- Updates the `buildkite-agent` `v3` documentation to use updated GraphQL API when creating agent token

[Update] Updating `agentTokenCreate` mutation to use new `tokenValue`.

---

pages/pipelines/templates.md

We recently modified the user flow for creating a Pipeline template so we need docs to reflect this change. We no longer immediately create a template, we now follow a more standard creation flow: click create > fill out a form > click save.

Update docs for 'Creating a pipeline template'

---

pages/apis/graphql/graphql_resource_limits.md

We had some confusion from customers about the value of the header required to access the query complexity. 
This change makes it explicit that the value of `true` needs to be passed in the header.

Clarify how to view query complexity of a query

---

pages/pipelines/input_step.md

This PR adds a section on input validation - the very existence of this option and guidelines about the syntax to use based on the following Buildkite Forum post: https://forum.buildkite.community/t/regex-validation-for-step-input/1260/3

Adds a section on input validation

---

pages/agent/v3/macos.md

Without the fully-qualified formula name, `brew` might complain, _eg_:
```
$ brew tap buildkite/buildkite && brew install buildkite-agent
Error: Formulae found in multiple taps:
* shopify/shopify/buildkite-agent
* buildkite/buildkite/buildkite-agent
Please use the fully-qualified name (e.g. shopify/shopify/buildkite-agent) to refer to the formula.
```

Use fully-qualified brew formula name w/tap to avoid ambiguity

---

pages/test_analytics/ci_environments.md

A lot of our customers are confused about setting environment variables and why they should be doing it. I've added this new section to the CI environments page, which hopefully encourages more customers to set these variables:
I've also updated the bullet points at the top section to jump to the CI specific info
[Linear Card](https://linear.app/buildkite/issue/PIE-1704/improve-documentation-for-environment-variables)

Improve Test Analytics Environment Variable docs

---

pages/apis/rest_api/builds.md

As per [this conversation](https://buildkite-community.slack.com/archives/C02T53V9H/p1681412288732759), this is supported. Update the examples to include it.
In the list example, include the "not rebuilt" variant (`null`). In the get example, make the shown JSON build number 2, a rebuild from number 1.

API: document `rebuilt_from` field for get/list builds

---

pages/apis/rest_api/analytics/runs.md

Description
We are adding a `created_at` field to  test analytics runs#index and runs#show api endpoints. This PR adds the new field to our api docs.

PIE 1850 Add created_at to test analytics runs#index and runs#show api endpoints

---

pages/apis/managing_api_tokens.md

Removed in https://github.com/buildkite/buildkite/pull/13089
Note, I didn't remove it from the [schema docs](https://github.com/buildkite/docs/blob/9f43215cd7134d3c78c09dc3154e0b0b7625383b/pages/apis/graphql/schemas/enum/apiaccesstokenscopes.md?plain=1#L43). There are a lot of changes to the schema so I think updating it is outside the scope of this PR.

The read_flaky_tests scope has been removed

---

data/content/agent_attributes.yaml

This PR fixes a typo in regards to the BUILDKITE_AGENT_TAGS_FROM_HOST env var in our documentation.
As seen here: https://github.com/buildkite/agent/blob/main/clicommand/agent_start.go#L317, the original
text has the env var as BUILDKITE_AGENTS_TAGS_FROM_HOST which is incorrect.

fix tags-from-host env var typo

---

data/content/environment_variables.yaml

@HugeIRL [pointed out this typo](https://3.basecamp.com/3453178/buckets/28474015/chats/5132790929@6357316472), which makes the field display `false` even if the value is meant to be `true`.
I've raised an escalation with Pipelines to get a review.

Fix typo: modifable -> modifiable

---

data/content/environment_variables.yaml

This is a bandaid on a bigger problem. `BUILDKITE_REPO` being marked as not modifiable has caused confusion for users, but the idea of being "modifiable" needs revisiting. Context captured [here](https://3.basecamp.com/3453178/buckets/28474015/messages/6359356260#__recording_6365240200).
Note, this is the same change first raised in #2307.

Mark BUILDKITE_REPO as modifiable

---

pages/clusters/manage_clusters.md
pages/clusters/overview.md

Linear ticket: [EDGE-1055](https://linear.app/buildkite/issue/EDGE-1055/ui-hide-agentregistrationtokentoken-and-clustertokentoken)
Updates the docs to reflect the new cluster token creation flow, as per the changes in [this PR](https://github.com/buildkite/buildkite/pull/13136/files).

Clusters: Update agent connection instructions to include token creation

---

data/content/aws-stack.yml
pages/agent/v3/elastic_ci_aws.md

The version numbers that have been removed are horribly out of date. It is a
large burden to update them all, so we are removing them.
We will investigate a better way to surface this to our customers in the future,
but in the meantime, we will remove them as they are misleading.
So for now, customers will need to follow the release announcements in the repository.

Update stack template for v5.22.1 and remove details of versions of installed software

---

pages/agent/v3/elastic_ci_aws/managing_elastic_ci_stack.md
pages/agent/v3/elastic_ci_aws/troubleshooting.md

@catkins wrote an [internal post](https://3.basecamp.com/3453178/buckets/23112918/messages/6363965965) about scaling up redundant agents if you use multiple elastic stacks per queue. This change aims to use a stronger recommendation not to do that and clarify the behavior if you do.

Clarify the behavior of using multiple stacks per queue

---

pages/apis/graphql/graphql_cookbook.md
pages/apis/managing_api_tokens.md

Update the feature name
Add cookbook for how to use [revoke inactive tokens after](https://buildkite.com/releases/2023-06/api-token-expiry-policies) via GraphQL API.

Add Update the revoke inactive tokens after to GraphQL cookbook

---

pages/apis/webhooks/build_events.md

We have` build.failing` event mentioned in the in the webhooks overview [page](https://buildkite.com/docs/apis/webhooks), but not listed as a build event [here](https://buildkite.com/docs/apis/webhooks/build-events).

Added in build.failing to be consistent with the webhook events overview

---

pages/agent/v3/docker.md

- as it says on in the title, double full stop (not sure if it should go inside or outside the `a` tag though?

Remove extra full stop on agent docker page

---

pages/agent/v3/elastic_ci_aws/troubleshooting.md

The more I read about this feature, the more I think we should disable it by default. Unfortunately, that's not going to make it for v6 of the elastic ci stack, so let's put this warning here instead.

Add a section in troubleshooting.md to explain how to disable user namespacing on docker daemon.

---

pages/apis/graphql/graphql_cookbook.md

Added an initial example Clusters section in the GraphQL cookbook with some examples:
Contains the first few examples
- getClusters
- getClusterQueues
- getClusterQueueJobs
- getClusterQueueJobsByJobState

Clusters category in GraphQL Cookbook/initial examples

---

pages/apis/rest_api/analytics/suites.md

PIE-1880
To manage team permissions for suites via the Terraform provider, we
should support a graphql_id attribute on the suites REST API response.

Add graphql_id to suites REST API

---

pages/agent/v3/aws.md
pages/agent/v3/elastic_ci_aws.md
pages/agent/v3/elastic_ci_aws/cloudformation_service_role.md
pages/agent/v3/elastic_ci_aws/managing_elastic_ci_stack.md
pages/agent/v3/elastic_ci_aws/parameters.md
pages/agent/v3/elastic_ci_aws/security.md
pages/agent/v3/elastic_ci_aws/troubleshooting.md
pages/agent/v3/redhat.md

The main changes are Amazon Linux 2023 and several parameter renames. We are also renaming the `master` branch to `main`. This affects several URLs to github, but also URLs to the stack templates. The github URLs have been changed to be agnostic to what the default branch is.
See https://github.com/buildkite/elastic-ci-stack-for-aws/releases/tag/v6.0.0 for more details.
That link won't be up while this is a draft. In the meantime, use https://github.com/buildkite/elastic-ci-stack-for-aws/releases/tag/v6.0.0-beta1 and https://github.com/buildkite/elastic-ci-stack-for-aws/releases/tag/v6.0.0-beta2 instead.

Update docs for Elastic CI Stack v6

---

pages/pipelines/build_exports.md

The docs for Build Exports — Prepare your Amazon S3 bucket said:
> … you may want to consider `SSE-KMS`
However:
- we definitely don't currently explain how to configure a resource policy on the KMS key to allow our AWS account to encrypt data with it, so it will probably fail with a permission error,
- we probably don't have our application's IAM role configured to allow KMS encryption,
- when it fails due to attempted KMS use, the permission checker doesn't currently pass on that informative error message.
So, the best thing for the moment is to discourage its use in the docs.
The _internal_ error message is something like this:
>     upload failed: - to s3://…/buildkite/build-exports/org=…/deliverability-test.txt An error occurred (AccessDenied) when calling the PutObject operation: …

Build Exports: we do not currently support SSE-KMS

---

pages/test_analytics/ruby_collectors.md

We run a link checker as part of linting the docs, and this link keeps causing it to fail by returning a 429. We don't want Google penalizing us for broken outbound links. From my understanding of the paragraph, we're mainly linking there to add legitimacy to our suggestion, but our suggestion provides the solution. If that's true, I don't think we need this link.
If I'm missing something, is there another resource we could link to or some information from that page we could pull into our docs?

Remove web archive link to Ruby best practices

---

pages/agent/v3/securing.md

Currently in docs there is no example on how to use environment variable BUILDKITE_CLEAN_CHECKOUT to set force clean checkout so adding one through this example and also information on how to confirm from logs if clean checkout happened.

Add an example for force clean checkout at step level

---

pages/apis/graphql/graphql_cookbook.md

A road-tested way to query all builds that have a certain state and were created within a particular time frame.

Adds a section to GraphQL cookbook

---

pages/apis/graphql/graphql_cookbook.md

Similar to what we have for the `auditEvents` query, just with a example using `occurredAtFrom` and `occurredAtTo` filtering

Added timeboxed Auditevents example to the GraphQL Cookbook

---

pages/agent/v3/ubuntu.md

The first paragraph is introductory, the second is the first action, so saying "Next, ..." doesn't make sense to me — unless I'm missing something!

Update ubuntu first step wording

---

app/models/page.rb
app/views/application/_head.html.erb
app/views/application/_toc.html.erb

Adds meta descriptions to all pages with content pulled from YAML front matter or falling back to the first paragraph.
Closes ONB-317, ONB-326

Add page meta descriptions

---

pages/apis/rest_api/builds.md
pages/apis/rest_api/pipelines.md

**What was the problem?**
For some time now, provider webhook_url for pipelines has been exposed in our REST API and webhook payloads without all of the correct permissions checks: anyone with a READ scoped agent token was able to see it. The problem here is that only users with edit permissions for the pipeline should be able to see the provider webhook_url - but we were not performing this additional check.
**Why is this such a concern?**
With the webhook_url you can trigger builds. We don't want read-only folks doing this. Not only that, but you can also use it to trigger builds as other people, potentially circumventing permissions etc.
In summary, to GET the pipeline provider webhook_url, the user should have:
- a READ scoped agent token
- "full access" permissions to edit the …

Update docs with notes on pipeline provider webhook_url permissions

---

data/content/test_analytics_json_fields_history.yaml
data/content/test_analytics_json_fields_span.yaml

Change requested via support ticket to clarify the time unit for the JSON upload history object duration.
Also updated the duration attribute for the span section with the same information.
[PIE-1940](https://linear.app/buildkite/issue/PIE-1940/update-json-history-docs-to-clarify-the-time-unit-for-duration)
[Support ticket](https://3.basecamp.com/3453178/buckets/20365997/card_tables/cards/6449334609)
[Slack conversation](https://buildkite.slack.com/archives/C02RH06NMH6/p1692007930840309)

PIE-1940: Update description for TA json duration field

---

.buildkite/pipeline.deploy.yml

Fix an issue with pushing up the docs image to ECR by using the latest version of our buildkite-ecr-plugin.

Bump ecr-plugin to v2.7.0

---

pages/pipelines/managing_log_output.md

Adding additional patterns to the redacted-vars setting in the agent config, will require appending new patterns to the existing defaults. For example, if you wanted to redact the value of `FOO` in your log output, and keep the existing default patterns, the config setting should look like:
```shell
redacted-vars="*_PASSWORD, *_SECRET, *_TOKEN, *_ACCESS_KEY, *_SECRET_KEY, *_SOME_VALUE, FOO"
```

Update on setting redacted-vars in the agent config

---

pages/apis/graphql/graphql_cookbook.md

I had a question from a customer:
`AS the document shows PipelineScheduleUpdateInput has env: String not [String] . How can I update env with a list of variables such as env: [“bar=foo”, “var1"=“val1”, “var12"=“good”] ?`
Here's the mutation https://buildkite.com/user/graphql/console/2ad2ddd5-dd14-485c-b87d-af5751b3ec5b if you would like to check it out.
This probably applies to anything we take in as a String and separate with a new line - so there may be more opportunities.
Here is what the change looks like:
You may want to consider linking to this recipe or adding something in https://buildkite.com/docs/apis/graphql/schemas/pipelinescheduleupdateinput to let folks know.
Another thing - this is kinda hacky; a better alternative would be to have its value that accepts an Array. I am not …

Add GraphQL example of setting multiple env vars

---

data/content/test_analytics_json_fields_failure_expanded.yaml
pages/test_analytics/importing_json.md

We had some customer feedback regarding their difficulty using the failure_expanded object in their custom collector. The keys within the hash are required fields on the frontend, so I have updated the docs to detail this further. (Please feel free to recommend better words).
[PIE-1941](https://linear.app/buildkite/issue/PIE-1941)
[Support ticket](https://3.basecamp.com/3453178/buckets/20365997/card_tables/cards/6449338274)
[Slack conversation](https://buildkite.slack.com/archives/C02RH06NMH6/p1692007930840309)

PIE-1941: Update TA JSON failure_expanded

---

data/content/environment_variables.yaml

The customer is asking why the BUILDKITE_BUILD_AUTHOR is not showing in the UI as the build creator.  Though the information is in [this]( https://buildkite.com/docs/pipelines/conditionals#variable-and-syntax-reference-variables) part of our docs, customers tend to navigate into this [section](https://buildkite.com/docs/pipelines/environment-variables#BUILDKITE_BUILD_AUTHOR) for information about the environment variables.
Proposing to add the details here for the above reason and make it easier for customers to search this information.

Buildkite Build Creator details

---

config/routes.rb
data/nav.yml
pages/agent/v3/installation.md
pages/agent/v3/upgrading.md

We've had multiple pieces of feedback that the current [Upgrading page](https://buildkite.com/docs/agent/v3/upgrading) looks incomplete and bad. It also recently showed up in a report showing that it's a bad page for our SEO since it lacks content.
This change:
- Moves the information into the Installation page. I think that's the logical place for it. I also updated the style.
- Removes the Upgrading page.
- Adds a redirect to the new location.
- Displays the table of contents on the Installation page now that there are two headings to show.

Remove the agent upgrading page

---

pages/pipelines/build_exports.md

As part of this PR, we are updating the following
1. Improving visibility into IAM conditions config that customers need to set up for GCP based on user feedback
2. Add notes around how users can be sure that once build export is enabled there is connectivity validation performed by us

Update build_exports to bring visibility on IAM conditions and connectivity tests

---

pages/agent/v3/help/_annotate.md
pages/agent/v3/help/_annotation_remove.md
pages/agent/v3/help/_artifact_download.md
pages/agent/v3/help/_artifact_search.md
pages/agent/v3/help/_artifact_shasum.md
pages/agent/v3/help/_artifact_upload.md
pages/agent/v3/help/_bootstrap.md
pages/agent/v3/help/_env_dump.md
pages/agent/v3/help/_env_get.md
pages/agent/v3/help/_env_set.md
pages/agent/v3/help/_env_unset.md
pages/agent/v3/help/_lock_acquire.md
pages/agent/v3/help/_lock_do.md
pages/agent/v3/help/_lock_done.md
pages/agent/v3/help/_lock_get.md
pages/agent/v3/help/_lock_release.md
pages/agent/v3/help/_meta_data_exists.md
pages/agent/v3/help/_meta_data_get.md
pages/agent/v3/help/_meta_data_keys.md
pages/agent/v3/help/_meta_data_set.md
pages/agent/v3/help/_oidc_request_token.md
pages/agent/v3/help/_pipeline_upload.md
pages/agent/v3/help/_start.md
pages/agent/v3/help/_step_get.md
pages/agent/v3/help/_step_update.md
scripts/cli2md.rb
scripts/update-agent-help.sh

This is the script `cli2md.rb` that generates the agent cli reference docs.
Its input is the output of `buildkite-agent` commands with the flag `--help`.
We've changed some of the practices since when this script was first written. Now:
- We will encase code blocks in `shell` backtick blocks. In the input, we will use 4 spaces to indicate the start of a code block.
- We will also replace prime signs with backticks in all the input, previously it was just the descriptions of the arguments.
- We also remove the user's home directory from the docs, since it is not relevant to the docs.
- We also make the state machine explicit, instead of using 2 boolean variables to control it.
There is a companion [PR](https://github.com/buildkite/agent/pull/2317) to adjust the cli commands in the agent to …

Update agent cli reference docs generation

---

pages/agent/v3/cli_start.md

In this PR added an example to specify that when a job has targeting rules set with both tag and queue then an agent should be present which has both in order for the job to be scheduled.

Add example for queue and tag targeting rule

---

config/algolia.json

It appears our self-run Algolia crawler is over indexing a bunch of records because we're been including each item of the nav and table of contents, resulting in ~500 additional records per-page.
This PR updates out algolia config to exclude irrelevant content and fixes up the selectors to match the latest page hierarchy.
For reference:
- https://docsearch.algolia.com/docs/legacy/config-file
- https://docsearch.algolia.com/docs/legacy/how-do-we-build-an-index

Fix Algolia crawler 

---

docker-compose.yml

I keep running into issues with conflicting gems between buildkite and our docs.
This PR dockerizes vite so now everything can be run with the following:
```sh
docker-compose up -d app
```

Add dockerized version of the docs

---

config/algolia.json

I'm seeing a bunch of empty results in our search index with links to `#main`. 
~~This PR removes the link to see if that fixes the problem and we can look at bringing it back later.~~
This PR attempts to stop `#main` URLs from being indexed

Stop indexing `#main` URLs

---

pages/pipelines.md

The way the note is currently written is a bit confusing:
We could rewrite this callout while maintaining a link to the REST API, but to be as clear as we can (and assuming my interpretation is accurate), I think we should either say exit status is “only available when using the GraphQL API”, or “is not available when using the REST API”, rather than trying to word this note in such a way that it refers to _both_ APIs, while trying to indicate it’s only available in one.
A smaller rewrite could read:
```
Exit status information is available in the <a href="/docs/apis/graphql-api">GraphQL API</a>, but not the <a href="/docs/apis/rest-api">REST API</a>
```

Update exit status troubleshooting note

---

data/content/agent_attributes.yaml
pages/agent/v3.md

This appears to have been missed but is a crucial feature that we make use of and may be useful to others too.

Add documentation for `git-mirrors-skip-update`

---

pages/agent/v3/queues.md
pages/pipelines/branch_configuration.md

Purpose of this was to add **Agent Queues** as an alternative way of filtering pipelines and steps from being done – and where (agents) they are completed.
Then I added another example to the `Queues` page so it was clear the `queue` YAML attribute could be used as either root level or on a specific step.
Then I added a reference to branch filtering from the Queues page for completeness.
**QUERY:** I wasn't sure about referencing things as either 'build steps' or 'jobs'. It differs page to page. Welcome your input @mbelton-buildkite

Doc 654 add reference to queues on branch configurations

---

app/views/pages/show.html.erb
config/algolia.json

Looks like https://buildkite.com/buildkite/docs-algolia-crawler/builds/1651#018a2a08-1703-4dee-b85a-e30fe93e4422 accidentally stoped article content from being indexed.
I need to have a think how we might catch this kind of thing earlier in CI.

Fix algolia article selector

---

app/assets/stylesheets/components/_toc.scss
app/frontend/components/toc.js
app/models/page/renderer.rb
app/views/application/_toc.html.erb

OK I went a little further with https://github.com/buildkite/docs/pull/2396 and rather than just smooth scrolling (which I'm not tied to), I've also adapted the awesome work of https://lab.hakim.se/progress-nav into our table of contents.
I'll admit that I haven't produced the nicest code, but the end result is kinda cool. 
Here's a couple variations for us to discuss.
**V1 (the one in this PR)**
https://github.com/buildkite/docs/assets/656826/68b2b197-6f01-4fa2-9a27-3ab6d797ca23
**V2 (the 🐍 version)**
https://github.com/buildkite/docs/assets/656826/bef06831-34d4-4aa2-a646-f4e8715625e9

Table of contents (V2)

---

app/frontend/components/toc.js

This fixes an error that pops on pages that don't include a table of contents.

Skip initialising table of contents for some pages

---

app/assets/stylesheets/components/docsearch/_variables.scss
app/assets/stylesheets/components/docsearch/button.scss
app/assets/stylesheets/components/docsearch/modal.scss

Okay okay last one. Quick pass over the appearance of the Docsearch 3 input:
A subtler treatment for the ⌘K key affordance:
Some visual tweaks to background colour and border radius of modal, bring input shadow to main search field
And add nice focus treatment too:

Visual tweaks to new docs search

---

app/assets/stylesheets/base/_global.scss
app/assets/stylesheets/base/_mixins.scss
app/assets/stylesheets/pages/_docs.scss
data/content/environment_variables.yaml
pages/pipelines/environment_variables.md

This fixes some formatting issues with env variables example caused by markdown rendered in `code` tags.
https://2436--bk-docs-preview.netlify.app/docs/pipelines/environment-variables
Closes DOC-633
Before:

Strip markdown from environment variable examples

---

app/models/page/renderer.rb
spec/models/page/renderer_spec.rb

Sometimes I'm seeing search results with some blank `#main` links. 
I noted that we didn't include IDs on our h1's which I think means the default h1 indexing doesn't have anything to link to. 
Maybe this will improve things 🤷

Add ids to h1 tags for search

---

app/models/page/renderer.rb
app/views/layouts/application.html.erb
pages/agent/v3/gcloud.md
spec/models/page/renderer_spec.rb

This is another crack at removing some empty anchor links from showing up the search results. It doesn't look like https://github.com/buildkite/docs/pull/2438 helped so I'm looking at using a `__` prefixed id similar to what docusaurus does. I'm guessing the algolia search excludes these 😬 
I need a better way of testing this stuff in dev. 
This is what I'm trying to fix. You can see it uses the new ID but it's still displaying weird.

Attempt to fix blank search records

---

pages/pipelines/build_retention.md

We got a few customers that asked us about the per pipeline retention settings. So adding it to the docs so it is more clear
https://linear.app/buildkite/issue/PDP-1497/update-docs-to-talk-about-per-pipeline-settings-removed

Update docs to talk about per pipeline settings removed

---

pages/agent/v3/_alternative_keyservers.md
pages/agent/v3/debian.md
pages/agent/v3/ubuntu.md
vale/styles/vocab.txt

At the moment, the keyserver we use in the instructions to install the agent on Ubuntu and Debian seems to be down. However, it is not the only keyserver that our PGP public key has been distributed to, so let's add an alternative keyserver to the instructions.

Add alternative keyservers for Ubuntu and Debian

---

pages/apis/rest_api/pipelines.md

When setting `trigger_mode` in the REST API - the lowercase values of `fork`, `deployment`, `code` and `none` are valid inputs in the `provider_settings` [block](https://buildkite.com/docs/apis/rest-api/pipelines#provider-settings-properties) for GitHub/GHE. The capital-letter versions might cause some confusion around its setting - as `trigger_mode` can be set with `Code` for example, which isn't valid input for setting this attribute accordingly!

Trigger mode property clarification (lowercase)

---

pages/pipelines/managing_log_output.md

If customers want to use their own bucket for logs, we only support SSE-S3 encryption

clarify supported bucket encryption

---

app/assets/stylesheets/components/_footer.scss
app/assets/stylesheets/components/_page.scss

Max width is applied so in certain contexts, the footer paragraph text looks misaligned:
**Before:**
**After:**

Fix center alignment of footer paragraph

---

app/helpers/application_helper.rb
app/views/application/_head.html.erb
spec/helpers/application_helper_spec.rb

Specify canonical URL on every page as `https://buildkite.com/docs/*/**` (without www).

🔍 Canonical URL

---

CODEOWNERS

This adds @MelissaKaulfuss and @meiqimichelle as default reviewers for the content while I'm off. @dannymidnight, is this the right syntax? [I think it is](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners#codeowners-syntax).

Add Mel and Michelle as codeowners

---

pages/pipelines/dashboard_walkthrough.md

The browser policy was recently shared with me, so I looked for a place to include it in our documentation. Ideally, it would go in a platform section relevant to all products, but we don't have that section in the docs yet. Instead, I believe it fits best on the Dashboard walkthrough page where we discuss the product UI.
[Preview](https://2457--bk-docs-preview.netlify.app/docs/pipelines/dashboard-walkthrough#supported-browsers)

Document supported browsers

---

.buildkite/push-image.sh
Dockerfile

This fixes the production env from `unknown` to `production`.

Fix RUM tagging for production image

---

app/frontend/components/toc.js

This PR fixes a JS console error that pops on when a user navigates to another page. It's caused by the table of contents element no longer existing in the DOM.

Fix table of contents selector error

---

README.md
app/controllers/pages_controller.rb
app/models/page.rb
app/views/application/_meta_content.html.erb
app/views/layouts/application.html.erb
app/views/layouts/homepage.html.erb
app/views/pages/landing_page.html.erb
app/views/pages/landing_page_pipelines.html.erb
app/views/pages/show.html.erb
pages/deployments.md
pages/pipelines.md
pages/tutorials/2fa.md
pages/tutorials/bazel.md
pages/tutorials/docker_containerized_builds.md
pages/tutorials/getting_started.md
pages/tutorials/github_merge_queue.md
pages/tutorials/migrating_from_bamboo.md
pages/tutorials/parallel_builds.md
pages/tutorials/pipeline_upgrade.md
spec/models/page_spec.rb

Define page focus keywords with the `keywords` front matter meta data.
Render keywords in `data-content-keywords` in the `body` tag to highlight the focus keywords of each page for content authors. This helps the content team to quickly inspect to see the types of content we're providing across different channels.
Use graceful fallback when no keywords have been provided — comma separated URL path segments.

✨ Specify content keyword in front matter

---

.buildkite/pipeline.yml

As of https://github.com/buildkite/docs/pull/2452, all pages now include a canonical link tag with https://buildkite.com. 
An interesting side-effect of that change is that now `muffet` (the link checker we use in CI) [fails builds](https://buildkite.com/buildkite/docs/builds/6596#018a8692-c2dd-42e1-bf9a-b3f7007b2fc0) that add new routes since muffet is unable to find a valid buildkite.com/docs route – since they've yet to be shipped. 
I believe this would classify as a classic 🐔 & 🥚 problem.
This PR excludes `buildkite.com/docs` URLs from the link checker so we get green builds.
/cc @olyism

Exclude `buildkite.com/docs` from being crawled

---

.buildkite/update_graphql_docs

I'm seeing the automated GraphQL builds [fail](https://buildkite.com/buildkite/docs-graphql/builds/272#018a9107-0bd8-4394-b718-28bfcf9752fa) on subsequent runs when the latest schema changes are yet to be merged.
This PR checks to see if an existing PR is open before progressing.

Skip pushing GraphQL changes when an existing pull request is open

---

Gemfile.lock

v1 has been deprecated
From https://github.com/buildkite/test-collector-ruby/
> DEPRECATION NOTICE Versions prior to 2.1.x are unsupported and will not work after mid-2023. Please upgrade to the latest version.

Update buildkite-test_collector from 1.5.0 to 2.3.1

---

pages/apis/graphql/cookbooks/jobs.md

Turned out, no one I asked knew how to do that from the top of their heads, so let's have it in the cookbook now that we know how to do it.

Adds a query to find UUIDs of jobs in a build

---

data/nav.yml
pages/apis/graphql/cookbooks/organizations.md
pages/team_management.md
pages/team_management/enforce_2fa.md
pages/tutorials/2fa.md

Enforce 2FA is a feature for all organizations who want to ensure that all users of their organization have 2FA enabled before they can access their organiztion.
Enforce 2FA is part of the Q3 release. 
- :basecamp: [Internal Project Docs](https://3.basecamp.com/3453178/buckets/23328660/messages/6543585015)

Enforce 2FA documentation

---

data/nav.yml
pages/apis/graphql/cookbooks/organizations.md
pages/team_management.md
pages/team_management/system_banners.md

System banners is an enterprise only feature for organizations to communicate with their staff via announcement banners.
System banners is part of the Q3 release.
:basecamp: [Internal Project Docs](https://3.basecamp.com/3453178/buckets/23328660/messages/6528240759)

System Banners Documentation

---

pages/apis/graphql/cookbooks/clusters.md

Added and adjusted the Cluster's GraphQL cookbook page:
- Adjusted the headings - the example queries just don't return the IDs! 😄 
- Added a cluster token example to complete cluster/queue/token examples (with token deprecation warning)
- Wording adjustments / arguments & filters

Clusters GraphQL cookbook touchup, token query addition/token value deprecation note

---

data/content/test_analytics_json_fields_history.yaml
data/content/test_analytics_json_fields_span.yaml

We mentioned that the value of duration is microseconds, but according to the code the value that is expected is in seconds (it converts to milliseconds and microseconds to show in the UI). I confirmed with @KatieWright26 :)

Update duration in history/span

---

pages/team_management/permissions.md

**Context**
Foundation has recently enforced the following service quota for team creation.
**Internal Docs**
- :basecamp: [Basecamp Project](https://3.basecamp.com/3453178/buckets/23328660/messages/6528239879)
- :basecamp: [Related escalation](https://3.basecamp.com/3453178/buckets/23328660/card_tables/cards/6215206158)

Add FAQ: max teams per org limit?

---

pages/test_analytics/test_suites.md

Now that the run issues has moved out of private beta, we need to update the docs to say 'Beta' instead

Changing TA run issues private beta notice to beta

---

pages/pipelines/templates.md

We have added ability to mark templates as available and also to not require them anymore. This updates to documentation to explain that.
It also talks about the CRUD APIs in REST and Graphql

Update pipeline template docs for Q3 release

---

README.md
styleguide/STYLE.md

Based on https://github.com/buildkite/docs/pull/2479, I noted we're missing up-to-date documentation on the process for generating GraphQL API docs.
Hopefully this is a little easier to follow @jonathanly.

Update README for generating GraphQL docs

---

pages/pipelines/waterfall.md

Adds in a line about how we treat canceled, expired, timed out, skipped jobs. 
Relates to https://github.com/buildkite/buildkite/pull/14047

Waterfall: Add info about non-terminal finished jobs states

---

Dockerfile

[Debian 12 was released in June 2023](https://wiki.debian.org/DebianBookworm) and has a range of package updates. The vast majority will not be significant in the context of the docs app and should have no impact on the app behaviour.
Updating is useful though, mainly just so we don't fall behind. It will also avoid some CVEs being detected by scanning software.
The critical CVE doesn't impact us, but here's the details: [CVE-2023-38408](https://security-tracker.debian.org/tracker/CVE-2023-38408).
The CVE is also fixed in bullseye so this upgrade isn't technically required, we could also install security packages . I reckon the OS bump is worth or for other reasons though. 
/cc @buildkite/platform

Upgrade from debian 11 (bullseye) to debian 12 (bookworm)

---

Dockerfile

In #2517 I upgrade docs frm debian 11 to 12, but I was surprised to see that CVE-2023-38408 is sitll being detected post-upgrade.
I think it's because the patched openssh is available in the debian security repositories. If so, adding this upgrade should fetch them.
/cc @buildkite/platform

Fetch security upgrades from apt [PLT-1607]

---

.buildkite/pipeline.deploy.yml

This will introduce a soft-fail step that will add ECR scan results to build annotation.

Add ecr scan step

---

Dockerfile

The slim image comes with far fewer packages pre-installed and we need to manually installed a handful that we need (like curl and build-essential), but in return we get:
* A slightly smaller final image
* Fewer debian packages installed, which means fewer (low value, noisy) CVEs will be detected
The resulting image size difference looks like this:
```
docs                      slim-bookworm                           b7b6f5d9d33a   3 days ago      1.35GB
docs                      bookwork                                8a6a4a888efe   3 days ago      1.84GB
```
I think we could probably get it a lot smaller via multistage build, by ensuring tools like nodejs, gh, svn, mercurial, make, gcc, and cpp are used to build assets and native extensions, but not included in the final image. Still, …

Switch to a slim debian Docker image [PLT-1610]

---

pages/test_analytics.md
pages/test_analytics/javascript_collectors.md

We have added Playwright support to our [JavaScript test collector](https://github.com/buildkite/test-collector-javascript). This PR adds an instruction to configure test collector with Playwright in JavaScript collectors page.
https://linear.app/buildkite/issue/PIE-2029
https://github.com/buildkite/test-collector-javascript/pull/72
We need to release this after we release [buildkite-test-collector v1.6.0](https://github.com/buildkite/test-collector-javascript/pull/76)

Add Playwright section to Javascript Collectors page

---

.buildkite/pipeline.deploy.yml

These CVEs have been assessed individually and all deemed safe to ignore. Best to view each commit for the justification behind each.

Ignore many CVEs

---

pages/pipelines/artifacts.md

A customer raised #2512 to describe some frustrating debugging work required on their part to discover they needed to use  `--include-retried-jobs` to get artifacts from a retried job. This change adds a note to the troubleshooting section on the Artifacts page to help people discover that.
@pda, I saw you mentioned on a thread related to that issue so hoped you might verify this information is correct. Let me know if there's someone else I should get as a reviewer. 😊

Add help for when artifacts are missing from retried jobs

---

.buildkite/pipeline.deploy.yml

Now that all CVEs have been triaged and we have 0 reported in the pipeline - we are ready to switch off Vanta checks. Before we do that - we need to make ECR scan results check hard-fail.
The plugin has support for providing inline help text to triage vulnerabilities. In the meantime - have a look at this PR for how we propose to triage CVEs: https://github.com/buildkite/guide/pull/285
New High and Critical CVEs will start failing builds.
No risk, pipeline change only.
Revert this PR (make the step soft-fail).

Hard fail ECR check

---

.buildkite/pipeline.yml

This fixes failing builds on main. 
We can bump the version once this following issue has been resolved:
https://github.com/loeffel-io/ls-lint/issues/163

Pin ls-lint to working version

---

pages/test_analytics/ruby_collectors.md
vale/styles/vocab.txt

Adding a small note to the ruby collectors to require potential conflicting gems before the TA test collector gem
Investigation and write up in [Basecamp](https://3.basecamp.com/3453178/buckets/20365997/messages/5825135697#__recording_5840767340) 
[Resolved Github issue](https://github.com/buildkite/test-collector-ruby/issues/169#issuecomment-1430799917)

add docs on potential conflicting gems with the collector

---

.buildkite/pipeline.deploy.yml

This change ignores the following CVE whilst awaiting a bookworm patch: 
https://security-tracker.debian.org/tracker/CVE-2023-45853
There's no usage of minizip/zlib which makes this vulnerability unlikely to be exploitable.

Ignore zlib CVE

---

.buildkite/pipeline.deploy.yml

Pretty sure this one is safe to ignore. It affects the Linux Profiler `perf` tool which we don't use.

Ignore CVE-2023-5717

---

data/nav.yml
pages/apis/rest_api/limits.md

Add a page detailing our REST API rate limits. 
This PR adds:
- A sidenav item under REST API as it's quite an important document for REST API users
- Details on rate limits, how it works and best practices

Add a page on REST API rate limits

---

pages/apis/rest_api/clusters.md

The `id` (UUID) of a Cluster is needed in the request URL for a PUT to update it using the REST API - missing in the current docs release.
Was noticed by a few folks - and have added it in 👍

Added `id` to cluster Update / PUT endpoint

---

pages/pipelines/artifacts.md

Fix `artifacts_path` typo to `artifact_paths`

Fix typo in artifacts.md

---

pages/apis/webhooks.md

Only 20 webhook request and responses can be viewed in the UI. Updating the docs to match reality.

Update webhooks log count

---

pages/test_analytics/golang_collectors.md

Very minor change to update the `go testsum` command to `gotestsum` (no space). Without it Go will complain about the `testsum` command not being found.
This is correct in the example underneath, so this is just a consistency change. Caught me off-guard, might catch others too.

Fix typo when replacing go test with gotestsum

---

pages/agent/v3/elastic_ci_aws.md

A common practice I've seen is having a specific Windows Elastic Stack agent and targeting it with a queue. This PR brings a main, simple example to the overview page as a quick reference guide on how to target a queue. I have also updated the for more information blurb to include a direct link to targeting a queue.

add example of targeting a Windows agent elastic stack

---

pages/agent/v3/elastic_ci_aws/troubleshooting.md

This commit will add a section to the Elastic Stack troubleshooting docs under **Using Cloudwatch Logs** in it's own section outlining how and where to use the log-collector script to send troubleshooting logs to the Support Team at Buildkite.

Add log-collector script section to Elastic Stack docs

---

pages/plugins/directory.md

We changed how often we update the page, it is now each Sunday (UTC) instead of every hour.

Fixed GitHub sync description for plugins page

---

pages/agent/v3/elastic_ci_stack_for_ec2_mac/troubleshooting.md

The Aqua session type section was broken, so I added a correct header and fixed up the formatting, as well as made it more obvious.

Fixed Aqua session type section for macOS

---

pages/agent/v3/cli_annotate.md

This CL adds info about how many term block we allow per annotation.

Update cli annotation with term block limit

---

Dockerfile

An attempt to silence some irrelevant CVEs by removing the `linux-libc-dev` package.

Remove `linux-libc-dev` from runtime layer

---

.buildkite/pipeline.preview.yml
.buildkite/pipeline.yml
Dockerfile
docker-compose.production.yml

~~This PR consolidates some of the preview builder tools into a separate stage that can be targeted directly in CI. This means  we don't need to install misc tools like `curl` and jq` in the final layer.~~
Edit: The docker-compose plugin can only target stages whilst building, not when running.
This PR removes `docker-compose.production.yml` to keep things simple and replaces the production assets step with a production image build step to avoid compiling twice.

A little more docker housekeeping

---

pages/pipelines/managing_log_output.md

For private build archive storage, build logs are stored following a folder structure and file format that is not customisable:
`{ORGANIZATION_UUID}/{BUILDKITE_PIPELINE_ID}/{BUILDKITE_BUILD_ID}/{BUILDKITE_JOB_ID}.log`
It was highlighted by a customer that the `{ORGANIZATION_UUID}` part of that format was not reflected in the current documentation. 
This PR makes a small update to the docs so it accurately reflects the current behaviour.
[Escalation](https://coda.io/d/Escalations-Feedback_dHnUHNps1YO/Dispatch-Escalations_suxld?utm_source=slack&utm_content=comment_notification#Dispatch-Escalations-Board_tu-xJ/r141)
Updated the file format representation to include `ORGANIZATION_UUID`, as that reflects the current behaviour
**Before:**
**After:**

Small update/ammendment to managing_log_output docs 

---

.buildkite/pipeline.deploy.yml

Temporarily ignore CVE-2023-5678 whilst awaiting a patch.
See https://github.com/buildkite/buildkite/pull/14643

Ignore CVE-2023-5678

---

app/frontend/css/components/_responsive_table.scss

This PR fixes an issue occurring where we were removing padding on adjacent `th` and `td` elements when there was a faux  table header in place.
**Desktop:** Before / after
When reviewing the tablet/mobile designs, I noticed that the padding between elements was not well resolved; leading to large amounts of negative space and making it a bit difficult to infer the proximity and relationship between elements. These updates lead to a more comfortable reading experience, with greater information density.
**Tablet** Before / after
**Mobile** Before / after

Improve padding on responsive tables with faux table headings

---

.buildkite/pipeline.graphql.yml
.buildkite/update_graphql_docs
README.md
bin/utils.sh
lib/tasks/graphql.rake
scripts/generate-graphql-api-content.sh
scripts/generate_graphql_api_content.rb

Recent changes to the docker image and the upgrade to ruby 3.2 broke the pipeline for keeping the GraphQL schema up-to-date.
This PR should get it working once again.

Fix GraphQL pipeline

---

app/views/application/_head.html.erb

✨ I am not precious about my ruby so please correct if there's a better way to do this ✨ 
- we have an issue currently where we are accidentally serving docs under badge.buildkite.com
- this actually isn't too much of an issue except that google found it, crawled it and indexed it
- there was an initial fix (https://github.com/buildkite/ops/pull/1777) to just remove badge.buildkite.com/docs, but that meant that google had indexed what was now a bunch of 404s, which is also kind of a bad look.
- that fix was reverted, and there was a change to add a canonical ref: https://github.com/buildkite/docs/pull/2452 - which is great, but our SEO consultant has recommended that we also add an explicit `noindex` to the badge.buildkite.com/docs, so google will stop indexing them at all.
- once google …

Add noindex to pages under badge.buildkite.com

---

.buildkite/pipeline.preview.yml
bin/prepare-preview

It was nice while it lasted. Turns out the https://github.com/ailohq/github-deployment-buildkite-plugin repository has been removed and no longer exists in the buildkite plugins index.
I've sent the organization an email to see if they might bring it back and in the meantime we'll go without. 
Maybe I'll get around to reimplementing the behaviour some other time!

Remove usage of ailohq/github-deployment plugin

---

pages/pipelines/audit_log.md

Customers are not aware of using [Amazon EventBridge](https://buildkite.com/docs/integrations/amazon-eventbridge) as an option to stream Audit Log events, so mention it in the docs. They often reach out to us asking for a dedicated service or polling our GraphQL API.
<kbd>[Preview updated doc](https://2568--bk-docs-preview.netlify.app/docs/pipelines/audit-log)</kbd>

Mention Amazon EventBridge as option to stream audit log events

---

data/nav.yml
pages/agent/v3/securing.md
pages/agent/v3/signed_pipelines.md
pages/apis/rest_api/builds.md
vale/styles/Buildkite/h1-h6_sentence_case.yml
vale/styles/vocab.txt

We're getting closish to releasing signed pipelines on the agent - it's a fairly complicated feature and needs comprehensive docs to be useful.
These docs explain what the feature is, its use cases, and how to set it up on your agents.
Issue: [PDP-1288](https://linear.app/buildkite/issue/PDP-1288/update-bk-documentation)

Signed pipelines guide docs

---

pages/agent/v3/signed_pipelines.md

There's a bug where `ul`s in markdown in the docs renderer need a newline before the beginning of the list, or they'll look broken:
This PR fixes that issue with the signed pipelines page:

Fix list formatting in Signed Pipeline docs

---

pages/apis/rest_api/analytics/_runs_list_query_strings.md
pages/apis/rest_api/analytics/runs.md

We have added support for filtering Test Analytics runs by Buildkite build_id to the REST API.
I have copied the existing documentation formatting from the builds page including the link back to shared documentation on the use of query parameters.
[PIE-2128](https://linear.app/buildkite/issue/PIE-2128/filter-runs-by-build-id-in-ta-rest-api)
[Support Escalation](https://3.basecamp.com/3453178/buckets/20365997/card_tables/cards/6765942503)

Document filter runs by build_id

---

.buildkite/pipeline.yml

We noticed that some env variables are missing from Rspec runs in [Docs TA suite](https://buildkite.com/organizations/buildkite/analytics/suites/docs-1?branch=main). 
This PR passes Buildkite environment variables from CI env to Docker container that runs Rspec, so the Test Collector can send them to Test Analytics. ~~I exclude `BUILDKITE_BUILD_URL` to prevent linking to the private pipelines.~~
To verify, we can check if the Rspec run has all information in [Docs TA suite](https://buildkite.com/organizations/buildkite/analytics/suites/docs-1?branch=main)

Pass Buildkite Env Variables to Rspec steps

---

pages/test_analytics/your_own_collectors.md

The "your own collectors" page references and links to collectors that are "coming soon". There is no such coming soon list, or active plans to add support for new frameworks and therefore incorrect.
This PR removes the line that mentions any 'coming soon' collectors and instead only mentions how to build your own collector

Removing reference to coming soon test collectors

---

pages/apis/agent_api.md

Explicitly state that the non-metrics endpoints in the agent API are not public endpoints, and that we don't guarantee stability. This is implicit in `The only publicly available endpoint is /metrics.`, but this makes it clearer.

[CORE-6] Specify that agent API is internal

---

pages/integrations/sso/okta.md

The session is called Credentials Details with `s`.

Fix a typo in SSO with okta doc

---

data/content/aws-stack.yml

Autogenerated by `scripts/update-elastic-ci-stack-for-aws-parameters.sh`.
Looks like we haven't done this for the last few versions. But better late than never.

Update elastic stack docs for v6.13.0 release

---

pages/test_analytics/importing_junit_xml.md

The [Importing JUnit XML](https://buildkite.com/docs/test-analytics/importing-junit-xml) page in TA linked to https://llg.cubic.org/docs/junit/. That link stopped working and caused the docs builds to fail. For example, [on this build.](https://buildkite.com/buildkite/docs/builds/7105#018d531a-5fb3-4d77-9462-f317ac26bbb8/717-756)
This change replaces the broken link with a resource recommended by @gchan in [this escalation](https://3.basecamp.com/3453178/buckets/20365997/card_tables/cards/7000544649#__recording_7000628143).

Remove broken link from Linux Lighting Group

---

pages/pipelines/notifications.md

Fixes an error that slipped through untested (the current example kinda works - the notifications DO arrive to all the channels that are mentioned, but only one custom message gets delivered).

Fix an error in an example for Slack notification config

---

pages/pipelines/build_matrix.md

Matrix has a max job creation limit of 50, and we haven't yet added that to the matrix limits section. I've now added it.

add: matrix job creation limit

---

pages/agent/v3/help/_annotate.md

A user asked if Buildkite custom emojis can be used in annotations; they can.
This just makes that a little clearer as there isn't any other mention of using custom emojis in the docs that I can find.

Inform of custom emoji support

---

pages/apis/rest_api/annotations.md
pages/apis/rest_api/builds.md
pages/apis/rest_api/pipelines.md

Document a new `POST /v2/organizations/{org.slug}/pipelines/{pipeline.slug}/builds/{build.number}/annotations` endpoint for creating build annotations.
While here:
- Update the REST API jobs output to include recently added attributes: `parallel_group_index`, `parallel_group_total`, `matrix`, `cluster_id`, `cluster_url`, `cluster_queue_id`, `cluster_queue_url`
- Fix an odd-one-out casing issue for our `201 Created` status cods

Add REST API docs for creating annotations

---

pages/pipelines/cluster_queue_metrics.md

Currently the docus don't inform that there is potential variation in the numbers shown in the agent panel and those on the graph below.
I've added an (i) box to inform the user of this.

Add information on agent panel metrics

---

.markdownlint.yaml
styleguides/markdown-syntax-style.md

Other than not being able to spell the word 'suppress' in branch names correctly, I'd like to make this suggested change to the Markdown linting rules around list indentation.
First, when building the docs site locally, these linting rule checks don't appear to run. I presume this is by design, to improve the performance of the local docs build environment.
When changes are pushed up to GitHub, Buidlkite runs a Markdown linter that checks to ensure that unordered list items (bullet points) are strictly indented by only 2 spaces. This prevents us from leveraging the full benefits of Markdown's HTML rendering in the docs.
For example, forcing 2 spaces, I'm unable to bring the code blocks in line with my 2nd level bullet point:
By indenting bullet points by 4 spaces, I'm able to get a 3rd …

Temporarily suppress bullet point indentation checking.

---

pages/test_analytics.md
pages/test_analytics/javascript_collectors.md

We have added Cypress support to JavaScript collectors. This PR adds how to configure Cypress with Test Analytics.

Add Cypress to Test Analytics Javascript collectors

---

data/content/environment_variables.yaml

We [added](https://github.com/buildkite/buildkite/pull/15636#event-11844849188) `BUILDKITE_CLUSTER_ID` env var, we need to document it

Add BUILDKITE_CLUSTER_ID

---

pages/apis/graphql/cookbooks/pipelines.md

"Update pipeline schedule with multiple environment variables" section had a Heading level 3, instead of level 2 resulting in appearing as a sub-section of the previous Heading level 2 "Delete a pipeline"

Correct Header level as section was appearing as sub-section

---

pages/agent/v3/unclustered_tokens.md
pages/clusters/overview.md

The current [Clusters overview](https://buildkite.com/docs/clusters/overview#accessing-clusters-and-agents) page (near the top of **Accessing clusters and agents** section) in the Buildkite Docs site has content which appears to have documented a snapshot of clusters behaviour before clusters went GA.
The first sentence in this section now looks completely wrong! This is the sentence:
> If you only have one Cluster with one Queue selecting Agents in the global navigation will take you to your single queue.
If, however, this is still true, please do let me know
Hence, this PR fixes this Clusters overview page to remove this 'in dev' content, along with some other improvements.

Fixes to clusters overview page.

---

pages/pipelines/command_step.md
pages/pipelines/job_minutes.md
vale/styles/Buildkite/h1-h6_sentence_case.yml

We don't have any " Developer plan" and it is confuse our customer.

Change the plan's name to the existing one

---

.buildkite/pipeline.deploy.yml

Ignore https://security-tracker.debian.org/tracker/CVE-2023-50387 whilst waiting for a fix.

Ignore CVE-2023-50387

---

pages/pipelines/_job_states.md

A possible job state is `expired` which is shown in our job state diagram on the same page, however the list did not include this state. This updates the list to include the `expired` state.

Update list of job states to include expired

---

pages/agent/v3/cli_oidc.md

This just removes the space in the example for the sub oidc claim so it reflects/matches the full example token at the base of the page.

docs: fix example in cli_oidc.md

---

pages/agent/v3/signed_pipelines.md

Signed pipelines are not compatible with pipeline templates, so we should call that out in docs to make it clear.

Call out that signed pipelines are not compatible with pipeline templates

---

.buildkite/pipeline.deploy.yml

Historically, we have used the `deploy` queue to manage resources in the production account. These agents run inside the account, and have fairly broad permissions that are used by several pipelines.
Instead of relying on the agents to have the permissions we need, we can use an OIDC assumable role with custom permissions. The benefits being:
- The role can be tightly scoped to the permissions needed to deploy `docs`
- The role is only assumable by the `main` branch of `docs-main` pipeline
- We can run the deploy steps on lower privilege agents
This pattern was recently used in the [site repo](https://github.com/buildkite/site/pull/2898).
The [role](https://github.com/buildkite/ops/pull/2137) has permissions to interact with ECR and ECS. However, we may need to tweak the permissions to …

Move deploy to elastic-runners queue with OIDC role for cross account access

---

data/content/agent_attributes.yaml

There's a typo in the no-git-submodules section of the docs where it displays the value as:
BUILDKIT_DISABLE_GIT_SUBMODULES
When it should be:
BUILDKIT**E**_DISABLE_GIT_SUBMODULES

fix: BUILDKIT -> BUILDKITE

---

pages/apis/graphql/cookbooks/pipeline_templates.md

There is no `pipelineTemplateId` field in `pipeline` but a `pipelineTemplate` field with an `id`.
The mutation without a correct format will fail with `"Field 'pipelineTemplateId' doesn't exist on type 'Pipeline'"`

docs: fix wrong pipeline template mutation example in cookbook

---

pages/pipelines/skipping.md

`[skip ci]` is a bit of a blunt instrument and recently we've seen > 1 case of confusion caused where builds haven't triggered due to its use.
I'd like to therefore add an informative message to the page which may aid in reducing the confusion.

Add context around [skip ci] use and builds not triggering

---

pages/apis/rest_api.md
styleguides/writing-style.md

Just thought I'd take this opportunity to fix the wording in this section a little while it was still fresh on my mind.
Also added some minor clarifications to our writing guidelines on list items.

Minor wording tweaks to REST API authentication section.

---

pages/test_analytics/importing_json.md
pages/test_analytics/importing_junit_xml.md

The docs say a plugin would be available for Github Actions and CircleCI but we don't have any plans to create one yet. 
We should remove this paragraph from these views to avoid customer expectation of a plugin being created soon.
- `/docs/test-analytics/importing-junit-xml`
- `/docs/test-analytics/importing-json`

Removing reference to Github and CircleCI plugin in TA

---

pages/agent/v3/unclustered_tokens.md

This PR bolds the text for: 
> It is not be possible to create and work with unclustered agents for any new Buildkite organizations created after the official release of clusters on February 26, 2024.
I feel this is an important piece of information that may get skipped as it is part of the paragraph that describes the deprecation.

add: visibility to deprecation of unclustered agents message

---

config/routes.rb
data/nav.yml
data/tiles.yml

We now have a golden path for setting up Java repos, so we should update the docs to allow customers to easily find the documentation on setup. 
At the moment a customers have to go to References -> Importing JUnit XML. It would be easier for them just to see Java in the languages and then link to this page.

Adding Java to TA language nav

---

pages/integrations/slack.md

Through this PR we are adding a note in slack integration page about quota limit for slack notification services

Add a note about quota limit for slack notification services

---

pages/apis/webhooks/build_events.md

A minor but important change. The "_sender_" in the **request body data** section does not return a String, it returns an Object that contains two strings, as the example shows below it.
This commit corrects the distinction and provides clarity, all in one small change!

fix: update sender from string to object

---

pages/apis/graphql/cookbooks/jobs.md

Adding this example as it is not possible to get the information in the Job that is a result of another being retried and a customer reached out wanting to get this information to perform different decisions in a job based on how it was retried - Manually or Automatically.

Add example GraphQL query to get retry information for a Job

---

pages/apis/graphql/cookbooks/clusters.md

As Clusters have entered General Availability, we do not have an example of how to use the GraphQL to associate Pipelines with Cluster which can be used to programmatically update multiple Pipelines

docs: Add GraphQL example of associating Pipeline with a Cluster

---

pages/packages/getting_started.md

These claims were true for Packagecloud, but not Buildkite Packages. Buildkite Packages repositories can only contain one package type each. We do allow any distribution to use repositories, but we don't have "sub-repositories" for each ubuntu/debian distribution etc the way Packagecloud does. And authentication tokens are still evolving in product. So it might be easiest to remove these claims for now.
/cc @gilesgas

Remove bits that aren't quite true

---

pages/packages.md

This PR addresses the following points (near the top of the main overview docs page for Buildkite Packages):
- Indicates up front that Buildkite Packages can be used with other CI/CD applications.
- Provides a link to the Buildkite Packages product page (https://buildkite.com/packages) indicating that people can sign up for the private beta there.

Update introduction to Buildkite Packages overview page

---

pages/apis/rest_api/pipelines.md

...To include pipeline template assignment support
Customer has flagged with us that our pipelines rest api documentation does not reference pipeline template assignment.
[Support coda ticket](https://coda.io/d/Escalations-Feedback_dHnUHNps1YO/Escalations_sudOj#escalations-board_tu9Bj/r300&view=modal)

[PS-60] Update pipelines REST API documentation

---

config/algolia.json

Something isn't quite right with our Algolia doc scraper configuration. We've got lots of blank links and grouping isn't really happening.
After reading the [docs](https://docsearch.algolia.com/docs/legacy/config-file/) some more and reviewing some other configurations, it occurred to me that our doc search is missing the top level grouping (ie. Packages, Test Analytics, Pipelines etc.) which I think is causing the issue since that content should live in the `header` of the page.
This PR switches up the selectors to match `lvl0` to the active nav item and removes `h6` headers which aren't being used.
Before merging, I'll manually trigger a crawl from this branch to confirm it all works as expected.

Fix Algolia results 

---

pages/apis/rest_api/analytics/suites.md
vale/styles/vocab.txt

We had a support request raised by a customer who noticed that terraform provider(TFP) did not have UI feature parity with `:suites`. New fields were added as a part of the suite#index uplift. TFP uses the TA suite API to update and create suites, and consequently the API has had to be updated to accept these new optional fields.
I've updated the docs for suite API to ensure Feature parity / accessibility to all customers
[PIE-2406](https://linear.app/buildkite/issue/PIE-2406/auditupdate-terraform-provider-to-ensure-parity-with-suite-index)
[Escalation](https://3.basecamp.com/3453178/buckets/1713315/card_tables/cards/7225937705#__recording_7230084616)
[BK PR to add fields to API](https://github.com/buildkite/buildkite/pull/16114)

[PIE-2406] Add new suite fields to suite apis

---

pages/apis/api_differences.md

We recently released [REST endpoints for Teams API](https://buildkite.com/changelog/226-introducing-teams-rest-api). 
This PR updates the docs so that we reflect the difference in 'API difference' section.

Update stale info about API differences regarding teams endpoints

---

pages/agent/v3/elastic_ci_stack_for_ec2_mac/autoscaling_mac_metal.md
pages/agent/v3/elastic_ci_stack_for_ec2_mac/troubleshooting.md

The current version of macOS has moved some settings around, and AWS have renamed theirs.

Update EC2 Mac instructions for macOS Sonoma

---

pages/pipelines/wait_step.md

We received a customer feedback where jobs following a wait step were ran without waiting for previous steps to continue as opposed to what we say in the docs on wait steps. After investigation, it was the caused by the use of `depends_on` attribute with a missing dependency. Details at this HS ticket [56014]( https://secure.helpscout.net/conversation/2334371567/56014/) .

Explicit dependencies on a wait step can break the wait intention 

---

pages/pipelines/create_your_own.md
pages/pipelines/example_pipelines.md
pages/tutorials/bazel.md
pages/tutorials/docker_containerized_builds.md

This PR makes some changes to the docs in order to reference our new pipeline templates gallery wherever possible. I've added it to some of the tutorial pages, to the integration pages and to the getting started pages. Definitely open to any wording suggestions and feedback. 
Note: if viewing the Docker tutorial page locally in dev, the iframe won't load properly and you'll need [this extension](https://chromewebstore.google.com/detail/ignore-x-frame-headers/gleekbfjekiniecknbkamfmkohkpodhe) to remove some type of header to enable loading. Or you can trust me it works :P 
Thank you!

Add references to the Pipeline templates onto the docs

---

app/views/application/_head.html.erb

1. Visit https://buildkite.com/docs/apis/graphql/graphql-tutorial
2. Follow the link to “GraphQL console”
The GraphQL console page loads
It does a Turbo Drive navigation and fails on a blank page. There's a JS error trying to execute the [turbo:render callback for the docs site](https://github.com/buildkite/docs/blob/b6d31cbdb6caed91f05d266112f0bdace16a671d/app/frontend/entrypoints/application.js#L9).
https://github.com/buildkite/docs/assets/1201065/7b65889f-b6a3-477c-baf0-093115b5ca6e
By default, Turbo Drive try to load all URLs on the same origin (ie. all of buildkite.com). The [turbo-root](https://turbo.hotwired.dev/handbook/drive#setting-a-root-location) option lets us scope this instance of Turbo to the `/docs` prefix only, so it doesn't attempt to handle any navigation from the docs …

Fix broken navigation from docs back to app

---

vite.config.ts

Remove some spam from the dev logs when running via docker.
before:
after:

Prevent dev logs from spamming hot module reloading

---

pages/integrations/amazon_eventbridge.md
pages/integrations/bitbucket_server.md
pages/integrations/github_enterprise.md
pages/pipelines/build_retention.md
pages/pipelines/waterfall.md
pages/team_management/permissions.md
pages/test_analytics/permissions.md
pages/tutorials/migrating_from_bamboo.md

As well as fix up some Markdown syntax and grammar.
This PR came about as a result of https://github.com/buildkite/docs/pull/2759.

Remove 'Team' plan refs and change 'Business' plan refs to 'Pro'

---

pages/pipelines/cluster_queue_metrics.md

Currently we don't call out that `Unclustered` agents are not included in the advanced queue metrics. This is because they cannot be assigned to `queues` in the same way that the new clusters set us can be.
A `queue` can be targeted but that is simply an Elastic Stack tag, rather than a `queue` in the Buildkite sense.
Turning on `advanced queue metrics` will therefore have no affect on folks who only use `Unclustered`, nor do agents in that "cluster" have an impact on the metrics.

Clarify metrics not on unclustered

---

pages/integrations/amazon_eventbridge.md

See https://github.com/buildkite/buildkite/pull/14888.
one annoying thing about these examples is that they don't have an example of when the signal reason is semantically useful - ie, if a job failed, it have a signal reason `agent_refused`, which is much more useful to put in there than an empty string, but if we were to add a proper signal reason in there, it wouldn't make semantic sense. happy to do either.

Add signal reason to job finished event

---

pages/apis/managing_api_tokens.md

This scope is for stopping Agent. Not for registering a new Agent. Links to the new [Agent token](https://buildkite.com/docs/agent/v3/tokens) page for registering Agent.

Update write_agents scope description

---

data/nav_graphql.yml
pages/apis/graphql/cookbooks/artifacts.md

We have it documented how to get the Download URLs for Artifacts via the REST API but missing an example of using GraphQL to get them.
In addition mentining the URLs from Buildkite Artifacts expire after 10 minutes rather than 60 seconds with the REST API.
Using GraphQL to get the multiple Download URLs is faster than the REST API.

SUP-2072: Add example of using GraphQL to get the Download URL for Artifacts from a Build

---

pages/apis/graphql/cookbooks/teams.md

GraphQL example to get the members that are part of a team with their roles. This was asked in support.

Example of getting team member

---

pages/test_analytics/ruby_collectors.md

Recently we noticed quite a few of our customers have incorrectly grouped tests due to issues with RSpec automatically naming anonymous tests.
As a temporary solution, we decided to add some troubleshooting to the docs to inform people about why their tests may not be grouping correctly and what they can do to prevent it.

Add troubleshooting for TA tests not grouping

---

pages/pipelines/group_step.md

This is only specifically mentioned in the group step page, but groups and steps cannot share the same value for the `key` attribute within Build, so updating the info block.

SUP-1904: Update info on same key attribute value with groups and steps

---

data/content/aws-stack.yml
pages/agent/v3/elastic_ci_aws.md

https://github.com/buildkite/elastic-ci-stack-for-aws/releases/tag/v6.20.0

Bump elastic stack version

---

.buildkite/push-image.sh

The agent that builds these images runs buildkit, and we can instruct buildkit to push the images directly to the repository rather than export them to the docker image store then push. This should s lightly speed up this step.
I've added --provenance=false so buildkit pushes a regular image, rather than an image manifest. Some parts of our deploy pipeline are not ready for image manifests yet.

Update docker push to be buildkit compatible [PLT-2470]

---

pages/apis/agent_api/metrics.md

In https://github.com/buildkite/docs/pull/2612/files#diff-60af2a272ab3d6553f785ae3b4d0507b564787c977c712f4ecd0a8a76fb033efL13-L14 we made a change to the [Agent Metrics API](https://buildkite.com/docs/apis/agent-api/metrics) page.
We accidentally changed the REST API Authorization header type from `Token $BUILDKITE_AGENT_TOKEN` to `Bearer $BUILDKITE_AGENT_TOKEN`. This meant that customers using referring to the documentation were seeing a response like this from our API:
```sh
{
"message": "Eeep! You forgot to pass an agent registration token"
}
```
This PR fixes the documentation to reflect that for this endpoint, the Authorization header type should be `Token $BUILDKITE_AGENT_TOKEN` still.

Update Agent Metrics API Authorization type

---

pages/integrations/artifactory.md

We had a customer have an issue when trying to download artifacts across builds when using their Artifactory storage. They thought as they configured their environment variables to use their Artifactory that it would be able to download directly from Artifactory, without specifying the Build ID where the artifact was uploaded.
Updating the document elaborating the same as above.

Sup 2161 - Update Artifactory docs wording for Uploading/Downloading via Buildkite-Agent 

---

app/views/application/_analytics.html.erb

This felt like the most rails-y way to do this.
Adds the UTM 🍪 for non-third party cookie times.

feat(analytics): add utm cookie

---

pages/pipelines/dependencies.md
pages/pipelines/wait_step.md

There was some discussion about clarifying the code examples depicting `wait` step syntax in our docs.
This PR should also hopefully address this piece of direct page feedback we got here:

Fix '- wait:' syntax for pipeline dependencies page (and wait step page too).

---

.buildkite/ecr-scan-results-ignore.yml
.buildkite/pipeline.deploy.yml

Update our ECS scanning Buildkite plugin to a version that's closer to upstream:
Depends on https://github.com/buildkite/ecr-scan-results-buildkite-plugin/pull/11
- Switch to updated plugin (closer to upstream)
- Change format of ignore list, because upstream's parallel implementation is slightly different to ours
- Add fail-build-on-plugin-failure flag, to preserve our current plugin behaviour

Switch to less-diverged branch of ECR scan plugin

---

pages/team_management/permissions.md

This is a very small PR to remove some confusion around team member permissions. 
It was raised through the support channel that if Team member permissions are set to not allow pipeline creation that some members of teams can still create pipelines. 
After some investigation we found that Team Maintainers are not bound by the team member pipeline creation permissions, so I'm just adding this to the documentation so it's clear that team maintainers will be able to create pipelines.

fixed capitalisation

---

pages/test_analytics/javascript_collectors.md

[Playwright uses "reporter"](https://playwright.dev/docs/test-reporters#multiple-reporters) rather than "reporters" for all pluralities of reporter configurations.

Correct playwright config variable

---

pages/apis/rest_api/agents.md

The curl command lines were missing arguments to the `-X` flag.

fix broken curl command lines

---

pages/packages.md

The messaging on the [Buildkite Packages](https://buildkite.com/packages) page of the website will be updated soon.
From this revised callout, I'll also link through to the org admin section updates as part of merging them in with this PR:
https://github.com/buildkite/docs/pull/2824

Update public beta callout for Buildkite Packages.

---

pages/agent/v3.md

the usage of the k8s stack was been called out in the documentation as experimental and this is not the case. 
I have removed the experimental callout for the k8s service in the docs.

removed the experiment highlight from the k8s implementation doc

---

data/nav.yml
pages/packages.md
pages/packages/link_private_storage.md
pages/packages/permissions.md
pages/packages/private_storage.md
pages/team_management/permissions.md
pages/test_analytics/permissions.md

Included in this PR:
- New [Private storage](https://buildkite.com/docs/packages/private-storage) page (preview [here](https://2824--bk-docs-preview.netlify.app/docs/packages/private-storage)).
- Minor updates to the [Access control](https://buildkite.com/docs/packages/permissions#manage-teams-and-permissions-organization-level-permissions) page on **Organization-level permissions**, adding how to activate the **Packages** product (preview [here](https://2824--bk-docs-preview.netlify.app/docs/packages/permissions#manage-teams-and-permissions-organization-level-permissions)).
- Some minor updates to the other pages related to the changes made on this one ^ in the Pipelines and Test Analytics docs.

Buildkite Packages post-beta pre-GA docs updates

---

pages/clusters/manage_queues.md
pages/pipelines/hosted_agents/terminal_access.md
pages/team_management/permissions.md
pages/test_analytics/permissions.md
pages/tutorials/getting_started.md

In summary, these address the following UI changes:
- Terminal access for hosted agents in **Settings** changing from **SSH** to **Terminal Access**.
- When setting up a cluster's queue, changing the **compute** references to **agent infrastructure**.
As a bonus, also now clarified that registry permissions become available (i.e. once Buildkite Packages is enabled).

A number of updates to reflect recent UI changes to Buildkite.

---

pages/pipelines/hosted_agents/terminal_access.md

COMP-464
Add recommendation to `sleep` in a job, to extend terminal session time when using hosted agents.

docs: include sleep command in hosted agent terminal access docs

---

pages/apis/graphql/cookbooks/jobs.md

This is to fix the cookbook example query https://buildkite.com/docs/apis/graphql/cookbooks/jobs#get-a-jobs-uuid

Fix cookbook example query

---

pages/pipelines/build_exports.md

Fix an inconsistency in the build exports docs: builds that are exported to the shared buildkite bucket are held for 18 months, not 12 months. This is correct in the flow chart, but incorrect in the text. This corrects the text

Correct build export expiry from 12 months to 18 months

---

data/content/aws-stack.yml
pages/agent/v3/elastic_ci_aws.md

We've just released v6.22.0 of the elastic stack, which includes an agent version bump: https://github.com/buildkite/elastic-ci-stack-for-aws/releases/tag/v6.22.0
I've followed the steps from the release guide to update the docs, in particular:
- update the [versions of installed software](https://github.com/buildkite/docs/blob/main/pages/agent/v3/elastic_ci_aws.md?plain=1#L73-L74)
- run scripts/update-elastic-ci-stack-for-aws-parameters.sh

Update elastic stack and agent versions

---

.buildkite/pipeline.yml

In order to avoid hitting rate limits. Unauthenticated pulls from public ECR are limited to 1/sec. Authenicated pulls are 10/sec. Hopfully this will be enough for us to avoid hitting the rate limit.

Use IAM role to pull from public ecr

---

pages/pipelines/notifications.md

A small information block on using step-level notifications and how they may differ to build-level.
Step-level notifications may act differently to how people assume, eg they can ignore branch filters set at a build-level.

Add an information block for using step-level vs build-level notifications

---

pages/test_analytics/javascript_collectors.md

When using Jest with the Javascript test collector this CLI flag is required so that test file line numbers are reported to Test Analytics.

Add --testLocationInResults flag to Jest setup

---

pages/agent/v3/cli_artifact.md

Added documentation regarding support of artifact upload to self-hosted S3 compatible endpoints using BUILDKITE_S3_ENDPOINT environment variable.

Added documentation regarding support of BUILDKITE_S3_ENDPOINT

---

pages/packages/manage_registries.md
pages/packages/security/oidc.md
pages/pipelines/security/oidc.md
pages/pipelines/security/oidc/aws.md

Clarify the [OIDC intro for Buildkite Packages](https://buildkite.com/docs/packages/security/oidc) (preview [here](https://2874--bk-docs-preview.netlify.app/docs/packages/security/oidc)), to also make it clearer that 3rd-party systems mentioned on this page are designed to generate OIDC tokens for consumption by Buildkite Packages, and not the other way around (i.e. Buildkite Agents generating tokens).
Also, further down the page, clarifies/defines each 'entry' in a Buildkite Packages' registry's OIDC policy as a _rule_.
As part of implementing these changes, the [equivalent (overview) page for Buildkite Packages](https://buildkite.com/docs/pipelines/security/oidc) (preview [here](https://2874--bk-docs-preview.netlify.app/docs/pipelines/security/oidc)) was amended accordingly too.

Rework intros to OIDC overview pages to make their purposes more clear.

---

data/content/environment_variables.yaml

Addresses https://github.com/buildkite/docs/issues/2869.

Fix typo in environment variables table contents.

---

app/models/page/renderers/external_link.rb
spec/models/page/renderer_spec.rb

We currently style external links with an arrow by adding the the class `external-link`. This change extends that behavior to also add the target `_blank` so that external links open in a new tab.
Opening external links in a new tab helps users avoid losing the context they were in with Buildkite.
See the link on to Jenkins in the first sentence:
Before: [Current page](https://buildkite.com/docs/pipelines/migrate-from-jenkins)
After: [Preview page](https://2880--bk-docs-preview.netlify.app/docs/pipelines/migrate-from-jenkins)

Open external links in a new tab

---

pages/integrations/slack.md

The existing documentation for the interaction between Slack notification services and the `notify:` YAML attribute were unclear. Avoiding duplicate notifications requires excluding the pipeline using `notify:` from the default notifications.
This update attempts to clarify this behaviour.

Clarify the interaction between Slack notification services and YAML notify

---

pages/apis/rest_api/pipelines.md
pages/platform/_deriving_a_pipeline_slug_from_the_pipelines_name.md

Implementation to expose an optional slug parameter to `POST /pipelines`
This PR is to update the REST API documentation to include the optional `slug` paramenter for `docs/apis/rest-api/pipelines` for creating a YAML pipeline, and creating a visual step pipeline.

Updating `POST /pipelines` REST API Documentation to Include Optional `slug` Parameter

---

pages/tutorials/github_merge_queue.md

Merge queues are not in beta any longer with GitHub ([docs](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue)).
I've also fixed up the spacing for the indentation in the steps.

Remove beta callout for GitHub merge queues

---

pages/pipelines/hosted_agents/mac.md

Update docs to reflect latest supported macOS xcode and runtime versions on mac hosted agents.

docs: add latest supported mac xcode and runtime versions

---

.buildkite/update_graphql_docs

I noticed https://buildkite.com/buildkite/docs-graphql/builds/605 was using the wrong link. This change should fix it.

Use correct URL for annotation link

---

pages/agent/v3/prioritization.md

In order to use the `--priority` flag on `annotate` in the CLI, an agent version >= 3.65.0 is needed

Add caveat for --priority flag

---

pages/agent/v3.md
pages/agent/v3/hooks.md

This was promoted a while ago but not updated here. This moves the section to the promoted section in the docs

Move Job API docs to promoted experiments section

---

pages/test_analytics/javascript_collectors.md

Installing `buildkite-test-collector` with the `--dev` command produces a warning.
This command likely is intended to be `--save-dev` (or maybe truly `--include=dev`) instead.

fix buildkite-test-collector npm install command

---

pages/apis/rest_api/pipelines.md

Implementation to expose an optional slug parameter to `PATCH /pipelines`
This PR is to update the REST API documentation to include the optional `slug` paramenter for `docs/apis/rest-api/pipelines` for updating properties of an existing pipeline. 
A user can now update the pipeline `slug` name using `PATCH /pipelines` when they provide a `slug` parameter. 
It is important to note that if a user updates the `name` of a pipeline _without_ providing a `slug` parameter, a new `slug` will be generated for that pipeline that is derived from the updated name. If a user updates the `name` and forgot to add the `slug` parameter (because they wanted to preserve their pipeline `slug`) they can update the `slug` name in isolation.
Under "Update a pipeline" in the "Optional request body properties" …

Updating PATCH /pipelines REST API Documentation to Include Optional `slug` Parameter 

---

.buildkite/pipeline.yml
data/nav.yml
pages/packages.md
pages/packages/_file_details_page_sections.md
pages/packages/_registry_slug.md
pages/packages/alpine.md
pages/packages/container.md
pages/packages/debian.md
pages/packages/files.md
pages/packages/getting_started.md
pages/packages/gradle.md
pages/packages/javascript.md
pages/packages/manage_registries.md
pages/packages/maven.md
pages/packages/permissions.md
pages/packages/python.md
pages/packages/red_hat.md
pages/packages/ruby.md
pages/packages/terraform.md

https://linear.app/buildkite/issue/PKG-6378/documentation-anyfile
First cut of docs for the new 'files' package type. 
This is a bit awkward as a file isn't really a package type, nor part of an ecosystem. I've rejigged everything I thought appropriate, but perhaps the nav should change and be outside the package ecosystem parent heading, let me know what you think.
I've also fixed in same PR (see individual commits): 
* Publish button and title labelling for Javascript + Red Hat
* Beta removed from enable packages flow
* Installation instructions section title is now simply 'Instructions'
* The ordering of the pipeline - my OCD needs to see the steps being built first on the left 🙃

[PKG-6378] Documentation for Packages 'Files' (generic)

---

config/initializers/content_security_policy.rb

We've been sending CSP reports to a route on our own site for years, but never looking at them or taking action.
We're trialing report-uri.com as a cheap hosted option for collecting these reports and (hopefully) discovering actionable improvements we can make to our Javascript security.
The docs CSP headers are in report only mode and this doesn't change that. We should get data, but I expect no customer visible behaviour change.

Move Content Security Policy reports to report-uri.com [PLT-2978]

---

pages/pipelines/hosted_agents/linux.md

maybe this was just a leftover from a prior cleanup? it doesn't seem to fit in the doc anymore

remove fragment from when we didn't offer custom images

---

pages/agent/v3/cli_step.md
pages/agent/v3/help/_step_get.md

Had a customer reach out checking which attributes could be used with the `buildkite-agent step [get|update]` commands as they found it unclear from the docs. So adding list of available Attributes for clarity.
Will need to also update the Agents docs - https://github.com/buildkite/agent/blob/d387c3bdd58eb3fd94906e3e400ca8e0ab230e87/clicommand/step_get.go#L26-L31 - to correct example as `retry` is not an available attribute at the time of writing.

SUP-2343: Add lists of Attributes that can be used with `buildkite-agent step` 

---

pages/pipelines/managing_priorities.md

`priority` can be used as a top level value, applying to all steps in a build that don't have their own `priority` value set. This may come in handy to know where folks wish for a **build** to run quickly.

Add information on using priority as a global value

---

pages/agent/v2/debian.md
pages/agent/v3/debian.md

For context if you pull down the docker image for debian curl and gpg are not installed by default as it is a "slim" image, so subsequent commands fail.
Just a small tweak to help customers.

This small change ensures all dependencies used are installed

---

pages/apis/rest_api/annotations.md

This is already supported in the CLI (where I ripped the description): https://buildkite.com/docs/agent/v3/cli-annotate#creating-an-annotation-options
And you can see the implementation as well: https://github.com/buildkite/agent/blob/5d69f8b625a97ec7b7db1cfc7031c31cf89a10ae/api/annotations.go#L14C25-L14C33
I also tested this locally:
```
% curl -H "Authorization: Bearer $TOKEN" \
-X POST "https://api.buildkite.com/v2/organizations/.../pipelines/.../builds/254731/annotations" \
-H "Content-Type: application/json" \
-d '{
"body": "Hello world!",
"style": "info",
"context": "greeting",
"priority": 10
}'
{"id":"...","context":"greeting","style":"info","priority":10,"created_at":"2024-08-16T14:37:09.882Z","updated_at":"2024-08-16T14:37:09.882Z","body_html":"<p>Hello world!</p>\n"}
```

Add `priority` to POST to annotations

---

data/content/agent_attributes.yaml

The descriptions in the agent is slightly different to the docs, this causes confusion around the behaviour.

fix for language around no hooks or plugins description

---

data/nav.yml
pages/packages.md
pages/packages/_helm_registry_slug.md
pages/packages/container.md
pages/packages/helm.md

In addition to OCI registries, we will soon be adding support for Helm native registries. These are a separate registry type.  I'm not sure if it will be better to have them documented on the same page or separate pages. For the time being I decided to use one page; therefore, I named this Helm rather than Helm OCI.
[PKG-7456](https://linear.app/buildkite/issue/PKG-7456/documentation-helm-oci)

Added docs for Helm OCI registries

---

pages/test_analytics/test_ownership.md

While browsing the docs for test owners I noticed a typo `COEDOWNER`

Fix typo in TESTOWNERS example

---

pages/integrations/amazon_eventbridge.md

The example payloads for eventbridge events only showed fields that buildkite varies. As raised in https://github.com/buildkite/docs/pull/2935, copy and pasting this into the eventbridge sandbox as-is results in an error message that the sample event is not valid.
Putting the full payload in the examples will make it easier for users to test patterns using the eventbridge sandbox.

Add standard eventbridge fields to the example payloads

---

pages/apis/rest_api/analytics/flaky_tests.md

Now that the Test Analytics v2 ingestion is GA we can add the last_resolved_at field to the flaky-tests api docs

Document last_resolved_at flaky-tests api field

---

config/initializers/content_security_policy.rb

We're trialing an alternative vendor to see how they compare. URL based on docs at https://www.uriports.com/getting-started-with-website-monitoring?subdomain=buildkite

Change where we send CSP reports

---

.buildkite/ecr-scan-results-ignore.yml

These CVEs are in krb5, a library that handles kerbeos authentication. We don't any kerbeos in production, but also the issues are  fixed in 1.20.1-2+deb12u2 which is available in the debian repos and the docker build logs show is being installed. This seems to be a false positive by ECR

Ignore CVE-2024-37371 and CVE-2024-37370 in docker image

---

data/content/environment_variables.yaml

Add the following environment variables to the [Configure pipelines → Environment Variables](https://buildkite.com/docs/pipelines/environment-variables#buildkite-environment-variables) page:
- `BUILDKITE_ORGANIZATION_ID`
- `BUILDKITE_PIPELINE_ID`

Add ORGANIZATION_ID and PIPELINE_ID environment variables to docs

---

config/initializers/content_security_policy.rb

Our CSP is in report-only mode, but we'd like to get it closer to being enforcable. As a step in that direction I've opened a few pages in production, audited the most common CSP warnings in the browser console, and this should resolve them. These are all expected tools, our policy has just bitrotted, or the vendor has changed their resources.
1. object_src: we can't include `none` alongside an actual value
2. connect_src: we load GA v4 from www.googletagmanager.com, but it wants to submit data to https://www.google-analytics.com
3. connect_src: helpscout beacon wants tosend data to a cloudfront distribution
CSP docs for Helpscout beacon (mentions the cloudfront domain): https://docs.helpscout.com/article/815-csp-settings-for-beacon
CSP docs for datadog real user monitoring: …

A few tweaks to our report-only CSP header

---

pages/pipelines/waterfall.md

- Add info block on why a build time may differ to the total time of a waterfall view

Add info on build time discrepency vs waterfall jobs

---

data/content/test_splitting_env.schema.yaml
data/content/test_splitting_env.yaml
pages/test_analytics/test_splitting.md

To make it easier to manage the environment variables for Test Splitting, I have extracted them into a yaml file, and render them in the docs using `erb`.
This PR doesn't change the content of the page, however, it changes the formatting to be consistent with other pages that has a list of environment variables / configurations.
**Before**
**After**

Extract Test Splitting Environment Variables into a yaml

---

data/nav.yml
pages/apis/agent_api.md
pages/apis/agent_api/metrics.md
pages/apis/rest_api/access_token.md
pages/apis/rest_api/agents.md
pages/apis/rest_api/analytics/flaky_tests.md
pages/apis/rest_api/clusters.md
pages/apis/rest_api/meta.md
pages/apis/rest_api/organizations.md
pages/apis/rest_api/organizations/members.md
pages/apis/rest_api/packages/registries.md
pages/apis/rest_api/pipeline_templates.md
pages/apis/rest_api/pipelines.md
pages/apis/rest_api/rules.md
pages/apis/rest_api/teams.md
pages/apis/rest_api/teams/members.md
pages/apis/rest_api/teams/pipelines.md
pages/apis/rest_api/teams/suites.md
pages/apis/rest_api/user.md

New section for Packages API endpoints - Registries.

[PKG-7402] API docs for registries index

---

pages/apis/rest_api/packages/registries.md

[PKG-7403] - API docs for registries create

---

pages/apis/rest_api/packages/registries.md

[PKG-7404] API docs for registries update

---

pages/apis/graphql/cookbooks/rules.md

Noticed that the `getRules` GraphQL cookbook had a slight indentation added to the example - which I've brought it back to be in-line with the rest of the examples.

`getRules` GraphQL Rules cookbook indentation

---

pages/apis/graphql/cookbooks/rules.md
pages/apis/rest_api/rules.md
pages/pipelines/rules.md
pages/pipelines/rules/manage.md

In https://github.com/buildkite/buildkite/pull/18890 we are updating the rules parameter names to `source_pipeline` and `target_pipeline` rather than `source_pipeline_uuid` and `target_pipeline_uuid`. This is because these fields will now accept either a UUID or a pipeline slug. 
This PR updates the docs to indicate the above.

Update docs to reflect new naming for Rules params, and creation via pipeline slugs 

---

pages/agent/v3/signed_pipelines.md
vale/styles/Buildkite/h1-h6_sentence_case.yml

We have introduced the option to use AWS KMS keys with signed pipelines, this is seperate from the self managed keys already supported so I have added some setup documentation.

Add a section on using AWS KMS keys with signed pipelines

---

pages/agent/v3/cli_oidc.md

We're allowing some more optional OIDC claims for cluster and cluster queues.

Add optional cluster and queue oidc claims

---

pages/agent/v3/cli_oidc.md

Follow on from https://github.com/buildkite/docs/pull/2986, document optional agent tag oidc claims. This allows adding a claim to match any agent tag.

Document agent tag oidc claims

---

pages/pipelines/hosted_agents/mac.md

Add "gcloud CLI" to hosted agents to "Assorted tools" in Mac docs, now gcli is available.

Add gcloud CLI to hosted agents

---

package.json
pages/pipelines/build_timeouts.md

A customer has asked why there was delays in expiring jobs in their org. After clarification from the pipelines team, it would be good to have this information available for the customers to know.

Job expiry process delays

---

app/frontend/css/components/_page.scss

- on tablet, the screen is split into 4 grid areas: if there's no automatic TOC generated, which takes up the top right corner, and the content doesn't fill up the screen, the content ends up in the bottom left corner. If we add a `minmax` to the grid rows, with a min of 0 and a max of auto, it should sort itself out better.
**After:**
**Before** Reported by @zhming0:

fix(tablet): set rows grid to 0 if it's empty (e.g. no toc section)

---

pages/pipelines/input_step.md

The examples show the field, but it is undocumented.
Description/Example ripped from https://github.com/buildkite/pipeline-schema

Document `text` field in InputStep:TextInput

---

pages/pipelines/block_step.md
pages/pipelines/command_step.md
pages/pipelines/group_step.md
pages/pipelines/input_step.md
pages/pipelines/trigger_step.md
pages/pipelines/wait_step.md

- `key` has aliases `identifier` and `id` (however I suspect y'all don't want to advertise the latter due to confusion with `BUILDKITE_STEP_ID` (not being the `id`)) so make sure `identifier` is listed as an alias
- Document the "not-UUID-like" restriction on all `key`s
- Add missing `key` field to Trigger and Wait step docs

Improve/Standardize `alias`

---

data/content/test_splitting_env.yaml
pages/test_engine/test_splitting/configuring.md

Currently documented ENV var name [is incorrect](https://github.com/buildkite/test-engine-client/blob/3f045ed4a69a569913b007ca3aecc96a0c541e00/internal/config/env.go#L52).

Fix incorrect test runner env var name

---

pages/apis/graphql/cookbooks/jobs.md

Based on the finding from the customer raising this change.
When no "agentQueryRules" is specified in the query https://buildkite.com/docs/apis/graphql/cookbooks/jobs#get-all-jobs-in-a-given-queue-for-a-given-timeframe, it pulls all the jobs across the cluster.

SUP-2860/update-job-queue-api

---

pages/apis/rest_api/pipelines.md

This property is listed in both required/optional.

Make `cluster_id` just required (not optional as well)

---

pages/apis/rest_api/pipelines.md

`cluster_id` is the UUID ID, not the b64 encoded one

---

pages/apis/rest_api/pipelines.md

Hi @thejcannon , following on from your last two PR fixes, I thought I'd ask for your brief review on this PR.
This also implements the same fixes to another section of the same page regarding the creation of new pipelines.

Remove additional optional mention of cluster_id on other pipeline creation section and fix value type.

---

pages/apis.md

We've just received word from GitHub that they're ready to go live with our membership to the GitHub Secret Scanning Program:
https://docs.github.com/en/code-security/secret-scanning/secret-scanning-partnership-program/secret-scanning-partner-program#the-secret-scanning-process
But it seems they need this documentation to be up before they can hit the 'go' button:
The 'API' section seemed like the most logical place for this information, but I don't mind too much - just need somewhere to point to.
Once this is up, I can reply to GitHub and hopefully they can press the big red button!

feat: add docs for GitHub secret scanning program

---

data/content/agent_attributes.yaml
data/content/environment_variables.yaml

This feature was added [6 years ago](https://github.com/buildkite/agent/commit/93daef3e00f7481f8000e07975bd98275c3f0c84) and I think it's confusing referring to it as experimental given it's unrelated to `BUILDKITE_AGENT_EXPERIMENT`.
I don't feel strongly about experimental or not, I would just like `data/content/environment_variables.yaml` updated.
Closes https://github.com/buildkite/docs/issues/1819

document and remove BUILDKITE_GIT_FETCH_FLAGS from experimental

---

pages/apis/webhooks/pipelines/build_events.md

- Adding clarification of build webhooks not lining up 1:1 with REST API response body.
- Fixing typo for "Finding out if a build is blocked"

Adding build event response disclaimer
