- pages/agent/upgrading_to_v2.md.erb
Changed "you should not switch to using hooks" to "you should now switch to using hooks".
> Fix a typo in "Bootstrap customizations"

- pages/guides/writing_build_scripts.md.erb
> Fixed tiny semantic typo

- pages/guides/docker_containerized_builds.md.erb
> Typo, added missing word.

- pages/guides/docker_containerized_builds.md.erb
Please see https://github.com/buildkite/agent/issues/219 for details.
> Document WORKDIR gotcha

- pages/agent/uploading_pipelines.md.erb
Ok, big updates to this doc. Can you review for sanity @keithpitt?
> Reword the uploading pipelines documentation

- pages/guides/github_enterprise.md.erb
> Update the firewall install docs with nginx proxy info

- pages/guides/github_enterprise.md.erb
My bad, I had not tested that part quite enough.
This fixes the regex.
> Fix nginx config

- pages/webhooks.md.erb
- pages/webhooks/agent_events.md.erb
- pages/webhooks/build_events.md.erb
- pages/webhooks/integrations.md.erb
- pages/webhooks/job_events.md.erb
- pages/webhooks/ping_events.md.erb
Adds docs for buildkite/buildkite#1182 and adds Google Cloud Functions to the webhook integrations
> Add webhook event name to payloads

- pages/guides/deploying_to_heroku.md.erb
> Update the Heroku guide to support automatic deploys

- pages/agent/build_pipelines.md.erb
- pages/guides/uploading_pipelines.md.erb
> Doc updates for `block` steps - includes branch scoping.

- pages/guides/elastic_ci_stack_aws.md.erb
- pages/guides/getting_started.md.erb
> Elastic CI Guide

- pages/guides/docker_containerized_builds.md.erb
@toolmantim might want to double check this one
> Docker setup instructions tweak

- pages/api/jobs.md.erb
This endpoint was added a while ago, but it seems no docs were added. So here they are!
> Add docs for job retry

- pages/agent/debian.md.erb
- pages/agent/redhat.md.erb
- pages/agent/ubuntu.md.erb
Consolidate #40 and #46 with the units we currently ship with the agent. We'll probably start shipping a template like buildkite/agent#363 and start recommending that eventually.
/cc @keithpitt
> Recommend systemd templates & instances

- pages/basics/pipelines.md.erb
> Add pipelines doc

- pages/guides/uploading_pipelines.md.erb
Couple of small updates based on slack discussion and my misadventures with docker compose.
> Updated the compose variables in the uploading pipeline docs.

- pages/how_tos/deploying_to_heroku.md.erb
- pages/how_tos/migrating_from_bamboo.md.erb
- Some minor edits to Migrating from Bamboo and Deploying to Heroku
- Added a time estimate to one section of the deploying to Heroku doc, testing that out before adding these to all of the sections of the how to docs
> Editing docs, adding time estimate

- pages/how_tos/gitlab.md.erb
Super minor fixes for the Gitlab docs
> Moving some words around

- pages/builds/environment_variables.md.erb
> Add buildkite timeout to env vars

- pages/agent.md.erb
> Duplicate word in documentation

- pages/agent/gcloud.md.erb
> Fix typo in gcloud.md.erb

- pages/agent/hooks.md.erb
Adds docs for pre-exit hooks, and cleans up the artifact hook descriptions
> Add pre-exit hook docs

- pages/agent/aws.md.erb
- pages/quickstart/elastic_ci_stack_aws.md.erb
Update some words based on issue #113! Moved some things around too ✨
> Update elastic stack words

- pages/rest_api/jobs.md.erb
Minor typo (I think) that I noticed while reading docs
> unlocked => unblocked

- pages/rest_api/pipelines.md.erb
> Document Pipeline Create team_uuids field

- pages/pipelines/permissions.md.erb
This cleans up the the bash example, to add syntax highlighting, and remove some of the unrelated stuff too.
> Bash cleanups

- pages/agent/configuration.md.erb
This [nifty feature](https://github.com/buildkite/agent/pull/430) appears under-documented.
> Document BUILDKITE_TIMESTAMP_LINES feature

- pages/agent/plugins.md.erb
Ok, I got sick of waiting for me to finish the agent docs and am starting to ship them incrementally instead of big bang.
This is the plugins page. I think it will be useful alongside the existing docs.
> Add docs for plugins for beta agent v3.0

- pages/builds/environment_variables.md.erb
This PR adds some missing build environment variables, and documents a few of the news ones.
> Update build environment variables

- pages/pipelines/trigger_step.md.erb
Adding some words about access control to the Trigger step doc re: https://github.com/buildkite/docs/issues/102
I'm not sure if these additions are super accurate - @ticky would you mind having a quick squiz and let me know if anything needs to be added or changed? 😊
> Update trigger docs

- pages/pipelines/block_step.md.erb
part of buildkite/buildkite#2399
> Document line endings for block step

- pages/agent/plugins.md.erb
In this PR there is:
- Fix for incorrect grammar.
- Fix for an invalid link.
> Fixes for plugins page

- pages/pipelines/defining_steps.md.erb
Hope this will help Windows users.
> Add pipeline upload example for windows users

- pages/pipelines/branch_configuration.md.erb
It took me a few attempts to figure out that you can have multiple wildcards.
> Add an example for patch semver number

- pages/agent/upgrading_to_v3.md.erb
This adds a guide from upgrading from v2 to v3. 
TODO:
> Add guide for upgrading to v3

- pages/agent/v3/upgrading.md.erb
Applies some copy tweaks and adds links to the upgrade guide for the v3 agent
> Update the v3 upgrade guide

- pages/agent/v3/hooks.md.erb
- pages/agent/v3/windows.md.erb
This discusses how Windows `.bat` hooks are run, and also describes Git for Windows.
> Windows hooks

- pages/agent/v3/plugins.md.erb
Added in the suggestions from @keithpitt in Basecamp, plus some more editing. 
@lox could you please check the examples? @keithpitt mentioned they might be out of date.
> Update plugins guide

- pages/agent/v3.md.erb
Added a line about sending `SIGTERM` to the agent directly. I haven't done this before, so I'm not sure if I got the bits right 😅Let me know if you want more detail in there @keithpitt!
> Add sigterm note

- pages/agent/v3/install/_windows.md.erb
- pages/agent/v3/windows.md.erb
Document how to use the new install script to install via Powershell, also covers how to run as a service.
> Install on windows docs

- pages/agent/v3/windows.md.erb
I was playing with Windows stuff, and I wasn't sure how to open a powershell with Admin privelages. It's required, so I figured some sneaky words couldn't hurt!
> Add instructions on how to open powershel with admin

- pages/agent/v2.md.erb
- pages/agent/v3.md.erb
This adds links to https://buildkite.com/docs/agent/v3#usage, also updated the v2 version. 
Thanks for the suggestion @petemounce!
> This adds links in the cli usage overview to the topics

- pages/agent/v3/install/_debian.md.erb
- pages/agent/v3/install/_freebsd.md.erb
- pages/agent/v3/install/_linux.md.erb
- pages/agent/v3/install/_osx.md.erb
- pages/agent/v3/install/_ubuntu.md.erb
- pages/agent/v3/install/_windows.md.erb
- pages/agent/v3/install/_yum.md.erb
- pages/agent/v3/securing.md.erb
- pages/agent/v3/windows.md.erb
Will yolo merge. Lemme know if you see any mistakes!
> Update v3 docs to reference stable instead of beta

- pages/agent/v2.md.erb
> Add v2 warning to overview page

- pages/pipelines/command_step.md.erb
> Alphabeticise for readability

- pages/agent/v3/plugins.md.erb
This updates all the plugin.json information to the new plugin.yml, and links to all the tools that people might find useful when developing plugins.
> Update to plugin.yml and add related tools

- pages/builds/environment_variables.md.erb
- pages/pipelines/command_step.md.erb
- pages/pipelines/trigger_step.md.erb
- pages/pipelines/wait_step.md.erb
Also cleans up some of the step type pages to make them a little more consistent.
> Link to the trigger step doc from the env variables doc

- pages/agent/v3/configuration.md.erb
Fixed the name of the env var, re: slack convo this arvo 😊
Should we also update the v2 version of this doc?
> Update env var to reflect code

- pages/rest_api/_builds_list_query_strings.md.erb
See discussion here: https://buildkite-community.slack.com/archives/C02T53V9H/p1530690123000302
cc @keithpitt
> Document `commit` param for builds list

- pages/agent/v3/cli_annotate.md.erb
~TODO: Update agent help text~ buildkite/agent#792
> Refer to Annotation bodies as Markdown

- pages/agent/v3/prioritization.md.erb
BUILDKITE_PRIORITY should be BUILDKITE_AGENT_PRIORITY
> Fix env var typo in prioritisation

- pages/agent/v3/gcloud.md.erb
Didn't see this in docs, added it. Please obviously feel free to hijack and extend :)
> Mention BUILDKITE_GCS_ACCESS_HOST

- pages/apis/graphql_api.md.erb
Removed link to learngraphql.com.
Closes #304.
> Remove broken link

- pages/pipelines/command_step.md.erb
- pages/pipelines/plugins.md.erb
See https://github.com/buildkite/docs/issues/275#issuecomment-400604220
closes #275 
cc @lox
> Document the “plugins” property of command steps

- pages/tutorials/adfs.md.erb
- pages/tutorials/custom_saml.md.erb
- pages/tutorials/google-oauth.md.erb
- pages/tutorials/google_oauth.md.erb
- pages/tutorials/okta.md.erb
- pages/tutorials/onelogin.md.erb
Revisions from @keithpitt's review a while back. These still don't have sidebar links, they'll be added when SSOv2 goes live. Not in need of review yet 😄
Still to do:
> [WIP] Update SSO guides

- pages/pipelines/defining_steps.md.erb
A small re-write of some of the Defining Steps doc - trying to make it clearer, and add some more beginner-friendly info.
> Update defining steps

- pages/apis/rest_api.md.erb
Just published https://github.com/felixfbecker/PSBuildkite
> Add PSBuildkite API client

- pages/agent/v3/configuration.md.erb
> Remove rogue backticks

- pages/apis/webhooks.md.erb
Adds a list of the webhook events, which you can only find via the settings UI at the moment.
> List all the webhook events

- pages/pipelines/block_step.md.erb
Hello :wave:  
This would be nice to have on docs (: Unless there is more to it than I just found.
However, I need from you this magic `X` number. 
Let me know if that makes sense.
> block steps: Added note about different format for different numbers of option fields.

- pages/pipelines/artifacts.md.erb
Thanks for the catch @keithduncan 🙏🏻
> Change hyphen to underscore

- pages/pipelines/command_step.md.erb
Not too sure of the wording, just wanted to open a PR up with the correct rules so it can be adjusted and merged.
> Clarified -1 handling and retries

- pages/pipelines/defining_steps.md.erb
Oops, forgot to escape the emoji 🤦🏻‍♀️
Also shuffling the code example and text explanation so that they make more sense.
> Emoji and ordering fixes

- pages/integrations/sso.md.erb
- pages/integrations/sso/adfs.md.erb
- pages/integrations/sso/sso_setup_with_graphql.md.erb
Minor fixes for https://github.com/buildkite/buildkite/pull/3433
> Fix links and spelling

- pages/agent/v3/hooks.md.erb
- pages/pipelines/defining_steps.md.erb
Clarity issue raised in https://github.com/buildkite/docs/issues/368. Also closes https://github.com/buildkite/docs/issues/369.
> Clarify cli wording

- scripts/check-agent-env.sh
This adds a script to help find agent env that isn't documented.
> Add a script to find undocument agent env

- pages/apis/rest_api/builds.md.erb
We now support optional build messages in the REST API, so this just updated the message param to match 🙌🏼
> Build message is now optional

- pages/integrations/sso/custom_saml.md.erb
- pages/integrations/sso/google_oauth.md.erb
Closes https://github.com/buildkite/docs/issues/390 - thanks for pointing it out @eleanorakh! 
While checking the other docs for the same numbering issue, I realised that the custom SAML doc never made it over to the new steps-based structure. This updates to use the new, standard words and formatting.
> Fix google sso step numbers

- pages/apis/rest_api/artifacts.md.erb
Updated the description of artifact delete based on the discussion with @toolmantim and @eleanorakh  in https://github.com/buildkite/docs/pull/384
Closes https://github.com/buildkite/docs/issues/381
> Expand description of artifact delete

- pages/agent/v3/docker.md.erb
> Add `--name` to broken docker run examples

- pages/integrations/sso.md.erb
> Fix typo, add commas, capitalise URL

- pages/agent/v3/tokens.md.erb
Adds a new page covering Agent tokens and how they work/how to use them etc.
Closes #401
> Add new page about Agent tokens

- pages/integrations/sso/custom_saml.md.erb
Thanks @keithpitt for pointing out the out of date link in the Custom SAML doc! This PR removes it 👍🏻
> Fix custom saml doc

- pages/agent/v3/docker.md.erb
Often folks have issues where files are left as root. I often link to https://github.com/buildkite/agent/issues/407#issuecomment-370573431 for some help, but would be great to have that help here. 
It's a really tricky thing to explain, but it bites lots of folks. Thoughts @toolmantim / @harrietgrace?
> Add some guidance about docker permissions problems

- pages/pipelines/defining_steps.md.erb
Add in the missing forward slash in the link to the artifacts doc 🤦🏻‍♀️
> Fix broken link

- app/views/layouts/application.html.erb
Forgot to add this in https://github.com/buildkite/docs/pull/432 😅
> Add cloud identity sidebar item

- app/views/layouts/application.html.erb
- pages/tutorials/parallel_builds.md.erb
Updating the code example for running multiple agents, from https://github.com/buildkite/docs/issues/186. @toolmantim did anything else need to be added alongside this example? Or was the just the code update?
Closes #186
> Update parallelism example

- pages/pipelines/command_step.md.erb
Adds docs over the `soft_fail` command step field ⚠️💖
> Soft fail command step docs

- pages/agent/v3.md.erb
An update to the addition in #462. Added in @toolmantim's formatting and words suggestion.
> Update formatting and words for signal handling section

- app/views/layouts/application.html.erb
- pages/pipelines/secrets.md.erb
Adding some basic info about managing your secrets in pipelines. 
To do:
> Add docs page about secrets management

- pages/pipelines/block_step.md.erb
Not sure what else to put in this, but this seems like a start, and I don’t want to forget! 😅
Docs for buildkite/buildkite#3864
> Add the `multiple` attribute to the block step docs

- pages/tutorials/docker_containerized_builds.md.erb
This updates the docker and docker-compose versions in the Containerized Builds page.
> Bump docker and docker-compose versions

- pages/pipelines/trigger_step.md.erb
For https://forum.buildkite.community/t/allow-triggered-child-build-to-inherit-pr-related-env-vars-from-parent-build/168
> Add a pull request trigger example

- pages/apis/rest_api/pipelines.md.erb
From https://github.com/buildkite/buildkite/pull/4039 after the request in https://github.com/buildkite/docs/issues/499. 
@sj26 Does this look legit?
Closes #499.
> Add `visibility` to pipeline rest api

- app/views/layouts/application.html.erb
- pages/apis/rest_api/annotations.md.erb
> Add Annotations REST API to docs and sidebar

- pages/pipelines/build_meta_data.md.erb
> Fix typo in build-meta-data

- app/views/layouts/application.html.erb
- pages/pipelines/block_step.md.erb
- pages/pipelines/branch_configuration.md.erb
- pages/pipelines/command_step.md.erb
- pages/pipelines/conditionals.md.erb
- pages/pipelines/ignoring_a_commit.md.erb
- pages/pipelines/trigger_step.md.erb
- pages/pipelines/wait_step.md.erb
This PR adds a page about the new step conditionals, and adds it to the Pipelines section of the sidebar.
> Add page about step conditionals

- pages/pipelines/conditionals.md.erb
Added docs for this stuff before launch
> Add documentation for `build.pull_request.*` conditional variables

- pages/agent/v3.md.erb
The cancel grace period can be customized
> Update the cancel grace period in Signal Handling

- pages/pipelines/conditionals.md.erb
> Add docs and an example for using `build.source`

- app/views/layouts/application.html.erb
- pages/apis/rest_api/user.md.erb
Adds a basic page for the User REST API endpoint. @sj26 two questions: is that description at the top correct? and is there anything missing? 😊
Closes #498
> Add user endpoint API page

- pages/integrations/amazon_eventbridge.md.erb
Some tiny words fixes for the EventBridge integration doc.
> Fix some copy issues in the EventBridge doc

- pages/agent/v3/prioritization.md.erb
Fixes from @toolmantim's comments in #579 - I was too keen with the merge button 😅
> Fix load balancing info

- pages/pipelines/conditionals.md.erb
Somebody asked how to do logic with arrays, and I realised we didn't have the includes operator in here — so here it is! Super useful for things like checking teams.
> Document and demonstrate array includes operator

- pages/pipelines/conditionals.md.erb
This variable was recently added to the conditional system. It's only available on pull requests from github.
> document the new build.pull_request.draft variable

- Gemfile.lock
> Update to bundler 2.0.2

- pages/pipelines/block_step.md.erb
This PR fixes a little typo. ✨
> Change article An to A

- pages/pipelines/defining_steps.md.erb
Our code examples have a mix of quoted and unquoted values, this PR wraps them all in quotes.  
Closes #600
> Add quotes to labels

- pages/pipelines/environment_variables.md.erb
> add BUILDKITE_PIPELINE_NAME

- Gemfile
- Gemfile.lock
- config/initializers/lograge.rb
Add https://github.com/roidrage/lograge so that each Rails request only logs a single line.
> lograge; concise Rails logging

- pages/agent/v3/cli_meta_data.md.erb
- pages/pipelines/build_meta_data.md.erb
Document the newly added meta-data value limits and intended deprecation, and add some basic guidelines about what to use meta-data for.
> Meta data limits

- .buildkite/pipeline.deploy.yml
Improve deployment security by specifying new agents.
> Simplify deploy agent queue name

- pages/agent/v3/hooks.md.erb
I feel the need to apologise for this anally retentive fix.
> 🔍 Consistent "Agent, Plugin" ordering

- pages/integrations/amazon_eventbridge.md.erb
> Mention which EventBridge event the example requires 

- pages/integrations/amazon_eventbridge.md.erb
> Add missing “to” in EventBridge docs

- pages/agent/v3/hooks.md.erb
> Revert hooks ordering fix

- pages/pipelines/environment_variables.md.erb
Fixes #635 by mentioning the directory not the bin.
> Fix BUILDKITE_BIN_PATH description

- public/500.html
> Update maintenance page

- pages/tutorials/docker_containerized_builds.md.erb
Spotted from https://twitter.com/borja_burgos/status/1237800221347807233 🔎
> Use official memcache image

- app/models/page.rb
- pages/apis/webhooks.md.erb
- pages/apis/webhooks/agent_events.md.erb
- pages/apis/webhooks/build_events.md.erb
- pages/apis/webhooks/job_events.md.erb
- pages/apis/webhooks/ping_events.md.erb
- pages/integrations/amazon_eventbridge.md.erb
I small code cleanup in prep for switching the Markdown renderer
> Hardcode the webhook descriptions

- app/assets/stylesheets/public/_docs.scss
- pages/apis/webhooks.md.erb
In #442 we need to add a description to the links, so this updates the CSS and markup to support it
> Add support for specifying a link description

- pages/integrations/amazon_eventbridge.md.erb
We are now sending the agent token UUID, created_at and description through in the EventBridge agent events.
> Add agent token details to EventBridge agent events

- Gemfile
- Gemfile.lock
> add pry in development

- pages/agent/v3/hooks.md.erb
- pages/agent/v3/upgrading.md.erb
- pages/agent/v3/windows.md.erb
- pages/deployments.md.erb
- pages/pipelines/command_step.md.erb
- pages/pipelines/environment_variables.md.erb
- pages/pipelines/secrets.md.erb
- pages/tutorials/docker_containerized_builds.md.erb
> Fix old plugins links

- pages/pipelines/notifications.md.erb
Docs for recent work on Slack direct messages notifications
> Update for direct messages goodness

- deploy/task-definition-template.json
These are used to render the matomo fragment on every page
> Set matomo ENV vars in production

- pages/agent/v3/help/_meta_data_exists.txt
- pages/agent/v3/help/_meta_data_get.txt
- pages/agent/v3/help/_meta_data_keys.txt
- pages/agent/v3/help/_meta_data_set.txt
The agent meta-data help text was updated in https://github.com/buildkite/agent/pull/1160, this PR manually updates the help text in the CLI docs 👍🏻
Closes #631
> Update metadata job id description

- pages/deployments.md.erb
- pages/deployments/deploying_to_kubernetes.md.erb
- pages/integrations/artifactory.md.erb
- pages/pipelines/artifacts.md.erb
- pages/pipelines/block_step.md.erb
- pages/pipelines/branch_configuration.md.erb
- pages/pipelines/command_step.md.erb
- pages/pipelines/conditionals.md.erb
- pages/pipelines/controlling_concurrency.md.erb
- pages/pipelines/defining_steps.md.erb
- pages/pipelines/dependencies.md.erb
- pages/pipelines/input_step.md.erb
- pages/pipelines/notifications.md.erb
- pages/pipelines/secrets.md.erb
- pages/pipelines/trigger_step.md.erb
- pages/pipelines/wait_step.md.erb
- pages/plugins/writing.md.erb
- pages/tutorials/docker_containerized_builds.md.erb
- pages/tutorials/migrating_from_bamboo.md.erb
- pages/tutorials/parallel_builds.md.erb
> Add some filnames!

- .gitignore
- config/algolia-test.json
- config/algolia.json
Improve the search index. Currently just updating the `test_docs` index.
I'll see what other tweaks we need, then copy the config to `prod_docs` when we're happy.
> Improve search

- deploy/task-definition-template.json
🔎 spotted while browsing around 😅
> Fix typo for MATOMO_URL

- pages/agent/v3/cli_artifact.md.erb
- pages/pipelines/environment_variables.md.erb
> Add possible values for BUILDKITE_S3_ACL

- pages/apis/rest_api.md.erb
Proposing the [buildkite-php](https://github.com/bbaga/buildkite-php) library to be added to the list of available clients
> PHP Client library

- pages/pipelines/environment_variables.md.erb
Adding the two new env vars introduced in https://github.com/buildkite/buildkite/pull/4762 ⚡️
> Add build author vars

- pages/pipelines/artifacts.md.erb
Super simple docs addition to address #591
> Downloading artifacts from triggered builds

- pages/pipelines/branch_configuration.md.erb
> Mention limitations of branch wildcards 

- pages/pipelines/block_step.md.erb
- pages/pipelines/dependencies.md.erb
Improve docs in response to #714
> Clarify implicit and explicit dependencies

- pages/apis/rest_api.md.erb
Proposing the [buildkite-swift](https://github.com/aaronsky/buildkite-swift) package to be added to the list of available clients
> Swift Client package for REST and GraphQL

- pages/plugins/writing.md.erb
Stumbled on these issues when going through this tutorial
> Fixing a few inconsistencies in the writing a plugin tutorial

- pages/pipelines/controlling_concurrency.md.erb
Tweaking some of the wording that confused me, and prioritize the better example.
> Clarify concurrency

- pages/apis/rest_api.md.erb
👋
URLS feels like another Abbreviation, so change to URLs 😅
> URLs read better

- pages/deployments.md.erb
> Allow deploy pipelines in agent hooks

- pages/agent/v2/cli_artifact.md.erb
- pages/agent/v2/cli_pipeline.md.erb
- pages/agent/v3/help/_artifact_download.txt
- pages/agent/v3/help/_artifact_shasum.txt
- pages/agent/v3/help/_pipeline_upload.txt
- pages/agent/v3/help/_step_get.txt
- pages/agent/v3/help/_step_update.txt
- pages/apis/rest_api/builds.md.erb
- pages/tutorials/parallel_builds.md.erb
This changes a few incorrect usages of "it's" to "its".
> Fix minor typos

- pages/agent/v3/osx.md.erb
> Homebrew and remove some trailing spaces

- pages/pipelines/environment_variables.md.erb
These two variables will sometimes be blank, best let folks know
> mention that BUILDKITE_BUILD_AUTHOR and BUILDKITE_BUILD_AUTHOR_EMAIL can be blank

- app/models/page/renderer.rb
- pages/agent/v3/cli_artifact.md.erb
- pages/pipelines/environment_variables.md.erb
- spec/features/reading_pages_spec.rb
- spec/models/page/renderer_spec.rb
Reverts #719, and re-implements #710
> Reintroduce making h3's linkable

- app/views/layouts/application.html.erb
- pages/emoji.md.erb
- pages/pipelines/emoji.md.erb
- vale/Buildkite/spelling.yml
~I find myself in the strange position of needing to escape the colons in the code blocks, because the order the substitutions happen, probably we should figure out where replace text with emoji happens, and tell it not to do it inside code blocks?~
> Add MVP emoji page

- pages/pipelines/controlling_concurrency.md.erb
- vale/vocab.txt
Hey @jayco does this capture what you're describing in https://gist.github.com/jayco/5a96351d7a23f851cc5396a345884e95
> Concurrency gates

- pages/agent/v3/hooks.md.erb
> Clarify hooks

- app/views/quick_reference/_notifications.md.erb
- app/views/quick_reference/_steps.md.erb
> Updated descriptions for sidebar categories

- pages/pipelines/block_step.md.erb
|Before|After|
| <img width="768" alt="スクリーンショット 2020-07-27 14 19 51" src="https://user-images.githubusercontent.com/1000669/88506212-5dcf2000-d014-11ea-8306-1718c7ee158d.png"> | <img width="778" alt="スクリーンショット 2020-07-27 14 19 45" src="https://user-images.githubusercontent.com/1000669/88506209-5b6cc600-d014-11ea-85ba-5df3cb44fb77.png"> |
> Fix block step example link to GitHub

- pages/pipelines/block_step.md.erb
|Before|After|
| <img width="670" alt="スクリーンショット 2020-07-27 14 26 34" src="https://user-images.githubusercontent.com/1000669/88506624-480e2a80-d015-11ea-91d0-493e62d40762.png"> | <img width="680" alt="スクリーンショット 2020-07-27 14 26 20" src="https://user-images.githubusercontent.com/1000669/88506622-47759400-d015-11ea-86ac-b07847f15f8b.png"> |
> Fix a code wrapping in block step doc

- pages/agent/v2/cli_pipeline.md.erb
- pages/agent/v3/cli_pipeline.md.erb
- pages/deployments/deploying_to_kubernetes.md.erb
- pages/pipelines/secrets.md.erb
Was browsing through and felt YAML is better :D
> Use full name for YAML

- pages/pipelines/notifications.md.erb
This PR relates to https://github.com/buildkite/buildkite/pull/5282, the ability to add a custom slack notification message 😀
> Custom slack message

- pages/agent/v2/installation.md.erb
- pages/agent/v2/redhat.md.erb
- pages/agent/v3/installation.md.erb
- pages/agent/v3/redhat.md.erb
- vale/vocab.txt
> Fix spelling of Red Hat

- spec/features/reading_pages_spec.rb
> Add test for /docs/pipelines/my-builds

- pages/apis/rest_api/agents.md.erb
These words were added earlier today in #794
> Adjust wording based on feedback from Sam

- pages/apis/graphql_api.md.erb
> Update GraphQL tutorial link to our blog

- pages/pipelines.md.erb
- pages/pipelines/command_step.md.erb
- pages/pipelines/defining_steps.md.erb
@sj26 pointed out that folks don't always realize that steps can run on different agents. 
This is a small attempt to clarify that.
> Steps may run on difference agents

- pages/pipelines/conditionals.md.erb
One of our customers was bitten by this [today](https://secure.helpscout.net/conversation/1258368214/11765?folderId=1113725) and so I think it might be worth a note in the docs, somewhere. Here's an idea, but I'm not sure I love the words:
> Offer quoting advice for conditionals

- app/views/layouts/application.html.erb
- pages/apis/graphql_tutorial.md.erb
This started as an updated version of https://buildkite.com/blog/getting-started-with-graphql-queries-and-mutations but got bogged down in a lack of variables.
As it stands there isn't much here that isn't also in `pages/apis/graphql_api.md.erb` but might be worth adding anyway. :man_shrugging:
> Add some friendly GraphQL info

- app/views/layouts/application.html.erb
- pages/pipelines/example_pipelines.md.erb
- scripts/list-example-repos.sh
A slightly nicer way to display the example pipelines.
> List some pipeline examples

- pages/pipelines/trigger_step.md.erb
Fixes #798 
Looks, I totally misunderstood the fix, will update.
> Clarify webhook triggered build prmission issues

- pages/pipelines/command_step.md.erb
Minor clarification of what happens when commands fail.
> Clarify failure

- app/models/posthog.rb
- app/views/layouts/_analytics.html.erb
- config/initializers/content_security_policy.rb
- deploy/task-definition-template.json
Adds PostHog tracking. The required environment variable values have already been added.
> Add Posthog

- pages/pipelines/artifacts.md.erb
> Tiny typo fix

- pages/pipelines/block_step.md.erb
> Fix inconsistent label for variable

- vale/Buildkite/spelling.yml
- vale/vocab.txt
> Add these to the good words list

- pages/pipelines/build_meta_data.md.erb
- pages/pipelines/notifications.md.erb
Fixes bug where the comment appears in the text.
> Add spacing between content and comments

- .buildkite/pipeline.yml
- package-lock.json
- package.json
- pages/deployments/deploying_to_heroku.md.erb
- pages/deployments/deploying_to_kubernetes.md.erb
- pages/integrations/build_status_badges.md.erb
- pages/integrations/cc_menu.md.erb
- pages/pipelines/branch_configuration.md.erb
Doesn't look like the major Alex version change is what is causing the Alex linting step to hang. CC @yob 
But the combo of latest alpine and latest Alex might be?
> Update to alex 9

- pages/pipelines/branch_configuration.md.erb
Some updates to the branch configuration docs to demonstrate the changes we're hoping to introduce. We hope this will make branch configurations easier to understand when combining positive and negative patterns.
p.s. please don't merge yet — this is for after https://github.com/buildkite/buildkite/pull/5545
> Strict branch configuration

- pages/pipelines/environment_variables.md.erb
> Document $BUILDKITE_UNBLOCKER_EMAIL

- pages/pipelines/block_step.md.erb
- pages/pipelines/input_step.md.erb
Add the new `blocked_state` attribute and description to the block step table 🌈
> Add blocked builds

- pages/apis/rest_api/pipelines.md.erb
> Clarify PATCH

- pages/pipelines/defining_steps.md.erb
> Escape emoji in pipeline label

- app/models/page.rb
- app/views/layouts/application.html.erb
- spec/features/reading_pages_spec.rb
Thanks for spotting @harrietgrace !
I keep discovering ways this isn't like a static site generator. :-)
> Remove agent brackets in page title

- pages/pipelines/controlling_concurrency.md.erb
- vale/vocab.txt
- update yaml example
- tweak wording
> Match docs to blog post

- pages/apis/graphql_tutorial.md.erb
https://buildkite.com/docs/apis/graphql-tutorial
|Before|After|
| <img width="894" alt="スクリーンショット 2020-12-01 23 52 59" src="https://user-images.githubusercontent.com/1000669/100757110-5344ed00-3431-11eb-8779-1bad4eb998f6.png">|<img width="896" alt="スクリーンショット 2020-12-01 23 59 38" src="https://user-images.githubusercontent.com/1000669/100757123-563fdd80-3431-11eb-8a62-81cd57139032.png"> |
> Update example response so it shows nicely

- pages/pipelines/dependencies.md.erb
This is half a fix for #840 
It doesn't systematically document all the states, but does clarify the specific issue.
> Clarify waiting_failed

- pages/pipelines/dependencies.md.erb
> Document soft fail and allowed dependency failure

- pages/apis/rest_api/pipelines.md.erb
We had a customer let us know that the configuration value was not mentioned in the required payload, this updates that value in two places.
Create pipeline:
Update pipeline:
> Update payload values for API to include configuration

- pages/pipelines/notifications.md.erb
https://docs-review-docs-all-bu-81tto6.herokuapp.com/docs/pipelines/notifications#build-states
> Mention all Build states in Notifications of Pipelines

- app/views/layouts/application.html.erb
- pages/pipelines/archiving_and_deleting_pipelines.md.erb
- pages/pipelines/managing_pipelines.md.erb
- vale/vocab.txt
https://docs-review-docs-pipeli-belw8w.herokuapp.com/docs/pipelines/managing-pipelines
Will be https://buildkite.com/docs/pipelines/managing-pipelines after shipping this.
> Archiving and deleting Pipelines

- pages/pipelines/controlling_concurrency.md.erb
Fixes some typos with the word concurrency.
> Fix typo in concurrency gate

- pages/pipelines/conditionals.md.erb
https://forum.buildkite.community/t/meta-data-in-conditional-clause/1190
> Add a note that conditionals do not support meta data

- app/views/layouts/application.html.erb
Oh hi. First time, long time.
Nothing too fancy. Just adding the PagerDuty docs to the table of contents. LMK if there's anything I missed.
> Adding PagerDuty to side nav ToC

- pages/agent/v3/configuration.md.erb
Fix for https://github.com/buildkite/buildkite/pull/5990/files
> Document PID template in agent name

- pages/apis/webhooks.md.erb
Mention the possibility that the hook can be in a state to the real thing.
> Webhook states

- app/views/layouts/homepage.html.erb
Hey @JuanitoFatas 
I'm not keen on using Documentations, but I think this change captures what you were trying to fix?
> Better title

- app/views/layouts/application.html.erb
- pages/apis/rest_api/meta.md.erb
> List meta endpoint

- pages/apis/rest_api/pipelines.md.erb
Hey @blaknite could you help me out with missing info here please.
CC @JuanitoFatas 
Fix for #931
> Add webhook endpoint

- pages/apis/rest_api/pipelines.md.erb
As added in buildkite/buildkite#6094
> Add "created_by" to the Pipelines API docs

- pages/apis/rest_api/pipelines.md.erb
The response is `201 Created` (no content).
> This endpoint creates webhook for pipeline using GitHub

- pages/agent/v3/help/_annotate.txt
- pages/agent/v3/help/_artifact_shasum.txt
- pages/agent/v3/help/_artifact_upload.txt
- pages/agent/v3/help/_bootstrap.txt
- pages/agent/v3/help/_meta_data_exists.txt
- pages/agent/v3/help/_meta_data_get.txt
- pages/agent/v3/help/_meta_data_set.txt
- pages/agent/v3/help/_pipeline_upload.txt
- pages/agent/v3/help/_start.txt
- vale/vocab.txt
~Looks like we've reverted some doc fixes here.~
Latest docs.
> Bump agent docs to 3.27.0

- pages/pipelines/dependencies.md.erb
> Clarify step keys

- pages/agent/v3/cli_pipeline.md.erb
- pages/agent/v3/cli_start.md.erb
- pages/pipelines/defining_steps.md.erb
- vale/vocab.txt
Context in https://github.com/buildkite/feedback/issues/173#issuecomment-441542660
> Add step default docs

- pages/pipelines/environment_variables.md.erb
- pages/tutorials/parallel_builds.md.erb
Add these two from [Parallel Jobs](https://buildkite.com/docs/tutorials/parallel-builds#parallel-jobs).
https://docs-review-more-buildk-qonyjd.herokuapp.com/docs/pipelines/environment-variables#bk-env-vars-buildkite-parallel-job
> Add parallel job envs

- pages/pipelines/command_step.md.erb
I assume `'*'` does not include 0?
> Clarify retry policy for '*'

- pages/apis/rest_api/pipelines.md.erb
As added in buildkite/buildkite#6234
> Add `archived_at` to pipelines

- pages/apis/webhooks.md.erb
@jayco do you think this is more clear? Or should I elaborate further?
> Slight rewording of webhook token

- pages/apis/rest_api/pipelines.md.erb
This was discovered during implementation of https://github.com/buildkite/terraform-provider-buildkite/pull/123
> Fix supported provider_settings in docs

- config/routes.rb
- pages/apis/graphql_api.md.erb
- pages/apis/rest_api.md.erb
- pages/pipelines/permissions.md.erb
Spotted some double-redirects via ahrefs.com. This fixes them!
> Update old URL REST API docs refs

- pages/agent/v3/help/_bootstrap.md
> Fix rendering of bootstrap docs

- .buildkite/pipeline.deploy.yml
- README.md
- app/helpers/application_helper.rb
- app/models/page.rb
- spec/features/reading_pages_spec.rb
- styleguide/STYLE.md
> Follow up changes of branch renamed to main

- app/models/page/renderer.rb
- pages/agent/v3/help/_annotate.md
- pages/agent/v3/help/_annotation_remove.md
- pages/agent/v3/help/_artifact_download.md
- pages/agent/v3/help/_artifact_shasum.md
- pages/agent/v3/help/_artifact_upload.md
- pages/agent/v3/help/_meta_data_exists.md
- pages/agent/v3/help/_meta_data_get.md
- pages/agent/v3/help/_meta_data_keys.md
- pages/agent/v3/help/_meta_data_set.md
- pages/agent/v3/help/_pipeline_upload.md
- pages/agent/v3/help/_start.md
- pages/agent/v3/help/_step_get.md
- pages/agent/v3/help/_step_update.md
- scripts/cli2md.rb
@toolmantim looks like it might be just the one URL across most files? 
While I was there I noticed this:
which I fixed in f4afcfd
And this issue in https://github.com/buildkite/docs/pull/986
which I fixed in fe094cc
> Fix issues with cli2md

- app/assets/stylesheets/public/_homepage.scss
- app/views/layouts/_sidebar.html.erb
- app/views/pages/index.html.erb
- pages/integrations/repository_management_systems.md.erb
- pages/integrations/source_control.md.erb
@scopegate have a play with this.
~I might rename the ridiculously long repository page, and add it the toc, not 100% sure.~
> Some quick homepage linking

- pages/agent/v3/cli_start.md.erb
Resolves https://trello.com/c/GkxXC0ln/167-docs-for-acquire-job
> Acquire job

- pages/agent/v2/docker.md.erb
- pages/agent/v2/hooks.md.erb
- pages/agent/v3.md.erb
- pages/agent/v3/docker.md.erb
- pages/integrations/sso/adfs.md.erb
- pages/pipelines/block_step.md.erb
- pages/pipelines/build_meta_data.md.erb
- pages/pipelines/command_step.md.erb
- pages/pipelines/input_step.md.erb
- pages/pipelines/managing_log_output.md.erb
- pages/tutorials/docker_containerized_builds.md.erb
@plaindocs I've gone and updated all of these Ps to H3s as we discussed. The CSS was targeting the classname and didn't mention the element type, so didn't even need to update the CSS 👍🏻
> Update docs__note__heading elements from p to h3

- .vale.ini
- pages/agent/v3.md.erb
- pages/agent/v3/configuration.md.erb
- pages/pipelines/environment_variables.md.erb
Take advantage of the new formatting, and add a list and overview.
> Experimental feature list

- app/assets/stylesheets/public/utils/_text_content.scss
|Before|After|
|<img width="1119" alt="CleanShot 2021-04-22 at 16 14 37@2x" src="https://user-images.githubusercontent.com/1000669/115671856-e7363780-a385-11eb-8ae1-8dd2d30f2aee.png"> | <img width="939" alt="CleanShot 2021-04-22 at 16 14 51@2x" src="https://user-images.githubusercontent.com/1000669/115671862-e8fffb00-a385-11eb-9b3a-08ea436330de.png"> |
> Fix table overflow

- pages/apis/rest_api/pipelines.md.erb
- pages/pipelines/permissions.md.erb
There has been quite a bit of confusion about how this works. This might help.
> Clarify pipeline creation

- pages/integrations/pagerduty.md.erb
> Lowercase the pagerduty.com URL

- .buildkite/pipeline.yml
- .vale.ini
- pages/tutorials/elastic_ci_stack_aws.md.erb
Prevent vale from checking gitignores
> Update vale, remove style, check only markdown

- pages/agent/v3/configuration.md.erb
I noticed this while browsing the docs 🙌
> Fix missing </code> block

- pages/agent/v3/securing.md.erb
- vale/vocab.txt
Please take a look at this. I'm not sure that it's the best title for the entry, but it's the closest I could come up with that still made sense.
> Preventive steps for infra compromisation

- pages/apis/rest_api/pipelines.md.erb
- vale/vocab.txt
Implementation here: https://github.com/buildkite/buildkite/pull/6627
> Document the new unarchive pipeline REST API endpoint

- pages/apis/rest_api/agents.md.erb
- pages/pipelines/permissions.md.erb
Clarify how to stop agents using the REST API
> Stop agents

- pages/apis/managing_api_tokens.md.erb
> Fixing outdated section naming (Security->Audit)

- pages/apis/rest_api/jobs.md.erb
> Clarify retries

- app/models/matomo.rb
- app/models/posthog.rb
- app/views/layouts/_analytics.html.erb
- app/views/layouts/application.html.erb
- app/views/layouts/homepage.html.erb
- config/initializers/content_security_policy.rb
- deploy/task-definition-template.json
Historically we've used these for visitor analytics, but not any more
> Remove posthog and matomo

- .github/dependabot.yml
I did this manually in #1139, but we may as well make it automatic 🤷‍♂️
I'm .... 99% confident this will work. It matches the config we have in bk/bk.
> configure dependabot to update the emojis submodule once per month

- pages/pipelines/permissions.md.erb
> Fix typo in Permissions page

- pages/agent/v3/help/_artifact_upload.md
- pages/pipelines/artifacts.md.erb
As per the [Basecamp discussion](https://3.basecamp.com/3453178/buckets/23406985/messages/4063506586#__recording_4088750290), this clarifies our new artifact retention policy in two places.
> Add info on artifact retention

- pages/integrations/sso/azure_ad.md.erb
.. based of feedback from a customer that used the docs to setup SCIM.
> A small tweak to the wording of the Azure AD SCIM docs

- app/views/layouts/_analytics.html.erb
Adds the tracking code for our Google Universal Analytics property
> Add GA Universal tracking ID

- pages/pipelines/environment_variables.md.erb
- BUILDKITE_AGENT_ID description
- Reorder (A-Z)
- Fixed a renamed variable's example to reflect the updated variable's name
> Adding the missing BUILDKITE_AGENT_ID description

- pages/agent/v3/securing.md.erb
This is an attempt to give the tool a slightly more positive spin. The previous version makes it sound like it would be a terrible idea to use it. SEEK use it in production. 
Given that we will eventually take it over, we can afford to be more positive about it. 
Let me know what you think.
> signed pipelines updated

- pages/agent/v3/configuration.md.erb
- pages/pipelines/environment_variables.md.erb
Makes sense to link this up despite it being experimental.
Fixes  #1229
> Add Git mirror env var

- app/assets/stylesheets/public/utils/_text_content.scss
Something like this should work?
> Nested UL formatting

- README.md
Add a note in readme about ruby installation on MacOS
> Update readme about ruby installation on MacOS

- pages/pipelines/group_step.md.erb
- Consistency in quotation marks
- Better naming in examples
- Name --> label
- Removing extra whitespace
> Small improvements for the Group step page

- pages/pipelines/managing_log_output.md.erb
> Add ~~~ info

- .buildkite/pipeline.yml
- .vale.snippets.ini
- pages/integrations/_branch_config_settings.md.erb
- pages/integrations/_build_skipping.md.erb
- pages/integrations/_one_repo_multi_org.md.erb
- pages/integrations/bitbucket.md.erb
- pages/integrations/bitbucket_server.md.erb
- pages/integrations/github.md.erb
- pages/integrations/github_enterprise.md.erb
- pages/integrations/gitlab.md.erb
- vale/Snippets/headings.yml
> Warn about headings in snippets

- pages/pipelines/managing_priorities.md.erb
- Bit explanation of what `dispatch` is
- Add a note on job priority
> Clarification on job priority

- pages/apis/webhooks/agent_events.md.erb
Adds more details about what each event means and how it occurs.
Before:
After:
> Clarify agent events

- pages/pipelines/defining_steps.md.erb
> Talk about dynamic templates

- pages/pipelines/trigger_step.md.erb
> Tiny clarification on pipeline slug

- .buildkite/pipeline.yml
Using https://github.com/codespell-project/codespell 
Fixes #921 (as an alternative)
> Check for common spelling mistakes

- pages/pipelines/block_step.md.erb
> Mention GH status

- pages/pipelines/group_step.md.erb
Adds corrected and simplified examples for group merging in the UI (group step documentation).
> Corrections for the group merging examples

- pages/agent/v3/securing.md.erb
- pages/apis/graphql_api.md.erb
- pages/pipelines/audit_log.md.erb
- pages/pipelines/block_step.md.erb
- pages/pipelines/incoming_webhooks.md.erb
Eliminating the trailing whitespace where the MD linter failed to flag it.
> Eliminating extra whitespace

- styleguide/STYLE.md
Expanding the chapter on snippets in the style guide.
> Extended information about content reuse

- pages/plugins.md.erb
- pages/plugins/directory.md.erb
- pages/plugins/using.md.erb
- pages/plugins/writing.md.erb
WIP
Commit #1:
Adding missing commas, removing extra commas, fixing typos, removing "we" from the tutorial to comply with the style guide.
> Proper handling of unofficial plugins

- app/controllers/quick_reference_controller.rb
- app/views/pages/index.html.erb
- pages/pipelines/command_step.md.erb
- pages/pipelines/managing_priorities.md.erb
- vale/vocab.txt
- I've tweaked the intro and structure
- Added a mention on the homepage
~- Added a line to the quick reference controller ( @ticky is this all that needs to happen on this end?)~
- Added the command step attribute
> Refresh priorities docs

- app/assets/stylesheets/public/_docs.scss
Fixing display error created in https://github.com/buildkite/docs/pull/1306
> Correct hidden text display error for navicon

- pages/agent/v3/hooks.md.erb
...if they end up in a non-executable folder. Follow-up to #1302
Needs tech review.
> Note on troubleshooting Permission Denied error for hooks

- pages/agent/v3/aws/vpc.md.erb
Adds the TOC element to the page.
> Adding TOC to AWS VPC Design page

- pages/pipelines/notifications.md.erb
> Added an example to deliver slack notification when a step is soft failed

- pages/pipelines/_build_states.md.erb
- pages/pipelines/block_step.md.erb
- pages/pipelines/trigger_step.md.erb
@plaindocs this is the right thing to add, but is this a correct place to be adding it?..
> Adding a note on a failed blocked state

- pages/pipelines/environment_variables.md.erb
> Add plugins environment variable

- pages/plugins/using.md.erb
> Added more info about the order of plugin when there are multiple plugins in the same step

- pages/integrations/amazon_eventbridge.md.erb
Added blocked state example request
> added blocked state example request

- pages/pipelines/group_step.md.erb
> Clarify group steps total

- pages/pipelines/group_step.md.erb
Slightly reworded according to https://github.com/buildkite/docs/pull/1336
@plaindocs - please provide a sanity check.
> Reworded group merging section

- README.md
- config/algolia.json
This adds synonyms for things we want to show up in the search index.
> Add synonyms to the config file

- pages/integrations/github.md.erb
I couldn't figure out where this could be linked to on GitHub :(
> Adding a tiny note on repository webhooks

- app/assets/stylesheets/public/_docs.scss
- app/assets/stylesheets/public/_site_header.scss
- app/views/layouts/_sidebar.html.erb
- app/views/layouts/application.html.erb
First crack at this. Still needs the JS
This resolves DOC-224:
https://linear.app/buildkite/issue/DOC-224/search-box
> WIP: First cut of search box in sidebar nav

- pages/agent/v3/tokens.md.erb
> Clarification around organization-id

- .buildkite/pipeline.yml
1. Gather all the linting steps into one group
2. Make the *slow* rspec step depend on the linting group
> Group linting steps

- data/agent_attributes.yaml
- pages/agent/v3/securing.md.erb
If you enable `no-local-hooks`, it will also affect plugins.
> Note on `no-local-hooks`

- app/views/layouts/_sidebar.html.erb
> Move Phabricator to Source Control

- pages/agent/v3/cli_start.md.erb
Added info on multiple tags, and about tags and queues when they are specified together.
> Added details about tags and queues when they are used together and with multiple values

- pages/pipelines/group_step.md.erb
Removes a non-existent limitation.
> Clarification on parallel groups limitations

- .buildkite/pipeline.yml
pullrequest belongs in the argument list, not the path
> Fix codespell

- pages/pipelines/conditionals.md.erb
- pages/pipelines/notifications.md.erb
> Refactor conditionals info

- pages/pipelines/group_step.md.erb
According to the code, the limit is actually 50, not 100
> update job truncation limit value

- app/assets/javascripts/application.js
- app/assets/stylesheets/public/_docs.scss
- app/views/layouts/_sidebar.html.erb
- app/views/layouts/homepage.html.erb
- config/environments/production.rb
This resolves DOC-224:
https://linear.app/buildkite/issue/DOC-224/search-box
> Add `/` as hotkey for search

- pages/pipelines/security_overview.md.erb
- Added link to 2FA tutorial
- Renamed Code review process into Code review and testing process
- Reword the phrase about the way passwords are stored (they are not, only their salted hashes are)
> Clarifications for the Security Overview

- pages/test_analytics/integrations.md.erb
Team Test Analytics got feedback on this section of our docs via a beta particpant Slack channel. Grant and I hopped on a screenshare to offer some clarifications for this section of our documentation.
> Add detail to env var and CI info

- app/assets/stylesheets/public/utils/_text_content.scss
E.g. [this page](https://buildkite.com/docs/test-analytics/integrations#environment-variables):
|Before|After|
| ![CleanShot 2022-04-27 at 17 15 59@2x](https://user-images.githubusercontent.com/1000669/165473959-cdf7e0af-dbba-4da4-b9bb-af968d1348c0.png) | ![CleanShot 2022-04-27 at 17 15 48@2x](https://user-images.githubusercontent.com/1000669/165473955-b3a14aaa-c0c8-435c-8df6-a46c31ddabc2.png) |
> [DOC-307] Add margin to table

- pages/test_analytics/integrations.md.erb
Based on feedback from @blaknite and my scribbly notes -- the proposed changes are more correct.
> Correct variables for RSpec on Buildkite

- pages/integrations/bitbucket_server.md.erb
Says one thing, should say another.
> Fixup switched integration

- pages/apis/graphql_api.md.erb
This is just a stop gap while we get the spec properly documented.
> Add docs on graphql schema

- pages/test_analytics/importing_json.md.erb
- pages/test_analytics/importing_junit_xml.md.erb
Added the info to the only document in TA that mentions the 202 response. @meiqimichelle - is this what we're looking for? Should I add a note to the REST docs, too?
> Adding info on 202 Accepted by REST

- vale/Buildkite/protip.yml
Does what it says on the tin.
There are probably other things we could also add.
> Dont use protip

- pages/agent/v3/hooks.md.erb
- pages/plugins.md.erb
+ apostrophes' fixes
+ (a possible completely erroneous) restructure
> More mentions of vendored plugins

- app/views/layouts/_sidebar.html.erb
- pages/test_analytics/js_collectors.md.erb
This covers the Jest reporter for Test Analytics.
> Add Jest test collector doc

- pages/test_analytics/ci_environments.md.erb
- pages/test_analytics/importing_json.md.erb
- pages/test_analytics/importing_junit_xml.md.erb
- pages/test_analytics/ruby_collectors.md.erb
Quick search and replace across docs to remove an outdated env var name:
~~TEST_ANALYTICS_TOKEN~~
BUILDKITE_ANALYTICS_TOKEN
> Change TEST_ to BUILDKITE_

- app/views/layouts/_sidebar.html.erb
Fix a typo. Langauges -> Languages
> Fix typo in Languages

- pages/test_analytics/swift_collectors.md.erb
Updated docs based on latest README from [buildkite/test-collector-swift](https://github.com/buildkite/test-collector-swift)
> Updated docs for Swift test collector

- pages/test_analytics/js_collectors.md.erb
Fixes a typo in the collector name in the config code snippet.
Excited to test the test analytics!
> Fix typo in js_collectors.md.erb

- README.md
A little meta docs improvement, to follow up from the vale config changes the week before last.
> Document `./scripts/vale.sh` usage

- pages/pipelines/wait_step.md.erb
I had a usecase for this today and went looking for documentation on it. I figured it might be useful for others.
> Add documentation example for conditional wait

- app/assets/stylesheets/public/_nav.scss
- data/nav.yml
> 🐛 Fix sidebar bug

- styleguide/STYLE.md
Add instructions on adding responsive table.
> 📝 Styleguide for responsive table

- pages/test_analytics/importing_json.md.erb
- pages/test_analytics/importing_junit_xml.md.erb
Adding information about the Test Collector plugin.
> Adding info on using plugins to import JSON and JUnit

- app/assets/stylesheets/public/_responsive-table.scss
- app/assets/stylesheets/public/utils/_text_content.scss
- pages/apis/rest_api/pipelines.md.erb
- pages/test_analytics/importing_json.md.erb
- pages/test_analytics/importing_junit_xml.md.erb
Creating a PR for https://github.com/buildkite/docs/pull/1604 to improve how the code blocks appear on the REST API page.
Currently, the code block is difficult to edit to make it readable.
**What's changed:**
- Use `render_markdown` method to use `redcarpet` to render markdown code
- Make all tables on this page responsive tables
- Styling improvements for this page, as well as affected tables
- General html cleanup and remove unnecessary CSS classes for simpler maintainability
This PR has been tested locally on Chrome, Firefox and Safari on macOS Monterey.
**Before**
**After**
**Before:** horizontal scrolling required on small screens
**After**
> 💄 Improve UI design for code blocks within tables on REST API page

- data/nav.yml
> ✏️ "Getting started"

- app/models/page.rb
> Misc small Elastic Stack fixes

- pages/agent/v3/elastic_ci_aws.md.erb
**This PR:** Adds a bunch of info around troubleshooting the elastic stack - notes on what logs get sent where, and how to get into an instance if it's misbehaving.
My wording probably isn't awesome here, feel free to edit as necessary :)
> Add more info on troubleshooting the elastic stack

- data/environment_variables.yaml
Adding information about BUILDKITE_PULL_REQUEST_DRAFT environment variable to the list of env variables. 
@sj26 I have doubts about the example I've provided here. Please take a look.
> Adding BUILDKITE_PULL_REQUEST_DRAFT env var

- pages/pipelines/defining_steps.md.erb
- pages/pipelines/dependencies.md.erb
With uploaded steps entering the frame.
> Adding info about explicit step dependencies

- styleguide/STYLE.md
I need info on what to do if you _did_ commit that vendor\emoji thingie to your working branch. Will revert commit work?
> On vendor\emojis submodule update

- Dockerfile
- docker-compose.production.yml
Same as #1637 except this works in local Docker
> Production ENV VARs in Docker

- pages/test_analytics/ci_environments.md.erb
Update the docs to respect changes in
https://github.com/buildkite/test-collector-ruby/pull/136
> Update TA docs GITHUB_REF -> GITHUB_REF_NAME

- pages/pipelines/build_meta_data.md.erb
- pages/pipelines/secrets.md.erb
Fixing some visual abominations and 1 H2 with faulty capitalization.
> Fixes 2 ugly links and one H2 (Quick Fix Thursday)

- pages/pipelines/managing_priorities.md.erb
Nice one @jradtilbrook and @sj26  !
> Default priority is shipped

- CODE_OF_CONDUCT.md
To match the other Buildkite repositories.
> Add Contributor Covenant v2.1.

- pages/test_analytics/swift_collectors.md.erb
New release, hot off the presses: https://github.com/buildkite/test-collector-swift/releases/tag/v0.3.0
I've also got a note from the dev team that "it might be worth including the steps specifically for Xcode from the README" -- if anyone's got time to compare-contrast-update, that would be amaze 🤩 but also -- it is good to just get this version bump out!
> Version bump!

- pages/agent/v3/macos.md.erb
- vale/styles/Buildkite/h2-h6_sentence_case.yml
This could definitely use some better wording, but the main idea here is to make sure we note about the path changes present in M1 installations of Homebrew.
> add note about M1 chips and homebrew path changes

- pages/test_analytics/swift_collectors.md.erb
https://github.com/buildkite/docs/pull/1661#pullrequestreview-1049497187 was a post-merge review; this PR expands on those changes a little.
> Make Swift collector doc more consistent with other collectors

- styleguide/yaml.md
Follow up for https://github.com/buildkite/docs/pull/1518#issuecomment-1195436281.
> Revise YAML style guidance with better and more examples

- pages/agent/v3.md.erb
I'm trying to address this feedback a little
> This is a whole lot of "how it works that is written under the assumption that I know what to do with it. I'm just confused."
> Be more helpful when talking about the agent

- pages/test_analytics/swift_collectors.md.erb
> Fix the indenting/numbering

- pages/apis/api_differences.md.erb
> Adding info on granular access permissions in REST

- pages/apis/rest_api/builds.md.erb
> Fix link in REST API - Builds page

- pages/test_analytics/ruby_collectors.md.erb
Relevant issue: https://github.com/buildkite/test-collector-ruby/issues/123
> Mention issue and solution

- pages/test_analytics/javascript_collectors.md.erb
PIE-1005
Followed the same structure as https://github.com/buildkite/docs/pull/1681
Related to https://github.com/buildkite/test-collector-javascript/issues/36
> Add troubleshooting information regarding --forceExit to JS/Jest collector 

- app/assets/javascripts/nav.js
- app/assets/stylesheets/public/_homepage.scss
- app/assets/stylesheets/public/_page_container.scss
- app/assets/stylesheets/public/_variables.scss
- app/assets/stylesheets/public/utils/_text_content.scss
- app/views/layouts/_nav.html.erb
- app/views/layouts/_site_header.html.erb
- app/views/pages/index.html.erb
I've decided to set a max-width for the entire Docs site to address UX issues of:
- Inconsistent text lengths
- Optimizing the reading lengths of every line of text
- Far distance between elements on very large screens
Inconsistent text lengths 👆
Fluid design creates too much white space and distance between elements.
To address this _holistically_ I've applied a max-width of `1536px` for the entire site (optimized for the common laptop screens). Beyond this width the components stop 'stretching' horizontally. This has the benefits of:
- Better control over content width
- Reduce eye tracking and mouse movement distance
- Better visual appearance
Standard laptop screen ☝️ 
Standard desktop screen ☝️ 
Very large desktop screen ☝️ 
1. Removed `max-width` for paragraph texts (supplanted by …
> 💄 Holistic fix for page wrapping issue

- .buildkite/pipeline.yml
Caught out by
https://buildkite.com/docs/test-analytics/ci-environments#containers-and-test-collectors
> Pass environment variables to Docker

- spec/rails_helper.rb
This one was on me. But the environment variables does run now.
> Oops, dont put this inside config

- scripts/emojicom-processed-ratings.txt
This system isn't ideal, but it's what we have.
> More feedback

- pages/pipelines/managing_log_output.md.erb
Support will handle the comms for these requests :)
> Update mail of contact to support

- data/tiles.yml
- pages/test_analytics/monitors.md.erb
- pages/test_analytics/test_suites.md.erb
- Adds notes of temporary unavailability for TA monitors and alerts.
> Notes of unavailability for Monitors in TA

- pages/apis/agent_api.md.erb
* Use more straightforward wording
* I'm leaving the API token instructions untouched as I'm trying to avoid folks using the API Access token.
> Minor edits to the Agent API

- pages/pipelines/notifications.md.erb
Related to https://github.com/buildkite/docs/issues/1724
> Clarify when you can use step notifications

- pages/agent/v3/hooks.md.erb
Corrected "...speeds up a fresh..." to "spins"
> Typo in hooks.md

- app/views/layouts/application.html.erb
- docker-compose.production.yml
Same as https://github.com/buildkite/docs/pull/1637 Just confirming that this works.
Will clean up afterwords
> Test docker-compose set variables

- Dockerfile
- Dockerfile.render
- docker-compose.production.yml
- docker-compose.yml
Here's a different test for ENV VARs, based on #1638 
Still addressing ONB-29
> Testing ENV VARs in Render and PROD via Dockerfiles

- config/initializers/content_security_policy.rb
Ref: https://segment.com/docs/connections/sources/catalog/libraries/website/javascript/upgrade-to-ajs2/#using-a-strict-content-security-policy-on-the-page
Linear: https://linear.app/buildkite/issue/ONB-29/🔗-integrate-docs-with-segment
Fixes #ONB-29
> Allow Segment's main analytics.min.js script [wip]

- pages/agent/v3/macos.md.erb
After a few trial runs, I'm finally ready to have this huge contribution merged.
> Add a missing etc, for real this time

- app/views/pages/index.html.erb
- data/content/agent_attributes.yaml
- pages/agent/v3/aws/vpc.md.erb
- pages/apis/graphql_api.md.erb
- pages/apis/managing_api_tokens.md.erb
- pages/pipelines/artifacts.md.erb
- pages/pipelines/block_step.md.erb
- pages/pipelines/build_matrix.md.erb
- pages/pipelines/build_retention.md.erb
- pages/pipelines/defining_steps.md.erb
- pages/pipelines/environment_variables.md.erb
- pages/pipelines/public_pipelines.md.erb
There should be no semantic changes.
> Fix small issues I noticed while auditing the docs

- app/assets/stylesheets/public/_copy-to-clipboard-button.scss
- app/assets/stylesheets/public/utils/_button.scss
Minor fix for button style when displayed over content.
https://user-images.githubusercontent.com/656826/217972334-d0a512e7-28e8-431f-8dee-b671f9279830.mov
> Fix button background on "Copied" state

- .github/labeler.yml
Add some additional labels and rename `apis` -> `api`.
> Add a few more PR labels

- .buildkite/update_graphql_docs
Remove one more button press when releasing automated PRs like the following https://github.com/buildkite/docs/pull/1861.
> Auto-merge generated GraphQL PRs

- pages/deployments/deploying_to_heroku.md.erb
Escape double quotes from the environment variable, otherwise, it will throw an error.
> Update yml examples

- app/assets/stylesheets/base/_fonts.scss
- app/assets/stylesheets/base/_variables.scss
- app/views/application/_head.html.erb
This PR updates docs to use a working "Maison Neue" font and updates the content styles to use this font.
> Use "Maison Neue" font for content

- pages/agent/v2/gcloud.md
- pages/agent/v3/gcloud.md
It looks like there's been a redirect in place for these pages, which has just been removed. I verified these through https://web.archive.org/
> Fix k8s links

- pages/test_analytics/javascript_collectors.md
- vale/styles/vocab.txt
> Document support for Jasmine and Mocha in JS Collector

- app/views/application/_helpscout.html.erb
Use revised Help Scout Beacon ID and initialise for all users.
> [ONB-197] Update Help Scout Beacon ID

- app/assets/javascripts/application.js
- app/assets/javascripts/nav.js
- app/assets/javascripts/toc.js
- app/views/layouts/application.html.erb
- app/views/layouts/graphql.html.erb
- app/views/layouts/landing_page.html.erb
> Render table of contents on GraphQL pages

- pages/test_analytics/importing_junit_xml.md
> Fix typo - add missing 's'

- data/nav.yml
- pages/pipelines/archiving_and_deleting_pipelines.md
[Previously live](https://web.archive.org/web/20210330194207/https://buildkite.com/docs/pipelines/archiving-and-deleting-pipelines)
> DOCS-573: Add archiving deleting to nav

- data/nav.yml
- pages/pipelines/archiving_and_deleting_pipelines.md
[Discussed on Basecamp](https://3.basecamp.com/3453178/buckets/23328660/chats/3993480919@5949857898)
> DOCS-573: Add Teams API to nav

- data/tiles.yml
- pages/test_analytics/test_suites.md
Adding docs for the Test Analytics flaky test tracking that's currently in private beta.
This is a combination of words from both @meiqimichelle and @swebb. Please let me know what feedback you have since I am lacking technical writing experience 🙇 
[Linear ticket](https://linear.app/buildkite/issue/PIE-1367/flaky-test-tracker-feature-documentation)
> [PIE-1367] TA flaky test tracker docs

- pages/agent/clusters.md
Addressing all the feedback from #1960. Thank you for going into this so deeply, @mbelton-buildkite!
> Improve clusters docs

- pages/pipelines/trigger_step.md
> removed incorrect command attribute for trigger job

- pages/integrations/sso.md
Trying to add some more helpful information for those who mightn't know what JIT is.
> Yes, we do. isn't helpful.

- pages/pipelines/build_export.md
- vale/styles/vocab.txt
Information and instructions re. preparing (Enterprise) customer-owner S3 bucket ready for the upcoming Build Export feature.
> Export build data: Preparing your S3 bucket

- data/nav_graphql.yml
- scripts/graphql_api_content/nav_data.rb
- spec/scripts/graphql_api_content/nav_data_spec.rb
I'd removed the "Schema browser" label and moved the Cookbook page previously...but I made the changes directly to the nav file. I noticed things had gone back to before and realized the nav file is generated when the GraphQL script runs. This change moves those updates into the script and generates the nav file from that.
> Fix GraphQL script IA

- app/controllers/application_controller.rb
- app/controllers/pages_controller.rb
- config/initializers/nav.rb
- data/nav.yml
- data/nav_graphql.yml
- scripts/generate_graphql_api_content.rb
- scripts/graphql_api_content/nav_data.rb
- spec/scripts/graphql_api_content/nav_data_spec.rb
No more nav switching. It's all the same nav!
> Consolidate GraphQL nav into regular nav

- pages/agent/v3/cli_env.md
Through this PR we are adding information about how to set experiment flag for job-api to be available
> add info about how to set experiment flag

- pages/apis/rest_api.md
Reverts buildkite/docs#2037
[Context](https://3.basecamp.com/3453178/buckets/28474015/chats/5132790929@6091660298)
> Revert "DOCS-561 Add URL Query Param auth method for rest API"

- pages/integrations/github.md
Add a note to explain the behavior on how builds are triggered when we have an open PR and a commit is pushed to the branch associated with the PR.
> Commit push to branch with PR

- app/views/application/_nav_children.html.erb
Keep the arrow showing as expanded on page load.
https://user-images.githubusercontent.com/656826/236391623-57cea48b-8072-4a58-bc23-9f308b086aa6.mov
> Preserve state for sidebar expanded arrow 

- app/frontend/components/toc.js
There's an error on the homepage that's caused by the table of contents JS not finding an element.
> Fix JS error on home page

- .gitignore
- Dockerfile
- Gemfile
- Gemfile.lock
- app/models/page.rb
- config/sitemap.rb
- docker-compose.production.yml
Add configuration to generate sitemap for /docs.
TODO:
> Generate sitemap

- pages/tutorials/migrating_from_bamboo.md
This change updates and fixes many of the style issues with the Bamboo page, but does not change the meaning of the content. It also removes the mention of Bamboo Cloud, [which is no longer a product](https://community.atlassian.com/t5/Bamboo-questions/Forced-migration-to-cloud-What-about-Bamboo/qaq-p/1510512).
> General style update to Bamboo migration guide

- pages/integrations/sso/azure_ad.md
- pages/integrations/sso/okta.md
This is an automatically enabled feature now for enterprise customers and we no longer have to enable this manually, unless it's a custom provider
> Change note about okta/azuread scim being avail for enterprise

- pages/apis/rest_api/clusters.md
Add docs for https://github.com/buildkite/buildkite/pull/12365 which implements creating, updating and deleting clusters with the REST API. This should be merged once the API implementation is deployed.
Preview docs: https://bk-docs-pr-2148.onrender.com/docs/apis/rest-api/clusters
> add documentation for creating, updating and deleting clusters with the REST API

- pages/agent/v3/hooks.md
Addressing feedback from [GitHub issue 2145](https://github.com/buildkite/docs/issues/2145).
> Fix link to agent lifecycle hooks

- .buildkite/build-static
- .buildkite/pipeline.preview.yml
- .gitignore
- Dockerfile
- app/helpers/application_helper.rb
- app/helpers/tiles_helper.rb
- app/models/page.rb
- app/views/application/_brand.html.erb
- app/views/application/_footer.html.erb
- app/views/application/_head.html.erb
- app/views/application/_home_header.html.erb
- app/views/homepage/_popular_guides.html.erb
- app/views/homepage/_products.html.erb
- bin/deploy-preview
- data/tiles.schema.yml
- data/tiles.yml
- package.json
- spec/helpers/application_helper_spec.rb
- spec/helpers/tile_helper_spec.rb
- static.json
- yarn.lock
Render is costing a lot for what it does. 
This PR adds an alternative preview URL solution by instead generating a static site and using Netlify for managing previews.
> Generate preview URLs using Netlify

- pages/apis/graphql/graphql_cookbook.md
Add an example query for searching agents with a prefix within in an org in cookbook
> example for searching agent with in an org

- pages/apis/rest_api/clusters.md
- pages/apis/rest_api/pipelines.md
* Document the `cluster_id` property on the Pipelines API page
* ~Document how to add pipelines to a cluster on the Clusters API page, and link to Pipelines API~
Closes EDGE-984.
> document adding pipelines to a cluster

- pages/apis/rest_api/clusters.md
Add docs for https://github.com/buildkite/buildkite/pull/12471
> add docs for creating, update and deleting cluster queues with REST API

- pages/apis/rest_api/analytics/suites.md
Description
Documentation about Test Analytics rest api endpoint Suites#Show
Linear: https://linear.app/buildkite/issue/PIE-1705/rest-api-endpoints-documentation-suiteindex
> suites#index Test Analytics REST API documentation

- pages/apis/rest_api/analytics/suites.md
https://linear.app/buildkite/issue/PIE-1775/add-api-documentation-for-suitescreate
> TA suites#create rest api endpoint

- pages/agent/v3/hooks.md
- vale/styles/vocab.txt
We shipped polyglot hooks fairly recently, which allowed agents to run hooks written in any language. This PR documents that feature, including many of its caveats.
> Polyglot hooks docs

- pages/agent/v3/hooks.md
The hooks page was updated to introduce polyglot hooks in #2136 but I didn't have a chance to review it. This change suggests fixes for the main style issues found on the page.
> Fix polyglot hooks writing style

- pages/apis/managing_api_tokens.md
We've recently added the ability for organization's to revoke inactive tokens once they have been inactive for a certain period of time.
- [Project Page](https://3.basecamp.com/3453178/buckets/1933834/messages/6096559452)
- [Coda](https://coda.io/d/Buildkite-Roadmap_dUWyuyLHsQw/Marketing-Release-Train_su-L0#June-Release_tuTsj/r133&view=modal)
> Update "managing API tokens" to include automatic inactive token expiry

- pages/apis/managing_api_tokens.md
> Revoking inactive tokens automatically is Enterprise feature

- pages/agent/v3/help/_lock_acquire.md
- pages/agent/v3/help/_lock_do.md
- pages/agent/v3/help/_lock_done.md
- pages/agent/v3/help/_lock_get.md
- pages/agent/v3/help/_lock_release.md
- pages/tutorials/parallel_builds.md
To reflect a fix that went into the latest agent release.
> Store and use the token

- pages/agent/v3/_linux_multiple_agents.md
- pages/agent/v3/debian.md
- pages/agent/v3/redhat.md
- pages/agent/v3/ubuntu.md
... on Debian, Red Hat, and Ubuntu docs.
> Use `spawn` for multiple agents

- pages/pipelines/permissions.md
Added info about rebuild permissions in pipelines.
Added info around code level permission levels
> Added info about rebuild permissions

- pages/pipelines/incoming_webhooks.md
@HugeIRL raised this [in an internal chat](https://3.basecamp.com/3453178/buckets/28474015/chats/5132790929@6397141144) so I've made an attempt to clarify the situation. Feel free to make it better :)
> Clarify who manages the IP filtering

- app/assets/stylesheets/base/_article.scss
- app/assets/stylesheets/components/_page.scss
- app/assets/stylesheets/components/_pill.scss
A couple minor style updates to some pages that looked broken
| Before | After |
| --- | --- |
| <img width="1624" alt="Screenshot 2023-07-31 at 2 40 29 pm" src="https://github.com/buildkite/docs/assets/656826/08f207d8-7980-4584-8831-5ae9bd2468f8"> | <img width="1624" alt="Screenshot 2023-07-31 at 2 40 47 pm" src="https://github.com/buildkite/docs/assets/656826/37193e37-d440-4c19-b1e2-c33cff385cb8"> |
|  <img width="1624" alt="Screenshot 2023-07-31 at 2 40 33 pm" src="https://github.com/buildkite/docs/assets/656826/df96f998-4301-4f46-ab19-2dcfea97ca7c"> | <img width="1624" alt="Screenshot 2023-07-31 at 2 40 44 pm" src="https://github.com/buildkite/docs/assets/656826/e7978491-7c4c-45ef-8a03-6f8663217012"> |
> Minor fixes for GraphQL pages

- pages/pipelines/migrate_from_jenkins.md
https://buildkite.com/blog/buildkite-or-jenkins-choosing-the-right-tool-for-you
> Incorporate style changes from the blog

- data/nav.yml
- pages/pipelines/permissions.md
- pages/test_analytics/permissions.md
Context: https://linear.app/buildkite/issue/ONB-315/duplicate-title-on-permissions-pages
No URL changes.
> Update page titles to avoid duplication for SEO

- data/content/aws-stack.yml
Several parameters changed for v6 but looks like I forgot to update the template 😅
> Update Elastic CI Stack template to v6.3.0

- data/content/environment_variables.yaml
> Fix typo in environment variable

- .buildkite/update_graphql_docs
Quick follow up from https://github.com/buildkite/docs/pull/2398 to fix the schema sync script.
> Update GraphQL script to check definition file

- pages/apis/webhooks.md
Small pluralisation fix for the Webhooks callout note.
> Fix pluralisation on webhooks callout

- app/views/application/_site_header.html.erb
- config/algolia.json
My regex wasn't quite right in https://github.com/buildkite/docs/pull/2417 and after playing around some more I'm just going to remove the link.
> Remove skip to content link

- app/assets/stylesheets/components/docsearch/button.scss
- app/assets/stylesheets/components/docsearch/modal.scss
- app/frontend/components/toc.js
Steal some styles from @BrettJay's visual refinement. 
https://github.com/buildkite/docs/assets/656826/47158c6c-1f98-4448-adad-53276a28df0d
> Style search button

- pages/pipelines/build_matrix.md
A long-overdue upd following https://secure.helpscout.net/conversation/2306810185/54487/
Discussed and approved by @jeremybumsted
> UPD about concurrency groups

- app/frontend/css/components/_callout.scss
- app/frontend/css/pages/_docs.scss
Missed a couple images in https://github.com/buildkite/docs/pull/2086.
> Fix broken hover anchor image

- pages/pipelines/create_your_own.md
This question popped up several times so I decided to add this to the docs. If you can think of other places where this could be added, feel free to turn it into a snippet and propagate.
> Add a note on inviting users

- pages/integrations/sso.md
As a follow-up for a ticket that required info that was known, but wasn't reflected in the docs. Fixing it with this PR.
> Expanding the SSO FAQ

- .buildkite/pipeline.deploy.yml
Use deploy queue when running ECR scan results step.
> Run ecr scan results step on deploy queue

- data/content/aws-stack.yml
This is used to generated the documentation for the template parameters.
> Update template for Elastic CI Stack v6.8.0

- CODEOWNERS
This reverts commit 5d33aa545d865d5241b3d27ea2fc63adbaa7c8c4.
> Revert "Add Mel and Michelle as codeowners"

- .buildkite/pipeline.preview.yml
- bin/prepare-preview
I found this plugin and thought I'd have a play with it.
https://github.com/ailohq/github-deployment-buildkite-plugin
> Use Github deployment API via plugin

- .buildkite/push-image.sh
- Dockerfile
- bin/deploy-preview
Switch our Dockerfile to use a multi-stage build in an effort to reduce image size, maybe improve builds times, and hopefully reduce the potential number of CVEs. 
Image size has shrunk from ~1.56GB 👉 700MB.
> Multi stage build

- bin/utils.sh
Fix up the curl request added in https://github.com/buildkite/docs/pull/2563
> Fix curl request for creating a pull request

- pages/apis/rest_api/builds.md
Linear: https://linear.app/buildkite/issue/PDP-1930/expose-step-id-in-rest-api-builds
Updated  the Build API docs to reflect 2 new attributes 
```
"jobs": [
{
"id": "b63254c0-3271-4a98-8270-7cfbd6c2f14e",
"graphql_id": "Sm9iLS0tMTQ4YWQ0MzgtM2E2My00YWIxLWIzMjItNzIxM2Y3YzJhMWFi",
"type": "script",
"name": "📦",
"step_key": "package",
"step": {
"id": "018c0f56-c87c-47e9-95ee-aa47397b4496",
"signature": {
"value": "eyJhbGciOiJFUzI1NiIsImtpZCI6InlvdSBzbHkgZG9nISB5b3UgY2F1Z2h0IG1lIG1vbm9sb2d1aW5nISJ9..gcmV8TgY6MfAXRbD_7kyuB3JAQMH-0th5E1MmQn5ND34bEs-zNBZ3tLi6w2e_gvfqL6C1kxRhOQzAwEZMQlo5w",
"algorithm": "HS512",
"signed_fields": [
"command",
"env",
"matrix",
"plugins",
"repository_url"
]
}
},
```
> update API docs to reflect new step attributes

- pages/agent/v3/elastic_ci_aws/troubleshooting.md
Add a troubleshooting section on spot instance reclamation in the elastic stack
> Add section describe spot instance reclamation

- .buildkite/pipeline.deploy.yml
See https://github.com/buildkite/buildkite/pull/15031
> Ignore CVE-2023-50495

- pages/plugins/using.md
A bit of nit-picking, but even I, for a second, wondered - "organization? Buildkite or GitHub?". For the first-time travelers into the Plugin-land - let's put a benevolent repetition here.
> Clarification regarding the organization's origin

- .buildkite/pipeline.deploy.yml
See [buildkite/buildkite](https://github.com/buildkite/buildkite/pull/15366). This looks to be how we've handled this before.
FYI @dannymidnight when you're back from leave.
> Ignore CVE-2024-0567

- CODEOWNERS
Since I (@gilesgas) will be making significant contributions to the `docs` repo, as well as reviewing other contributors' PRs, it makes sense to add me to the CODEOWNERS list.
> Add Giles (GitHub 'gilesgas' account) to the Buildkite CODEOWNERS list.

- pages/apis/graphql/cookbooks/agents.md
Add graphql queries for stoping an agent
> Add graphql queries for stoping an agent

- .buildkite/pipeline.deploy.yml
Following on from [buildkite/buildkite PR #15823](https://github.com/buildkite/buildkite/pull/15823), implement the same here.
> Ignore CVE-2024-0553 and CVE-2024-0567

- .buildkite/pipeline.deploy.yml
Fix the role name to match https://github.com/buildkite/ops/pull/2137
> Fix oidc role name

- pages/packages.md
- pages/tutorials/github_actions.md
Related to:
- https://github.com/buildkite/docs/pull/2502
- Buildlkite Pages link to product page.
> Minor wording improvements

- pages/agent/v3/cli_oidc.md
> docs: link to RFC for JWTs

- pages/integrations/sso.md
Update plans that have SSO available.
aligns with pricing:
> SSO is available on Pro and Enterprise plans

- .buildkite/pipeline.yml
We're experimenting with a new queue and docs feels like an excellent place to experiment. There's quite a few steps, and there's a chance we'll get a speed up.
Safe to revert if there's any surprises, the goal isn't to get in the way of other work!
> change to hosted queue

- pages/packages.md
- pages/packages/_javascript_registry_name.md
- pages/packages/_javascript_registry_read_token.md
- pages/packages/_javascript_registry_write_token.md
- pages/packages/_ruby_registry_write_token.md
- pages/packages/getting_started.md
- pages/packages/javascript.md
- pages/packages/permissions.md
- pages/packages/python.md
- pages/packages/ruby.md
- pages/packages/terraform.md
- pages/team_management/permissions.md
- pages/test_analytics/permissions.md
- vale/styles/Buildkite/h1-h6_sentence_case.yml
This PR is for the last chunk of work I forgot to commit before merging in https://github.com/buildkite/docs/pull/2803
> Packages beta subsequent updates

- pages/agent/v3/cli_artifact.md
As per title. A tiny addition as a result of responding to a ticket.
> Hard limit for S3 artifact upload size

- pages/apis/rest_api.md
Based on feedback from this issue: https://github.com/buildkite/docs/issues/2849
> Update the 'curl' command response to the base REST API endpoint.

- app/models/beta_pages.rb
- data/nav.yml
- pages/packages.md
- pages/packages/permissions.md
And remove beta callout near top of landing page.
> Remove beta pills from Buildkite Packages docs.

- pages/packages/alpine.md
- pages/packages/container.md
- pages/packages/debian.md
- pages/packages/getting_started.md
- pages/packages/gradle.md
- pages/packages/javascript.md
- pages/packages/manage_registries.md
- pages/packages/maven.md
- pages/packages/private_storage.md
- pages/packages/python.md
- pages/packages/red_hat.md
- pages/packages/ruby.md
- pages/packages/terraform.md
- pages/pipelines/hosted_agents/code_access.md
- pages/team_management/permissions.md
Hi, just some minor tweaks/suggestions for https://github.com/buildkite/docs/pull/2865
Feel free to incorporate some/all/none and close/merge the PR as you please:
- `run` in a terminal instead of `submit`.
- Converge on "API access token" instead of "API write token".
- Minor code whitespaces
- Remove repeated "as required" in some sentences.
- `performed` instead of `conducted` when describing steps/processes being done
> Minor suggestions

- pages/pipelines/hosted_agents/mac.md
- Update Hosted Agent Mac Instance Software list to include supported Xcode versions and builds
> docs: update xcode versions and builds

- pages/tutorials/github_merge_queue.md
Just adding a clarification for when you need to add an extra branch filter pattern, because for most people it won't be necessary.
> add clarification about merge queues

- pages/agent/v3/elastic_ci_aws.md
> Update agent version in AWS stack

- pages/pipelines/hosted_agents/mac.md
Update Xcode and runtime versions now available on hosted agents mac instance image
> docs: update mac instance software

- pages/apis/rest_api/teams/pipelines.md
Fixing list_pipelines API response description,
Example response below,
{
"access_level": "build_and_read",
"created_at": "2024-07-31T06:21:25.526Z",
"pipeline_id": "018e9d13-ff7f-456d-ad3b-4f68d0741eb6",
"pipeline_url": "https://api.buildkite.com/v2/organizations/priya/pipelines/api_test"
},
> SUP-2512 | Update pipelines.md

- pages/pipelines/security/secrets/managing.md
add the correct path do the env file, like it is described in the plugin https://github.com/buildkite/elastic-ci-stack-s3-secrets-hooks.
> fixing the path to env file

- pages/pipelines/notifications.md
> Update the documentation regarding which types of notifications can be configured at each level: Build vs. Step

- pages/integrations/sso.md
Simple spelling change + emoji submodule bump.
> Fix spelling of Organization

- pages/cli.md
Add some recent commands from the CLI to the help menu in the docs
@jradtilbrook
> Add new top level commands to output

- pages/apis/rest_api/packages/registries.md
> [PKG-7407] - API docs for registries show

- pages/apis/rest_api/packages/registries.md
Needs registries update to be merged first: https://github.com/buildkite/docs/pull/2969
> [PKG-7405] API docs for registries destroy

- pages/agent/v3/macos.md
> Remove unnecessary `brew tap` command

- pages/pipelines/configure/step_types/wait_step.md
> Add "branches" to wait step

- pages/test_engine/python_collectors.md
Just a small typo I noticed while setting this up.
> Fixup python extras command
