buildkite/docs

- pages/guides/environment_variables.md.erb
The docs say that it has a value of `true` when building a pull request, but it actually contains the pull request number.
> Fix documentation about BUILDKITE_PULL_REQUEST

- pages/agent/installation.md.erb
Previous link incorrectly pointed to debian, renamed Mac to Mac OS X for consistency with name in side panel.
> Fix link for Mac OS X installation documentation

- pages/guides/uploading_pipelines.md.erb
Previously the docs indicated that an uploaded pipeline step could have a field "label" to set the step's name, but in fact the expected field name is "name".
> Correct field name for job name in uploaded steps

- pages/api.md.erb
I've also updated the CodePen code to be jQuery-less, and uses Github's window.fetch polyfill
> Add CORS info to API overview

- pages/guides/deploying_to_heroku.md.erb
Currently if you Google "buildkite heroku deploy" this is all you get:
This adds a guide based on me setting it up for Carla’s Learn Brush Lettering
> Add a Heroku deployment guide

- pages/api.md.erb
- pages/api/access_tokens.md.erb
- pages/api/agents.md.erb
- pages/api/builds.md.erb
- pages/api/jobs.md.erb
- pages/api/pipelines.md.erb
- pages/guides/uploading_pipelines.md.erb
There has been a little confusion around how to supply parameters to requests, so let's clarify!
I've also renamed "properties" to "parameters". `http://.../builds?state=passed` has a parameter to me, not a property. Parameters seem like a superset of properties. Thoughts?
/cc @keithpitt
> Parameter clarification

- pages/agent/build_artifacts.md.erb
- pages/guides/artifacts.md.erb
It can be a little confusing because you think you might be able to use the `buildkite-agent artifact download` command outside of a running build. This is just to have a presence on the other pages to point peeps in the right direction.
> Links on how to download artifacts outside of a running build

- pages/agent/build_pipelines.md.erb
- pages/guides/uploading_pipelines.md.erb
This splits up the pipelines documentation into two documents. One is a guide, that provides more general advice and complete examples. One is the technical docs in the agent section alongside the artifact and meta data command, and it covers the example properties that you can use to configure the pipelines.
> Improved the pipeline documentation

- pages/guides/build_status_badges.md.erb
Adds documentation for the new `style` parameter for badges.
> Document badge styles

- pages/agent/securing.md.erb
In this example, to only allow the `script/deploy` command to run, it should be `!=` instead of `==`.
> Fix: change equals to not-equals sign

- pages/agent/build_artifacts.md.erb
Uploading artifacts requires the `ListBucket` S3 permission.
> Update example S3 policy

- pages/guides/controlling_concurrency.md.erb
We don't have any guide on how to control concurrency, and @sj26 wanted to link to one from the Terraform article he's writing. So this adds a basic one that at least tells people that it's organisation wide, the syntax to use, and an example.
> Add a guide on concurrency

- pages/guides/elastic_ci_stack_aws.md.erb
The queue is now "default" on the stack to help reduce confusion when getting up and running. This updates the guide to match.
Also I've updated the [Elastic CI Stack 1.1 release](https://github.com/buildkite/elastic-ci-stack-for-aws/releases/tag/v1.1) with a note to say the default queue name has changed.
> Queue is now "default" for Elastic Stack

- pages/agent/build_pipelines.md.erb
I noticed inconsistencies in the words we use to describe the pipeline.yml syntax.
This fixes references to "keys" instead of "properties", and other small inconsistencies in the step type docs
> Improve pipeline docs consistency

- pages/agent/_apt_locations.md.erb
I'm not positive if this is the default file location for builds across all Linux distributions, but it was certainly the case for Ubuntu:
```
ubuntu@ciders:/var/lib/buildkite-agent$ buildkite-agent -v
buildkite-agent version 2.3, build 1382
ubuntu@ciders:/var/lib/buildkite-agent$ ls
builds
```
Any feedback is appreciated.
> Update Build Location for buildkite-agent

- pages/builds/managing_log_output.md.erb
From this issue https://github.com/buildkite/frontend/issues/132 - fixing up the emoji escaping in the docs so that it looks correct inside a rendered code block.
> Properly escape emoji in code block

- pages/agent/configuration.md.erb
See https://github.com/buildkite/agent/blob/master/clicommand/agent_start.go#L116-L124
> Agent actually supports EC2 config as env vars

- pages/pipelines/pipelines.md.erb
The docs were not updated alongside buildkite/buildkite#1847, this updates them to reflect the changes and the discussion therein.
> Update docs for the recent pipeline status tweak

- pages/quickstart/getting_started.md.erb
Since the my builds email popup is now live, we don't really need this section anymore. Also the image was broken 😅
> Remove section about linking your git email

- pages/agent/securing.md.erb
This updates our security recommendations to:
* Use an `environment` hook instead of a `pre-command` hook for whitelisting. An environment hook is better because it runs before any local or plugin hooks can be executed.
* Mention providing a custom bootstrap executable
* Add a note that auto SSH key verification and command whitelisting does not protect from malicious source code
> Update recommendations for securing the agent

- pages/pipelines/command_step.md.erb
- pages/pipelines/trigger_step.md.erb
A question about trigger builds from builds came up in Slack today, and I noticed there wasn't any documentation on trigger steps.
I've added a brief page based on https://github.com/buildkite/agent-tests/blob/master/tests/trigger-pipeline/.buildkite/pipeline.yml .
> Add documentation for trigger steps

- pages/agent/aws.md.erb
✨
Fix for https://github.com/buildkite/docs/issues/104
> Fix typo in the AWS agent docs page

- pages/agent/gcloud.md.erb
Hi, I am using Buildkite on a Kubernetes cluster and it's been awesome. I followed your documentation. Everything went well except for the placement of the `id_rsa` and `id_rsa.pub` files which are supposed to be in the `/root/.ssh/` folder. When I deployed using the new folder it works. Thanks!
> Path to id_rsa and id_rsa.pub file were incorrect.

- pages/agent/gcloud.md.erb
- The current `volumeMounts` config does not work, `mountPath` only accepts a folder and not a file unless you use "file projection" secrets. Also, in kubernetes YAML you can use octal `defaultMode: 0400` to be clearer about permissions (instead of `defaultMode: 254` which is required with kubernetes JSON).
- Also added a quick note about how to do container startup scripts.
> Fix gcloud docs for ssh-key mounts.

- pages/rest_api/jobs.md.erb
Docs for:
```bash
curl -X POST "https://api.buildkite.com/v2/organizations/{org.slug}/pipelines/{pipeline.slug}/builds/{build.number}/jobs/{job.id}/unblock"  \
-d '{
"fields": {
"name": "Liam Neeson",
"email": "liam@evilbatmanvillans.com",
}
}'
```
> Add docs for field parameter on unblock api endpoint

- pages/builds/scheduled_builds.md.erb
Once #116 is merged, it'd be nice to tell people _How_ they can actually create schedules. This updates the Scheduled Builds documentation to include that, as well as some readability tweaks to the header/interval section.
> Improvements to schedules docs

- pages/builds/parallelizing_builds.md.erb
I added a few more tests runners in knapsack gem.
I also worked with a few companies with large projects. They use Buildkite and knapsack_pro gem. Often people ask me how to run a project with knapsack_pro and what CI provider I recommend and my first choice is Buildkite because it can be really fast comparing to other solutions.
I prepared article with a simple introduction to Buildkite:
http://docs.knapsackpro.com/2017/auto-balancing-7-hours-tests-between-100-parallel-jobs-on-ci-buildkite-example
and examples of configured Ruby/Rails project + knapack_pro with and without Docker:
* https://github.com/KnapsackPro/buildkite-rails-docker-parallel-example-with-knapsack_pro
* https://github.com/KnapsackPro/buildkite-rails-parallel-example-with-knapsack_pro
Here is related PR for list of …
> Parallelising builds: Update info about knapsack gem

- pages/agent/cli_pipeline.md.erb
- pages/pipelines/trigger_step.md.erb
Our current [trigger documentation](https://buildkite.com/docs/pipelines/trigger-step) uses environment variable interpolation in the examples, but that's not supported in Buildkite Agent 2.0, only in the new Buildkite Agent 3.0 betas. Which can cause confusion (buildkite/feedback#260).
It is very common to want to use trigger steps in this way, so instead of just modifying those examples not to use interpolation, this adds documentation to the `pipeline upload` command, and a note below the trigger examples. The idea is that people will upgrade to 3.0 if necessary, or use the workaround if they can't upgrade their agent.
> Document pipeline.yml environment interpolation and caveats

- pages/agent/cli_artifact.md.erb
This PR fixes the artifacts link on the buildkite-agent artifacts page.
> Fix artifacts link

- pages/agent/cli_pipeline.md.erb
If you've been using a pre-3.0 Buildkite Agent, with a pipeline that uses `$SOME_ENV` in it's commands, it can be a bit of trial and error to figure out exactly how you need to update your pipeline.yml files to make them work with the new environment variable interpolation.
Because this is probably quite common, this PR updates the environment variable section with an example of doing exactly this. Which should, fingers crossed, help people who are snagged by this.
We should also look at updating our "Pipeline Steps" documentation with this type of example too.
Before:
After:
> Add example for using an environment variable from steps

- pages/agent/cli_artifact.md.erb
- pages/builds/artifacts.md.erb
This aims to clean up a few mistakes in our artifact documentation that are tripping people up, and tries to make the artifact upload/download CLI documentation a little clearer. It covers:
* Fixes the incorrect `--job` argument to artifact download (the correct argument is `--step`)
* Avoids using the word "glob" to describe the download wildcard syntax
* Adds download examples that match the upload examples (as often, that's what you want to do… upload in one step, download in another)
* Fixes the broken links to the old `/docs/rest-api/artifacts#glob-path-pattern` URL
* Removes the link to our source code implementation of glob matching
* Removes the mentioning of the `%` SQL LIKE function
* Puts the upload/download examples before the technical/full definition of the pattern
> Fix errors and clarify artifact upload docs

- pages/agent/configuration.md.erb
As pointed out by @mistydemeo, this is referring to the wrong env var. `BUILDKITE_AGENT_ACCESS_TOKEN` is the temporary token given to the agent by Buildkite, I'm pretty sure we mean `BUILDKITE_AGENT_TOKEN` here.
Fixes https://github.com/buildkite/agent/issues/490.
> Fix incorrect env for token config

- pages/builds/writing_build_scripts.md.erb
Integrates @ticky’s feedback from #87 to improve the wording around the use of the Bash `set` command. It also makes "Capturing Exit Status" example code consistent with our default option recommendations.
> Clarify bash option setting

- pages/rest_api/pipelines.md.erb
Missing the 'r' at the end of 'your' 😄
> Fix typo in team_uuids description

- pages/agent/configuration.md.erb
The buildkite agent does not appear to recognise the buildkite_meta_data
env var and it is referred differently above
> Correct name of envvar in documentation

- pages/pipelines/command_step.md.erb
This mentions the `skip` attribute introduced here: https://github.com/buildkite/feedback/issues/55.
cc @keithpitt
> Add `skip` attribute

- pages/agent/debian.md.erb
Comments starting with `##` in fenced code blocks are, for some reason, turned into HTML headings, then processed by the syntax highlighter. What the heck.
Anyway, this turns them into real Markdown headings, which sidesteps the problem entirely.
I’m gunna sneaky-merge this because it’s broken rn!
> Fix a parsing issue causing weird formatting

- pages/agent/cli_meta_data.md.erb
An update for the doc on the agent meta-data to reflect the latest from the man page. 
This page now includes the `--default` flag, as was requested in https://github.com/buildkite/docs/issues/139 🙌🏻
> Update meta-data doc

- pages/rest_api/jobs.md.erb
This fixes the HTTP method for unblocking jobs, and documents the optional parameters.
> Fix the job unblock REST API documentation

- pages/builds/environment_variables.md.erb
This updates the build environment variables list with the following changes:
* Adds `BUILDKITE_PULL_REQUEST_BASE_BRANCH`
* Make it clear they're strings (so when people go to write bash conditionals they remember to use `"true"`) etc.
> Update build environment variables

- pages/pipelines/wait_step.md.erb
A customer noted the wait step documentation could be read to suggest that the wait step only considers the success of steps between it and the preceding wait step.
I’ve updated the documentation to explicitly show off the run-collate-deploy wait step technique we use in our own deployments!
> Clarify the behaviour of wait steps

- pages/builds/build_status_badges.md.erb
This adds docs for the build badge JSON output format, for https://github.com/badges/shields/issues/1261#issuecomment-343710262
> Document build badge JSON output

- pages/pipelines/block_step.md.erb
I ran into this from the API in a pipeline upload, this adds the error the API gives to the docs ahead of time 😸
> Add allowed character set docs for block step key

- pages/agent/gcloud.md.erb
Lots of people prefer to use HTTPS cloning and API tokens for GitHub authentication. This adds instructions (not specific for GitHub) for how to do that with Google Cloud and Kubernetes
> Add docs for using .git-credentials for HTTP-based cloning with Kubernetes/gcloud

- pages/agent/cli_pipeline.md.erb
The old command swallows all newlines, resulting in invalid YAML.
> Fix environment variable substitution Buildkite Agent 2.x support

- pages/agent/cli_artifact.md.erb
Not sure if this was ever `baseUrl` but it looks like it should be `BUILDKITE_S3_ACCESS_URL` based on the current agent code and https://github.com/buildkite/agent/pull/261.
> Update S3 access URL environment variable

- pages/pipelines/command_step.md.erb
I've started on docs on the new syntax I've added for retries.
Here's a rundown of all the changes I've made over the last few weeks. Not all of them in the docs, maybe you can fit them in somewhere else?
- Introduced a new `retry` configuration for steps.
- Manual retries can be disabled
- You can optionally provide a `reason` why manual retries are disabled
- `permit_on_passed` allows manual retries to be performed on passed jobs
- You can configure the job to automatically retry depending on exit status
- You can configure how many times a job can be retried (max of 10) depending on exit status
- If a job gets an exit status of (`-1`) that means we lost connection with the agent. By default, we automatically retry on this exit status as well. So if you `kill -9` an agent half way …
> Documentation on latest retry changes

- pages/builds/environment_variables.md.erb
Alphabetising the env vars, because it kills me every time I look at this page that they're not in order. Also, makes it much easier for people to find what they're looking for 💁🏻
Possibly adding some more things to this page, so leaving this PR as a WIP for the moment.
Later:
- Add image to explain precedence
- Add the writable variables table
> Some env vars updates

- pages/pipelines/command_step.md.erb
I noticed this while I was checking out the docs on the automatic retry attributes. I'm assuming this is a typo, but please let me know if I'm mistaken :)
> Fix typo in retry docs

- pages/agent/v2/hooks.md.erb
- pages/agent/v3/hooks.md.erb
Hooks are sourced, not executed, so shebangs are misleading.
Closes #79.
> Remove shebangs from hooks

- pages/agent/v3/hooks.md.erb
- pages/agent/v3/windows.md.erb
Extra bits from @keithpitt's feedback:
- capitalising Windows in a few places
- update link to windows agent doc
- only link relevant text
- update link to plugins doc
- correct casing on Git and SSH
> Updates to the windows hooks docs

- pages/rest_api/artifacts.md.erb
Looks like the curl urls for both get and downloading an artifact are missing the job information.
> Fix curl url for artifacts/download.

- pages/agent/v2/aws.md.erb
- pages/agent/v2/cli_artifact.md.erb
- pages/agent/v2/cli_meta_data.md.erb
- pages/agent/v2/cli_pipeline.md.erb
- pages/agent/v2/cli_start.md.erb
- pages/agent/v2/configuration.md.erb
- pages/agent/v2/debian.md.erb
- pages/agent/v2/docker.md.erb
- pages/agent/v2/freebsd.md.erb
- pages/agent/v2/gcloud.md.erb
- pages/agent/v2/github_ssh_keys.md.erb
- pages/agent/v2/hooks.md.erb
- pages/agent/v2/installation.md.erb
- pages/agent/v2/linux.md.erb
- pages/agent/v2/osx.md.erb
- pages/agent/v2/prioritization.md.erb
- pages/agent/v2/queues.md.erb
- pages/agent/v2/redhat.md.erb
- pages/agent/v2/securing.md.erb
- pages/agent/v2/ssh_keys.md.erb
- pages/agent/v2/ubuntu.md.erb
- pages/agent/v2/upgrading_to_v2.md.erb
- pages/agent/v2/windows.md.erb
This adds a warning to the top of v2 agent docs, directing people to the v3 version:
Handy if they've arrived there by Google, or old links, and adds to the internal page rank for the v3 pages.
> Add an out-of-date agent warning to v2 docs pages

- pages/builds/docker_containerized_builds.md.erb
Did some updates for the Containerized Builds with Docker doc:
- Moved the env vars info to new sections about using Docker Compose/Docker without plugins
- Update the `docker-compose.yml` example
- Update the "Configuring the build step" section with plugin examples and descriptions
- Update the "Docker without docker compose" section with plugin examples and descriptions
- Add links to the plugins github readmes
- Add info about `docker system prune` to the cleanup section
> V3ify docker docs

- pages/agent/v3/configuration.md.erb
The environment variable for disabling plugins seems to be incorrectly documented. [Here is the exact location in `buildkite/agent` where the environment variable is defined](https://github.com/buildkite/agent/blob/adee22c9d9f102239f2f6271315208f797f89196/clicommand/agent_start.go#L250).
> Fix environment variable for disabling plugins

- pages/agent/v3/cli_meta_data.md.erb
This command seems to be undocumented online at the moment, but it is listed in `buildkite-agent meta-data --help`.
> Document the `buildkite-agent meta-data exists` command

- pages/agent/v3/docker.md.erb
Changed the link to config info from the old github repo to the dockerhub readme. Updated the ubuntu dockerfile link to point at the right place. 
Fixes #233
> Update links to config and dockerfile example

- pages/agent/v3/cli_artifact.md.erb
- pages/builds/environment_variables.md.erb
Added @lox's explanatory words about artifact downloads, plus a little example. Does this sound accurate @lox?
Also fixed up the S3 buckets bit - removed an out-of-date caveat about not being able to set env vars in places, added a note that using hooks is best practice, and updated some syntax in the env vars example so that the `env` is a proper hash. 
Fixes #229 and #230
> Add example and clarify artifact downloads outside builds

- pages/agent/v3/plugins.md.erb
Aside from the typo, `node` won't get out of date whereas `"node:7"` is already out of date—so let's go with just `node`?
> Fix docker image and typo in plugins docs

- pages/agent/v3/plugins.md.erb
This adds mention of the `file://` plugin URL format, which people have asked about on support for how to refer to plugins which might have been pre-baked or installed on the agent machine.
It also updates it from "git repository name" to "git repository URL", because that's the [Git lingo for it](https://git-scm.com/docs/git-clone#URLS).
> Add file:// plugin URL example

- pages/agent/v3/plugins.md.erb
The S3 plugin is no longer a plugin, and never really worked as one (see buildkite/elastic-ci-stack-s3-secrets-hooks#16), so this replaces references to it with the Junit Annotate plugin which I figure is probably the next most useful one after the Docker ones.
We also use plain English names in the plugin.yml now (buildkite-plugins/buildkite-plugin-linter#15), so I've updated it from "docker-compose plugin" to "Docker Compose plugin".
> Replace s3 plugin mentions with junit-annotate instead

- pages/builds/environment_variables.md.erb
The source code is super hard to read, and I'm not entirely sure it's useful for people, given we list them all on the `buildkite-agent start` docs page?
> Remove start command source link from env doc

- pages/agent/v3/cli_pipeline.md.erb
We introduced a `pipeline upload --no-interpolation` flag in 3.1.1.
> Document pipeline upload --no-interpolation

- pages/builds/environment_variables.md.erb
This mostly just renames this section of the env var docs, makes a bigger call out of the agent registration token being removed, and adds links to the hooks and plugins pages so people know where to look to figure out how to actually define their own environment variables.
> Edits to the job runtime environment env docs

- pages/agent/v3/hooks.md.erb
This reworks our hooks page to include information about plugin hooks.
The "Available hooks" have been redone to be in a table just like environment variables. Hopefully this makes it much easier to read and scan, and explicitly states the order that the hooks are run in.
It also updates the plugin doc to link back to the hooks page in lots of places, because it's important for plugin authors to understand hooks, and how they're run in order and relation to all the other hooks.
You might need to check this one out locally @harrietgrace.
> Add plugin hooks information

- pages/agent/v3/cli_annotate.md.erb
Fixes minor error in junit-annotate plugin example, updating to valid plugin version.
> Fixup junit-annotate plugin example.

- pages/webhooks/integrations.md.erb
Public install of RequestBin has been shutdown
Source: https://github.com/Runscope/requestbin#readme
> Remove RequestBin in documentation

- pages/tutorials/adfs.md.erb
- pages/tutorials/custom_saml.md.erb
- pages/tutorials/google.md.erb
- pages/tutorials/okta.md.erb
- pages/tutorials/onelogin.md.erb
First cut of the SSO Guides! 
I'm specifically looking for feedback on the content: accuracy and readability, and any missing information. Feedback on layout and styling also welcome, especially the AD FS guide! 
In dev, the guides live under 'tutorials':
- google
- okta
- onelogin
- adfs
- custom-saml
Still to come (in a separate PR): Intro to SSO
> Add sso guides

- pages/builds/build_meta_data.md.erb
Removing the bit about not being able to add metadata to running agents. 
Do you think anything needs to be added in its place @toolmantim, or is it enough to just not have this misleading bit?
> Fix the meta data doc

- pages/agent/v2/ubuntu.md.erb
- pages/agent/v3/debian.md.erb
- pages/agent/v3/install/_debian.md.erb
- pages/agent/v3/ubuntu.md.erb
Ubuntu 14.04 is LTS and still supported until April 2019, but 12.04 is long gone.
Debian 9.x came out mid last year, so let's say 7.x+
> Bump OS versions in agent instructions

- pages/agent/v3/securing.md.erb
This doesn't filter versions, but helps implement the security advice on plugins (e.g. whitelist plugins, and possibly version SHAs)
> Adds an example of whitelisting plugins

- pages/agent/v3/configuration.md.erb
This was done via #791 and released in v3.3.0. The PR prose refers to a command-line flag that is wrong :(
> Add doc for --tags-from-host from v3.3.0

- pages/webhooks/integrations.md.erb
IDK what exactly needs to be said here, but unlike Github, Buildkite does not have SNS publishing, so the AWS Github guide is only a piece of the puzzle.
> Add to description of webhook AWS integration

- pages/agent/v3/configuration.md.erb
I find docs easier to read when sorted. Unfortunately:
* this splits apart the semantic-groupings for things like paths
* this makes token last, but it's required, so I added a column to denote that fact
Suggestion - JS-based table-sorting/filtering thing?
> Alpha-sort agent configuration setting table + add 'required?' column

- pages/pipelines/command_step.md.erb
The [command step attributes](https://buildkite.com/docs/pipelines/command-step#command-step-attributes) incorrectly reference the build meta-data docs, instead of the agent tags docs (probably from when agent meta-data was renamed to agent tags). This updates the link and words to point to the new [setting tags](https://buildkite.com/docs/agent/v3/cli-start#setting-tags) doc, and keeps the link to the targeting section as well.
> Fix agent tag command step link

- pages/apis/graphql_api.md.erb
Update docs to remove the beta warning in the graphql api, since the beta label has been removed.
> Remove beta section of the graphql api doc

- pages/agent/v2/cli_meta_data.md.erb
- pages/agent/v3/cli_meta_data.md.erb
I found this small fixup in my git stash, from I-can't-remember-when, and it still seemed like an okay change? It just rewords the "practical examples" because there are still some practical examples on these docs pages.
I'm happy for you to decide if the change is right or wrong @harrietgrace! But thought I'd push it up here before I `rm` it.
> Small word updates to the meta-data doc

- pages/agent/v3/configuration.md.erb
Someone wanted to know where the documentation was for which agent configuration options support templates. Only `name` does, but it wasn't entirely clear, so this tries to help make that a little more clear.
I struggled a bit with `%n` because the way it works is complicated, so just stuck with "a unique number".
> Clarify only agent name config supports templates

- pages/tutorials/sso_setup_with_graphql.md.erb
Building on #302, this adds some information required for people setting up SSO with Google Cloud Identity. 
Google Cloud Identity doesn't have a public meta-data URL for setup, so this adds back the section we lost previously, which shows people how to set up SSO manually using an SSO URL, identity/issuer and certificate.
These instructions work for both a custom app:
and for our current built-in Google Cloud integration:
> Add Google Cloud Identity instructions

- pages/tutorials/sso_setup_with_graphql.md.erb
This was meant to be removed in #302 — and it's now broken, because the type name has changed
> Remove SSOProviderGitHubOAuth

- pages/tutorials/sso_setup_with_graphql.md.erb
When a SAML system doesn't support meta-data URLs, everything is trickier. This adds some more information into the SAML guide based on experience setting up Google Cloud Identity.
> Fixes and additions for Google Cloud Identity

- pages/pipelines/environment_variables.md.erb
There were two broken links on the env vars page, one to the hooks doc and one to plugins doc. Both were missing the '/docs/' part of the url. Added this back in 👍🏻
Reported in #338
> Add missing docs url part to two broken links

- pages/agent/v3/cli_annotate.md.erb
Hey! 
The docs page says that markdown is supported, but most of the examples in the page show HTML. I suspect that the reason HTML is supported is because you can put basic tags into markdown, but maybe it would be good to highlight this to readers? 
Should the supported tags be listed?
> HTML available in annotations

- pages/apis/rest_api/builds.md.erb
Adds the pull request params to the [Create a Build](https://buildkite.com/docs/apis/rest-api/builds#create-a-build) documentation:
> Add the pull request params to the Builds API docs

- pages/pipelines/command_step.md.erb
Clarifying the use of `""` within the skip command section. Wasn't sure whether to add this as a sentence or as an example case, but I decided it wasn't clear what the example case results in.
> Clarify empty string is the same as false when skipping

- pages/pipelines/plugins.md.erb
[bksr](https://github.com/toolmantim/bksr) has been deprecated in favour of the [Buildkite CLI](https://github.com/buildkite/cli)
> Link to the buildkite/cli instead of bksr

- pages/pipelines/command_step.md.erb
Adding in @toolmantim's suggestion for the exit status note, removing the incorrect info about attempting to reconnect to the agent.
> Remove incorrect info about reconnecting

- pages/apis/rest_api.md.erb
The most recent commit to the buildkite-node library was [2 years ago](https://github.com/fraserxu/buildkite-node/commits/master) and the package is [not available in NPM](https://www.npmjs.com/search?q=buildkite-node).
> Remove unmaintained NodeJS library

- pages/agent/v3/cli_annotate.md.erb
Adding a note about how many annotations will display in the build for each step. Closes #337.
@eleanorakh I got this info from your support ticket, just wanted you to have a squiz before I merge 😄
> Add annotation limit info

- pages/agent/v3/cli_annotate.md.erb
- pages/apis/rest_api/jobs.md.erb
- pages/pipelines/images_in_log_output.md.erb
This updates the URL to Terminal (see: https://github.com/buildkite/terminal-to-html/issues/52)
> Update the URL to Terminal

- pages/pipelines/command_step.md.erb
While helping on https://github.com/buildkite/agent/pull/899 I realised that perhaps we need to update the documentation on automatic retries. And while I was there, I gave all the examples a bit of a once over to make sure we weren't adding attributes on types of jobs that typically didn't use them.
> Command step attribute cleanups

- pages/agent/v3/github_ssh_keys.md.erb
The link had a space in it, which broke the actual linkage. Also, broke the line to be easier to edit.
> Fix broken link

- pages/apis/rest_api/jobs.md.erb
Documents the new REST API endpoint we've added to delete a job’s log output.
> Add docs for deleting job log output

- pages/apis/webhooks.md.erb
- pages/apis/webhooks/job_events.md.erb
We've been using the descriptions from the main bk app's config yml in here for a while. They don't really describe what's actually going on, and we've had a few people now ask about what the difference is between started and activated. 
I couldn't find if those snippets are used elsewhere in the app, so I decided to just change them in the docs 👍🏻
> Update job event descriptions

- pages/apis/rest_api/teams.md.erb
This adds docs for the new Teams API, including a data model table which we added to the artifacts API long ago and meant to do the same for all the other REST API endpoints as well.
> Adds docs for the new Teams REST API

- pages/agent/v3/docker.md.erb
This adds a really prominent warning about using the agent in docker and our plugins. 
The issue at https://github.com/buildkite-plugins/docker-buildkite-plugin/issues/61 provides some more context.
> Add a warning about plugins and the agent in docker

- pages/integrations/sso/custom_saml.md.erb
This section heading got removed when I updated the Custom SAML doc to use the same formatting/structure as the other guides.
> Remove link that no longer exists

- pages/pipelines/environment_variables.md.erb
The docs currently suggest that `BUILDKITE_BUILD_ID` can be blank on rebuilds, surely not?
> Fix incorrect BUILDKITE_BUILD_ID docs

- pages/apis/rest_api.md.erb
Query params shouldn’t be used for sensitive information. This removes that method from the REST API authorization documentation.
> Remove the query param method of auth

- pages/pipelines/plugins.md.erb
Fixes the broken link that @keithpitt pointed out 🙏🏻
The copy has a link to Buildkite CLI, but in the links at the bottom there was bksr instead. Removed bksr and put in the correct url and link name for Buildkite CLI.
> Fix broken link on plugins page

- pages/agent/v3/docker.md.erb
- pages/tutorials/docker_containerized_builds.md.erb
As discussed in #367 there's a number of improvements we could make to our Docker documentation, including removing the words about environment variables / arguments being insecure.
I took the opportunity to update the Docker page to be more consistent with our other documentation pages (using the troubleshooting note styles, instead of 🚨 for example).
It also updates things to be our latest recommendations, and ensures that all the `docker run` command line examples are consistent.
> Update the Docker Agent docs

- pages/integrations/sso/adfs.md.erb
@toolmantim pointed out that the ADFS guide is having some layout issues in https://github.com/buildkite/docs/issues/403.
This PR swaps out the sublist items for regular bullet points:
It also bolded the subheadings inside Step 1. They're not as bold or large as the H3's, and I've left the H4 #s in there incase we ever do have CSS for those:
> Fix ADFS layout issues

- pages/agent/v3/docker.md.erb
One of the links in the Docker docs referred to a section that had been renamed in #402, this PR updates the text and URL of the link. Ran the tests locally and they're passing 👍🏻
> Update old link

- pages/tutorials/docker_containerized_builds.md.erb
As discussed in #366, this removes the link to `docker-gc` which isn't necessary anymore now that `docker system prune` is widely available and does almost everything docker-gc did.
And this also removes "the buildkite agent cleans up the images after each run" which hasn't been true since we switched to using plugins. The Docker Compose plugin does do some clean up, the Docker plugin doesn't. And either way, it's recommended you still set up `system prune` on your agent host.
> Improvements to the Docker cleanup docs

- pages/integrations/sso/sso_setup_with_graphql.md.erb
As it stands, the DisableProvider query doesn’t work, because it doesn’t select any of the output of `ssoProviderDisable`.
This was reported by a customer in Slack.
> Fix “Disabling an SSO provider” query

- pages/apis/webhooks/integrations.md.erb
Removed the outdated link that @ticky reported in #98. Gave it a new title to take the focus off SNS, added in a new intro that @toolmantim came up with that includes a mention of API gateway. 
The updated section looks like this:
Closes #98
> Update the SNS/Lambda webhooks info

- pages/apis/webhooks.md.erb
As mentioned in #292, we currently don't say where to set up your webhooks. This PR adds a note about where to find the webhooks in the org settings. 
@toolmantim do you think it needs more than this? I would have liked to mention the provider-specific guides we have too, but they don't seem to be linked from within the app after you've set up your pipeline? Do they only appear on the initial blank pipeline setup page?
Closes #292
> Add info about where to add webhooks

- pages/agent/v3/securing.md.erb
Requested in https://github.com/buildkite/docs/issues/140, and the example `proxy.conf` is from there too 🌟
I got @keithduncan to help me test out those two variables with proxy running in docker, so they should be all people need to get set up no matter what process manager they're using 👍🏻   
Closes https://github.com/buildkite/docs/issues/140
> Add a section about running the agent behind a proxy

- pages/pipelines/command_step.md.erb
From https://github.com/buildkite/buildkite/pull/3511, this adds the ID attribute to the command step table. I'm not 100% on its function, @toolmantim any suggestions for a better example?
> Add ID attribute

- pages/agent/v2/debian.md.erb
- pages/agent/v2/ubuntu.md.erb
- pages/agent/v3/debian.md.erb
- pages/agent/v3/ubuntu.md.erb
Updating the Ubuntu and Debian instructions for both v2 and v3 to use `hkps://` instead of `hkp://`. 
Closes #328.
> Use hkps with the ubuntu keyserver

- pages/pipelines/wait_step.md.erb
Adds a quick explainer about the `~` in the continue on failure example. Mentions that it's an explicit null character, that it's not required, and that we recommend its use to prevent other things getting in between the wait and the continue lines. 
I'm a little unsure of the wording I've used, do you have any feels about it @toolmantim?
Closes #222
> Update wait docs

- pages/agent/v2/debian.md.erb
- pages/agent/v2/ubuntu.md.erb
- pages/agent/v3/debian.md.erb
- pages/agent/v3/ubuntu.md.erb
People using Docker were having issues with the ipv6 keyserver we were recommending. This updates to use the ipv4 sks-keyservers. Also updates the echo line with @lox's suggested replacement.
> Update keyservers for Debian and Ubuntu again

- pages/agent/v3.md.erb
We found out about the `SIGQUIT` behavior from source code, which we are using to immediately fail and retry jobs when we spin down AWS instances. 
Feel free to make any changes to the wording.
> Add SIGQUIT behavior to docs

- pages/pipelines/environment_variables.md.erb
In the sentence edited, var name changes to `MY_ENV`, rather than `MY_ENV1` used above.
> Fix MY_ENV typo

- config/initializers/content_security_policy.rb
We use inline scripts for Matomo tracking, and for the agent selector, but they're currently broken because we don't configure any CSP nonce:
This fixes the inline scripts by configuring the CSP nonce correctly.
Fixes #473
> Configure CSP nonce correctly for inline scripts

- pages/agent/v3/gcloud.md.erb
This adds a doc to cover the change in https://github.com/buildkite/agent/pull/1000.  It probably should only be merged _after_ that one.
FYI @lox @petemounce
> Add new configuration option to agent GCS docs 

- pages/apis/rest_api.md.erb
Removing basic auth section of the Auth part of the REST API doc. Added a note telling people it's no longer available.
This is what the auth section will look like with this PR:
> Remove basic auth from REST API doc

- pages/agent/v3/cli_annotate.md.erb
Turns out our docs had been misleading people somewhat the whole time!
When writing an HTML block in markdown, the wrapping element needs to be a recognised starting html element. `<pre />` qualifies, but `<code />` does not. This means that if someone used our example, the code would come through as processed markdown, causing strange rendering errors.
Fixes buildkite/terminal-to-html#64
> Correct the order of `<pre />` and `<code />` tags in annotation docs

- pages/apis/rest_api/builds.md.erb
Looks like the oldest REST API doc is inconsistent with the rest. This updates the header, so it matches all the other rest docs.
> Add missing "API" to Builds REST API doc

- pages/pipelines/environment_variables.md.erb
This rearranges the environment variable documentation, given that the precedence is actually pretty much reversed from what’s listed here.
It also adds a reference to the YAML Pipeline Steps beta, which has precedence closer to what we used to document.
> Correct the environment variable precedence documentation

- pages/pipelines/trigger_step.md.erb
The docs claimed it was "master" but this was only the case if it was unspecified, which is very uncommon, as that in turn defaults to "master"
> Correct the default branch for Trigger steps

- pages/pipelines/ignoring_a_commit.md.erb
As mentioned by @lox in #317, Bitbucket Server doesn't send the commit message with every type of webhook. From the Bitbucket Server docs, it looks like it's just the `refs_changed` webhook that doesn't include the commit message. 
This PR adds a troubleshooting note to the end of the Ignoring Commits doc:
Closes #317
> Add note about Bitbucket server to Ignoring Commits

- pages/agent/v3/docker.md.erb
This page has two typos for the `BUILDKITE_BUILD_PATH` environment variable
> Fix environment variable reference in docker page

- pages/integrations/sso.md.erb
Fixes the following bug on https://buildkite.com/docs/integrations/sso:
> Fix the SSO heading

- pages/pipelines/plugins.md.erb
v1 of the detect-clowns plugin required a `command`, so the current example would fail. This updates the example to use v2 of the plugin, which doesn't need the `command`, which makes it work with the example 🤡
> Make the detect-clowns plugin example work

- pages/pipelines/command_step.md.erb
The following pipeline definition now returns a validation error, because the same step id is used twice:
```yml
steps:
- command: "tests-1.sh"
id: "tests"
- command: "tests-2.sh"
id: "tests"
```
This updates the docs to mention that the `id` must be unique.
> Mention that step ids now need to be unique

- pages/integrations/artifactory.md.erb
This updates the Artifactory guide to recommend API keys and access tokens instead of a password. It also fixes the example `NPM_CONFIG_REGISTRY` environment variable to actually work (by using the credentials set up in the previous section)
> Update the Artifactory security recommendations

- pages/agent/v3/configuration.md.erb
Adds the agent config option `cancel-grace-period` to the agent configuration docs.
Related: https://github.com/buildkite/agent/pull/1071
> Document the `cancel-grace-period` agent config option

- pages/pipelines/command_step.md.erb
- pages/pipelines/environment_variables.md.erb
- pages/pipelines/secrets.md.erb
Env vars page update for https://github.com/buildkite/buildkite/pull/4063:
- deprecates the `BUILDKITE_STEP_IDENTIFIER` var
- adds the `BUILDKITE_STEP_ID` and `BUILDKITE_STEP_KEY` vars to the main list
Also snuck in a little alphabetise of the vars list - the S3 vars were at the end of the S's when they should have been at the start. 
@toolmantim do those descriptions of the new STEP_* vars look legit?
> Add STEP_* env vars

- pages/pipelines/branch_configuration.md.erb
There have been two issues this year requesting clarification on how branch patterns work with negation: #241 and #514. Looks like our docs on this were definitely due a little update!
This PR adds a quick intro paragraph to the branch patterns section that describes a bit more about how the attribute works. There's also an extra example including negation that includes it with some non-negative branches. 
Closes #241 and closes #514
> Update branch pattern negation and info

- pages/agent/v3/cli_annotate.md.erb
@keithpitt was this the kind of thing you'd imagined with #387? 
This adds a big list of all the classes we support from Basscss. I've done some further grouping of the classes to separate them out a bit, does it look like they're all in appropriate places @ticky?
Closes #387
> Add list of supported CSS classes in annotations

- pages/pipelines/defining_steps.md.erb
Adds a section explaining how to use the `?clone` URL param to copy a pipeline's steps into a new pipeline. 
Does that all sound legit @lox?
Closes #439
> Add section on cloning pipeline steps

- pages/integrations/sso.md.erb
As @toolmantim pointed out in #451, we don't mention JIT provisioning anywhere in our SSO docs, even though it's a thing we have always supported.
This PR adds a (very) brief FAQ containing those keywords:
Closes #451
> Add JIT provisioning to FAQ

- pages/pipelines/secrets.md.erb
A quick update to #519 which catches a missing step `id` property
> Fix old reference to a step "id"

- pages/agent/v3/osx.md.erb
As discovered in https://github.com/buildkite/docs/issues/353, when you're using launchctl to start your Agents on macos, you can run into issues if you're not logged in to the launchctl GUI. 
This PR adds a troubleshooting note to the 'Starting on Login' section of the macos Agent page, including the text of the resulting error:
@lox does the content of the note make sense? Do we need any further steps other than just being logged in and restarting?
Closes #353
> Add launchctl gui troubleshooting note

- pages/pipelines/controlling_concurrency.md.erb
I was recently implementing concurrency controls in some of my Buildkite pipelines and saw this spelling error. I thought I would fix it up :smile:
> Fix spelling error in interdependant

- pages/agent/v3/configuration.md.erb
As pointed out in https://github.com/buildkite/docs/issues/501, we're missing a bunch of config options in our Agent Configuration options section.
This PR adds:
--endpoint 
--experiment 
--git-clone-mirror-flags 
--git-fetch-flags 
--git-mirrors-lock-timeout  
--git-mirrors-path 
--log-format 
--metrics-datadog 
--metrics-datadog-host 
--no-git-submodules 
--no-http2 
--no-plugin-validation 
--spawn 
--tags-from-gcp-labels 
--wait-for-gcp-labels-timeout
The descriptions are from the [agent start code](https://github.com/buildkite/agent/blob/22e3b5110a066e5404e1de1780846d3505656a94/clicommand/agent_start.go). I also moved `disconnect-after-job-timeout` to deprecated, as it's listed in the deprecated bit of that agent start file.  
The only thing missing is an example or default for …
> Update agent config options

- pages/agent/v3/configuration.md.erb
- pages/pipelines/environment_variables.md.erb
Adds the env var for the `cancel-grace-period` agent config option. 
@lox can it be edited as an env var? Or just as a config option?
> Add cancel-grace-period and cancel-signal env vars

- app/views/layouts/application.html.erb
- pages/agent/v3/cli_step.md.erb
- pages/agent/v3/help/_step_get.txt
- pages/agent/v3/help/_step_update.txt
Docs for https://github.com/buildkite/agent/pull/833 and https://github.com/buildkite/agent/pull/1083. 
@keithpitt I wasn't really sure how to describe this in the little intro paragraph. Is what I've got accurate? Do we need to add anything else?
> Add a CLI reference page for `buildkite-agent step`

- pages/pipelines/conditionals.md.erb
Updates the note at the end of the 'supported syntax' section to be a troubleshooting note and adds info about escaping $. Also updates the example code at the end of the doc so that both the instances of $ are escaped with \. 
Closes #542
> Update conditionals docs to escape $ char

- pages/apis/rest_api.md.erb
Adding a link to a python client for the Buildkite REST API. Available via `pip` 📦
> Add Python Buildkite api wrapper

- pages/agent/v3/configuration.md.erb
As mentioned in ye olde PR https://github.com/buildkite/agent/pull/875, the `git-clean-flags` has defaulted to `-ffxdq` since v3.8.0. 
This PR adds some more version info to the agent config option. The env var for this option already has the correct default value.
> Update git clean flags default

- pages/agent/v3/cli_meta_data.md.erb
- pages/agent/v3/help/_meta_data_keys.txt
Adding the `buildkite-agent meta-data keys` command to the meta-data CLI page. Added in https://github.com/buildkite/agent/pull/1039.
> Add meta-data keys --help text

- pages/agent/v3/hooks.md.erb
We recently (agent v3.15.0) changed the behaviour of the command hooks; it used to run all the command hooks present, now it just runs one. Also noted in https://github.com/buildkite/docs/issues/438.
This PR adds Agent version info to the existing note about command hook behaviour. Also includes some purely visual formatting of the table for easier editing 😊
> Add agent version note to command hooks description

- pages/pipelines/environment_variables.md.erb
This has been around for almost a year and a half now (https://github.com/buildkite/agent/pull/748), so I'm removing the 'currently experimental' note from the description. 
Other things:
- Updating the bit about exporting to hooks so that it's in line with the format of the rest of the vars. 
- Changing the agent config option to be `no-plugin-validation` instead of `plugin-validation`, as we only have one with the `no` prefix in the config docs.  
- Changing from 'values' to 'default' in the example bit so that it's clearer that it's off by default.
> Update desc for plugin validation

- pages/agent/v3/cli_annotate.md.erb
Now that we've got a "show more" button for annotations on the build pages, we don't need to mention the 5 annotation limit. See https://github.com/buildkite/buildkite/pull/3468 for more context.
> Remove mention of annotation display limit

- pages/apis/rest_api/jobs.md.erb
A new field called `header_times` was added to the job log payload  in https://github.com/buildkite/buildkite/pull/3968. 
This PR adds the field to the example output in the job REST API doc.
> Add header_times to job log API

- pages/pipelines/defining_steps.md.erb
You can store your `pipeline.yml` in other places than just the `.buildkite` directory that we mention in the docs. Added in https://github.com/buildkite/agent/pull/1051.
This PR adds a note that you can also use the top level of your repo, or a non-hidden `buildkite` folder.
> Add note about alternate pipeline.yaml paths

- pages/apis/rest_api/access_token.md.erb
Access Token API `https://api.buildkite.com/v2/access-token` is returning `uuid`.
> access token api returns uuid instead of id

- pages/agent/v3/cli_annotate.md.erb
This documents the coloured console output behaviour added in buildkite/buildkite#3479
Note: the four-character Markdown indent was used in this because of vmg/redcarpet#208
> Document the recently-added `term` blocks in annotations

- pages/apis/rest_api/pipelines.md.erb
[List pipelines](https://buildkite.com/docs/apis/rest-api/pipelines#list-pipelines) will return `env` and `steps` like other pipeline API responses.
> add missing env and steps to pipeline docs

- pages/pipelines/environment_variables.md.erb
A new env var was added in https://github.com/buildkite/agent/pull/1072 to enable encryption for S3 artifacts. 
This PR adds the new env var using the same format as the other private S3 bucket vars. @lox is the hooks info the same as the other S3 vars for this one?
> Add S3 encryption env var

- pages/agent/v3/configuration.md.erb
- pages/pipelines/environment_variables.md.erb
There was a new Agent config option added in https://github.com/buildkite/agent/pull/1066 - `health-check-addr`. 
This PR adds the config option and the associated env var. @lox what would be an appropriate example to use for the 'address:port'?
> Add health-check-addr agent config option and env var

- pages/apis/rest_api/pipelines.md.erb
As brought up in #511, the `default_branch` option is available on create and update in the pipelines endpoint, but wasn't listed in the docs. 
This PR adds `default_branch` as well as alphabetising the attribute tables.
> Add default_branch api field

- app/assets/stylesheets/public/_docs.scss
- pages/pipelines/scheduled_builds.md.erb
Add a note about using the Fugit::Cron parsing for cron strings. 
https://buildkite-docs-review-pr-571.herokuapp.com/docs/pipelines/scheduled-builds
@ticky I saw that you wanted to add tests for Fugit features, did you want me to hold off on merging this docs note until after that's set up?
> Add info about extended cron syntax

- pages/pipelines/block_step.md.erb
- pages/pipelines/command_step.md.erb
- pages/pipelines/conditionals.md.erb
- pages/pipelines/trigger_step.md.erb
- pages/pipelines/wait_step.md.erb
Adds `build.env()` to the supported variables list on the Conditionals page. I've also alphabetised the table so it's easier to find things. 
@keithpitt could I please get your help with an example? Also, is the description correct? 😄
Edit: Adds a bunch more new supported vars too! (From https://github.com/buildkite/buildkite/pull/4348)
> Add new conditionals vars

- pages/agent/v3/prioritization.md.erb
From issue https://github.com/buildkite/docs/issues/454, and stole some words from @toolmantim in https://github.com/buildkite/feedback/issues/422. 
This PR adds a new section called Load balancing to the Agent Prioritization page. 
Closes #454
> Add load balancing info 

- pages/pipelines/command_step.md.erb
Got this in a pipeline upload:
```
422 One of the steps you provided was invalid: Step keys can't have the same pattern as a UUID (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
```
> fix: key value

- pages/pipelines/conditionals.md.erb
Adding a warning around custom env vars as I have had two users caught out by this.
A bit of background:
Currently there are two flows when the build is created and they both operate differently in how they handle the processing of env var precedence. The new beta YAML pipeline steps supports this but the original pipeline upload does not (possibly breaking existing pipelines if we changed the precedence).
- Not sure if we want to link to the change log here as I did not see any other documentation around this.
- I did try and initially add this as **Note** to the build.env in the table column but it was pretty large
> Add warning for conditionals with custom build.env values

- pages/pipelines/notifications.md.erb
Couple of quick fixes here:
- Fixing a typo here from our example that uses an unknown value status rather than build state. 
- This also fixes an error about the passed value not being a variable.
> Fix typo in notification docs

- pages/pipelines/notifications.md.erb
Adds a note to the Notifications page about requiring a `pipeline.yml` file or the YAML steps editor.
cc @jayco
> Add note about notify attribute usage

- pages/pipelines/notifications.md.erb
Due to how YAML handles this, channel names not in quotes, or not directly following a workspace name, are treated as comments and their values discarded!
> Ensure any bare Slack channel names in the `notify` docs are quoted

- pages/pipelines/block_step.md.erb
Link named "input step" was linking "block step" (that is, this same page)
> Fix wrong link

- pages/integrations/amazon_eventbridge.md.erb
This adds a `detail-type` to the payload examples, which are often used in the event pattern to filter only certain types of events. It also fixes some incorrect payload examples in the last bunch of agent events.
Thanks to @keithduncan for the report of these!
> Add EventBridge detail-type and fix the payloads

- pages/deployments.md.erb
Concurrency parameter is called "concurrency_limit" instead of just "concurrency" as in the rest of the docs.
> Fix concurrency parameter in deployments.md.erb

- pages/pipelines/notifications.md.erb
The syntax listed here will currently result in an unhandled 500 error. The "channels" options must in fact live within the "slack" object.
> Fix the pipeline notification documentation

- app/helpers/application_helper.rb
`/docs` in production was calling this `#dashboard_path` method which only existed in the buildkite/buildkite app that it was a submodule of.
Adding it here allows buildkite/docs to be run in isolation.
The error when this is missing only manifests when `bk_logged_in=true` cookie is set (i.e. `#probably_authenticated?` is true)
> dashboard_path in ApplicationHelper

- pages/integrations/amazon_eventbridge.md.erb
Adds in the started_at and finished_at values to eventbridge events.
> add in started_at finished_at

- pages/pipelines/environment_variables.md.erb
I did some digging with this one today for a user that was trying to set BUILDKITE_CANCEL_GRACE_PERIOD in the pipeline. 
Even though the value is not in the protected list as discussed https://github.com/buildkite/docs/pull/543 It is the config value that is actually used when cancelling here https://github.com/buildkite/agent/blob/master/agent/job_runner.go#L330.
I have just reverted to the text to the previous value.
> revert BUILDKITE_CANCEL_GRACE_PERIOD changes on pipeline value

- pages/agent/v3/ssh_keys.md.erb
Running a build with an environment variable set is a much easier way of debugging SSH than having to edit a `~/.ssh/config` file on the agent machine.
> Use GIT_SSH_COMMAND for debugging ssh

- pages/deployments/deploying_to_kubernetes.md.erb
Earlier in the tutorial, we created the template at `k8s/deployment.yml` rather than `k8s/app.yml`.
Thanks to Madhuri Yechuri for noticing this.
> Use a consistent filename for the k8s manifest template

- .buildkite/pipeline.deploy.yml
- .buildkite/push-image.sh
the docker-ecr-publish plugin works well, but it insists on pushing a `latest` tag to the repository.
We're experimenting with an immutable tags on ECR, so pushing latest fails. I've opened [an issue](https://github.com/seek-oss/docker-ecr-publish-buildkite-plugin/issues/12), but in the meantime this should get the docs build working again.
> use an in-repo script to push the docs docker image to ECR

- pages/apis/rest_api/pipelines.md.erb
I was reading the docs on https://buildkite.com/docs/apis/rest-api/pipelines, and I noticed that the tabbing was off, seeming to me that it `env` was part of `steps`. 
This fixes the tabbing.
> Update pipelines.md.erb tabbing

- pages/apis/rest_api/builds.md.erb
- pages/apis/rest_api/jobs.md.erb
This adds the `step_key` field to the REST API job responses. It also updates the `name` examples, in order to make it clear what the three different fields are: `command`, `name` and `step_key`.
> Add step_key to jobs REST API responses

- Gemfile.lock
> xmlStringLenDecodeEntities in parser.c in libxml2 2.9.10 has an infinite
> loop in a certain end-of-file situation.  The Nokogiri RubyGem has
> patched it's vendored copy of libxml2 in order to prevent this issue
> from affecting nokogiri.
-- https://github.com/advisories/GHSA-7553-jr98-vx47
I haven't tested this locally, but I'd be surprised if a point release of nokogiri broke anything.
> nokogiri 1.10.8; fix CVE-2020-7595

- pages/apis/graphql_api.md.erb
Our frontend code isn't its own repo anymore! Removing the link from the graphql guide 😊
> Remove link to frontend repo that doesn't exist

- app/controllers/application_controller.rb
- config/routes.rb
This app is using [lograge](https://rubygems.org/gems/lograge) to log requests one-per line. Like this:
method=GET path=/docs/tutorials/getting-started format=html controller=PagesController action=show status=200 duration=1771.03 view=44.04
It renders some 404s (like when ActiveRecord::NotFound is raised), but it's unable to log requests for unmatched routes. The workaround [described in the README](https://github.com/roidrage/lograge#handle-actioncontrollerroutingerror) is to add a catch-all route at the lowest priority and render the 404 page with a controller action.
With this change, we got 404 logs:
method=GET path=/docs-fargate/tutorials/getting-started format=html controller=ApplicationController action=route_not_found status=404 duration=4.73 view=4.52
This will be helpful for …
> log 404s to stdout

- Dockerfile
- config/initializers/assets.rb
- config/routes.rb
We're preparing to serve https://buildkite.com/docs with this app deployed to fargate.
During the preparation we'd like to serve https://buildkite.com/docs from the current location, and https://buildkite.com/docs-fargate from this app on fargate.
Once we're happy that the rails app on fargate is working correctly, we can change the ALB to route https://buildkite.com/docs to it.
This PR attempts to make the app capable of working under both route prefixes, so there's no code changes required to start serving production traffic (and we can then remove support for `/docs-fargate`) at our leisure.
Note that assets will be loaded from `/docs-fargate/assets/*`. We'll need to revert the change in `config/initializers/assets.rb` before we remove `/docs-fargate` from the ALB.
> Configure the app to serve pages at /docs/* and /docs-fargate/*

- app/helpers/application_helper.rb
- app/views/layouts/application.html.erb
- config/routes.rb
While we're in the process of migrating docs to be hosted on fargate, we're routing https://buildkite.com/docs-fargate/* to the fargate containers.
This set of tweaks makes it possible to click around the site at https://buildkite.com/docs-fargate/* and stay on the  `/docs-fargate` prefix. Hopefully this makes it easier to test, with much less URL hacking.
@matthewd has pointed out that it might've been easier to leave the URLs as `/docs/*` and use an ALB rule that routes the *host* `pre.buildkite.com` to the new fargate service. he's right, that would've been easier. We've sunk the time into this approach now and I think it's done. Oops.
> Some more URL-related tweaks to make /docs-fargate work nicely

- config/puma.rb
this app is being deployed as a container on fargate, where we can size the tasks to a low-ish amount of cpu/memory resources.
In a container it's often nice to keep the processes as simple as possible, but have more of them.
I've also upped the thread count, on the assumption that with no DB most requests will be super fast and we can handle a fair number at the same time.
> configure puma to run in single (non-clustered) mode

- config/routes.rb
At the moment we're testing this app in production at https://buildkite.com/docs-fargate, and it's helpful to have that URL work (just like https://buildkite.com/docs).
Once this app is moved to service requests for https://buildkite.com/docs, we can remove this.
> redirect /docs-fargate to somewhere that renders a page

- pages/pipelines/defining_steps.md.erb
* Remove the empty spaces.
* Close the bash command with missing quote mark (can see in syntax highlighting on the doc page it isn't closed too)
> Close bash command quotation mark

- app/assets/stylesheets/public/utils/_text_content.scss
- app/models/page/renderer.rb
- spec/models/page/renderer_spec.rb
Adds support for code blocks with filenames.
For example:
~~~markdown
Here's a example of a `docker-compose.yml` file for a Ruby on Rails application that depends on Postgres, Redis and Memcache:
```yml
version: '2'
services:
db:
image: postgres
redis:
image: redis
memcache:
image: memcached
app:
build: .
working_dir: /app
volumes:
```
{: codeblock-file="docker-compose.yml"}
~~~
Closes #666
> Adds support for code block filenames

- config/initializers/session_store.rb
In production both bk/bk and docs are hosted under the buildkite.com domain, so in theory they can read each others cookies.
However, the rails session cookie is encrypted and we use different encryption keys for both apps. If we configure them to use the same session cookie, they'll only both be able to read the data if we use the same encryption key. I've done that before elsewhere and it works, but coupling codebases like that is awkward and brittle.
The docs app has no logged in state anyway, so for now there's no need for it to read the bk/bk session. The safest path is to just give them distinct session cookies until that becomes a problem.
In any case, the docs app currently doesn't write to the session anywhere. Setting this is a defensive move so if we start writing to the …
> ensure the session cookie for docs is different to the bk/bk session cookie

- pages/apis/rest_api/_builds_list_query_strings.md.erb
As pointed out in https://github.com/buildkite/docs/issues/645, our description for the builds API param `include_retried_jobs` isn't super clear. 
The PR updates the description to @dws-uber's words suggestion 🙌🏻 Thanks @dws-uber! 🙇🏻‍♀️
Closes #645
> Update include_retried_jobs description

- config/environments/production.rb
We're using lograge to log a single line per request and in production they come out like this:
I, [2020-04-02T10:29:20.928310 #1] INFO -- : [e9d8506d-7ccc-49d8-907f-a0381b5536e0] method=GET path=/docs/pipelines/defining-steps format=html controller=PagesController action=show status=200 duration=21.02 view=4.38
By removing this line, they lose the prefix:
method=GET path=/docs/pipelines/defining-steps format=html controller=PagesController action=show status=200 duration=21.02 view=4.38
The timestamp is unnecessary - cloudwatch records one for us.
The log level (info in this case) isn't too useful. The request ID could be useful at some point , but only if it's logged in the same format as the rest of the line. I'll look into how to achieve that.
> remove unnecessary log prefix in production

- config/environments/production.rb
the default TaggedLogging decorator prefixes log lines with the request ID, like this:
[4959e5bb-c638-4174-9219-d4310c26c8ab] method=GET path=/docs/pipelines/links-and-images-in-log-output format=html controller=PagesController action=show status=200 duration=21.12 view=4.50
We're using lograge and we just want plain, un-prefixed output to stdout, like this:
method=GET path=/docs/pipelines/links-and-images-in-log-output format=html controller=PagesController action=show status=200 duration=21.12 view=4.50
If we want to log the request ID, we can do it within the lograge format
> use a plain old logger in production

- Dockerfile
- config/initializers/assets.rb
While testing this app on fargate we were serving assets from `/docs-fargate`. However, now that this app is serving user traffic under `/docs`, we can remove the temporary asset path
> assume assets are served under /docs

- app/helpers/application_helper.rb
- app/views/layouts/application.html.erb
- config/routes.rb
- scripts/deploy-ecs
We used this prefix while testing the docs app on fargate. That fargate service is no serving production user traffic under /docs, and we don't need the testing prefix any more.
This is mostly reverting #672 and #674
> remove all mention of the /docs-fargate URL prefix

- pages/plugins/tools.md.erb
The link to the Buildkite CLI on the plugin tools page was pointing to the shellcheck plugin.
> Fix link to buildkite CLI

- pages/pipelines/defining_steps.md.erb
This removes the incorrect filename on the pipeline upload command example, so it matches the same type of examples further up the page too. In this case, this is the command to run in the pipeline.yml `command` step, not the contents of the file that generates the pipeline.
Fixes:
> Remove the filename on the dynamic pipeline upload

- app/views/layouts/application.html.erb
Fixes the following in page titles, and a few other incorrect references to page titles in our OpenGraph meta-data and what-not:
> Fix page titles

- pages/tutorials/getting_started.md.erb
Fix a typo in [Invite your team](https://buildkite.com/docs/tutorials/getting-started#invite-your-team-to-the-organization) page :)
Should be Users instead of Members.
[View updated doc on docs-review-invite-user-r8tgcf](https://docs-review-invite-user-r9tgcf.herokuapp.com/docs/tutorials/getting-started#invite-your-team-to-the-organization)
> Invite people under Users in Organization Settings

- app/models/page/renderer.rb
- pages/pipelines/environment_variables.md.erb
- spec/features/reading_pages_spec.rb
- spec/models/page/renderer_spec.rb
Makes all the `h3` elements linkable by adding an automatic id, and let's you customize the `id` and `class`.
For example, the following markdown:
```markdown
{: id="short-id"}
```
generates:
```html
<h2 id="short-id">A long complicated section description</h2>
<h3 id="short-id-subsection-1">Subsection 1</h3>
<h2 id="section-2">Section 2</h2>
<h3 id="section-2-subsection-2">Subsection 2</h3>
```
This means we can now link to individual [environment variables](https://buildkite.com/docs/pipelines/environment-variables#buildkite-environment-variables), and instead of `#buildkite-environment-variables-buildkite-agent-pid` we can have `#bk-env-vars-buildkite-agent-pid` for example.
Fixes #708
> Make h3's linkable, and provide the ability for `id` and `class` overrides

- pages/pipelines/scheduled_builds.md.erb
The documentation around `%` and `+` was causing confusion among some of our developers as it was not clear from what point the frequency is calculated (monthly, yearly, etc). After having a discussion on slack with Matthew Draper, and discovering some typos, it felt best to update the docs.
> Update schedules readme

- app/models/page/renderer.rb
- pages/pipelines/environment_variables.md.erb
- spec/features/reading_pages_spec.rb
- spec/models/page/renderer_spec.rb
Reverts buildkite/docs#710
More context in https://3.basecamp.com/3453178/buckets/1735271/messages/2629087723
TL;DR: nokogiri is taking 10-30 seconds to do its thing on https://buildkite.com/docs/pipelines/environment-variables in production and development.
Here's a flamegraph of the interesting part:
> Revert "Make h3's linkable, and provide the ability for `id` and `class` overrides"

- config/initializers/content_security_policy.rb
- deploy/task-definition-template.json
That points to our https://badge.buildkite.com.
This will fix the svg not showing on our [status badges page](https://buildkite.com/docs/integrations/build-status-badges).
> Add BADGE_DOMAIN env

- pages/agent/v3/cli_artifact.md.erb
- pages/pipelines/artifacts.md.erb
A couple of the new H3 links snuck through into master, this PR removes them for the moment. 
Keen to add them back in once we sort out a solution to the load issues with the h3s 🙌🏻
> Remove reverted h3 links

- app/assets/stylesheets/public/utils/_text_content.scss
Fixes #441 
Updated spacing: 
Note that this also applies to the TOC lists, where it's also an improvement:
> Update vertical margins on list items

- pages/pipelines/command_step.md.erb
A link in a blockquote for [Automatic Retry Attributes](https://buildkite.com/docs/pipelines/command-step#automatic-retry-attributes) had a link that was still in markdown:
The markdown links only seem to work if they are not nested under HTML, so I updated it to an HTML link like the majority of the links on the page:
> Unrendered link in Automatic Retry Attributes blockquote

- pages/agent/v2/securing.md.erb
I was browsing the guide and thought we could use more friendly terms 😊 
Trailing spaces are also gone upon save.
[Preview link](https://docs-review-update-term-u4nyis.herokuapp.com/docs/agent/v2/securing#allowing)
> Use friendlier terminology in secure agent guide v2

- pages/integrations/github_enterprise.md.erb
This is a follow-up PR of https://github.com/buildkite/buildkite/pull/5086.
* Use GitHub Enterprise Server to make it clear that the settings are for self-hosted GitHub Enterprise
* Fixed a typo of OAuth
> [Docs] Update to use GitHub Enterprise Server

- app/controllers/quick_reference_controller.rb
This will allow any domain to request and use the quick reference JSON.
> Add CORS headers to quick-reference JSON

- pages/agent/v3/osx.md.erb
So far this is just some notes, but eventually it will be full sentences and have some example code too. We already supply people with a plist, so I'm adding some explainers on how to add the --spawn option or how to dupe the whole plist. 
This PR adds a section on Running multiple agents to the macos agent installer doc, mirroring the one we've got in the Linux agent installer doc. 
Closes https://github.com/buildkite/docs/issues/730
> Add multiple agents info to the macos agent install doc

- app/views/quick_reference/pipelines.json.erb
- app/views/quick_reference/steps/_command.md.erb
- app/views/quick_reference/steps/command/_agents.md.erb
- app/views/quick_reference/steps/command/_allow_dependency_failure.md.erb
- app/views/quick_reference/steps/command/_artifact_paths.md.erb
- app/views/quick_reference/steps/command/_branches.md.erb
- app/views/quick_reference/steps/command/_command.md.erb
- app/views/quick_reference/steps/command/_concurrency.md.erb
- app/views/quick_reference/steps/command/_concurrency_group.md.erb
- app/views/quick_reference/steps/command/_depends_on.md.erb
- app/views/quick_reference/steps/command/_env.md.erb
- app/views/quick_reference/steps/command/_if.md.erb
- app/views/quick_reference/steps/command/_key.md.erb
- app/views/quick_reference/steps/command/_label.md.erb
- app/views/quick_reference/steps/command/_parallelism.md.erb
- app/views/quick_reference/steps/command/_plugins.md.erb
- app/views/quick_reference/steps/command/_retry.md.erb
- app/views/quick_reference/steps/command/_skip.md.erb
- app/views/quick_reference/steps/command/_soft_fail.md.erb
- app/views/quick_reference/steps/command/_timeout_in_minutes.md.erb
Adding more representative draft content for Command step type (mostly copied wholesale from existing docs content) to ensure there's nothing we're missing with regards to how we want to serve up and display sidebar content.
> Add draft content for Command step type

- pages/pipelines/notifications.md.erb
Adding the new `webhook` option to the notify page, thanks to @niceking! 
Same format as the email section, but with examples for webhooks.
> Add webhooks option to notification attribute

- pages/apis/graphql_api.md.erb
The links now served by relay.dev, so 1 less page jump when people clicks 😄
> Update GraphQL Relay links

- pages/plugins/_tutorial_readme.html
- pages/plugins/writing.md.erb
👋 Hi folks, I found a couple of things in the Plugin tutorial that were not clear to me - hoping these edits make it clearer for someone else!
- The configuration example references both `name` and `pattern` properties in different places. Updates to only use the `pattern` property, the value used in the hook example.
- Adds a short description of how to access the configuration values in the hook script
> Fix inconsistencies in Plugin Tutorial

- pages/pipelines/command_step.md.erb
I'm not super keen on the double negative, but I think this is an improvement. 
Is the `*` the same as `true` here? Regardless, we should pick one.
Fix for #772
> Clarification of soft-fail / timeout

- pages/pipelines/command_step.md.erb
I notice across all step types, only command steps are plural and we probably want to keep them consistent, so changed to singular command step. Also the URL is singular https://buildkite.com/docs/pipelines/command-step.
> Change to Command Step for consistency

- pages/apis/rest_api/pipelines.md.erb
We made some changes here to allow the `configuration` value to be used to set the steps in the pipeline update patch, these are just some small changes to make that a little clearer, we could possibly do an overhaul of all accept values here long term.
Changes:
Adds configuration and tip
Updates the returned value
> Update pipeline update to reflect recent changes.

- pages/pipelines/defining_steps.md.erb
Better to be consistent with the rest of the page.
> Typo: pipeline.yaml -> pipeline.yml

- pages/tutorials/parallel_builds.md.erb
Verified that `parallelism` actually works in the YAML.
> Fix typo parrallelism -> parallelism

- pages/pipelines/trigger_step.md.erb
The trigger step supports the `skip` key but it’s not documented.
> Add `skip` key to Trigger step docs

- pages/pipelines/trigger_step.md.erb
This is a followup fix for https://github.com/buildkite/docs/pull/807. In the original PR, I had misplaced the `skip` key description in the wrong section. It should have been placed under `Optional Attributes`. I accidentally placed it under "Optional `build` attributes", which is incorrect.
> Move `skip` attribute to the right section

- pages/integrations/amazon_eventbridge.md.erb
We have added the repo string and an unblocked_by object to the Eventbridge payloads, this update reflects those changes.
> update docs to reflect changes in eventbridge

- pages/agent/v2/osx.md.erb
- pages/agent/v3/install/_osx.md.erb
- pages/agent/v3/osx.md.erb
We have an issue raised in the agent https://github.com/buildkite/agent/issues/1284 around a bug with installing using brew and the config not storing the token value. From initial investigations it does not look like this is something that is going to work with changes to homebrew so this PR removes those references.
> Homebrew install does not currently work with the token argument

- pages/integrations/amazon_eventbridge.md.erb
- vale/vocab.txt
AWS published a number of EventBridge example implementations which could be very useful for people building custom Buildkite event-based integrations. This adds links to all three of them.
> Add AWS Quick Start examples

- pages/agent/v2/aws.md.erb
- pages/agent/v3/aws.md.erb
- vale/vocab.txt
Came across this guide so update it a bit.
Crosslink to RH/CentOS guide and fix typo for Cloudwatch.
> [AWS] Link to RH/CentOS and fix typo

- pages/integrations/docker_hub.md.erb
AWS published this blog post earlier today, and for Buildkite customers who use AWS it's a valuable addition to the discussion
> docker hub rate limit tips: include a link to AWS advice

- pages/pipelines/environment_variables.md.erb
Slight misname, this is just `BUILDKITE_UNBLOCKER_ID`.
> Fix incorrect environment variable name

- pages/apis/rest_api/agents.md.erb
- pages/apis/rest_api/builds.md.erb
- pages/apis/rest_api/jobs.md.erb
- pages/apis/rest_api/organizations.md.erb
- pages/apis/rest_api/pipelines.md.erb
- pages/apis/rest_api/user.md.erb
The REST API now returns this `graphql_id` field for various resources to help with people migrating over to GraphQL API.
> Add graphql_id to example responses

- pages/apis/webhooks/job_events.md.erb
This event is present on the overview page: https://buildkite.com/docs/apis/webhooks but not on the detail page: https://buildkite.com/docs/apis/webhooks/job-events
> Add job.scheduled to Job Event details docs

- pages/agent/v3/osx.md.erb
As of agent 3.26.0 we ship binaries for both Intel and M1 systems, and homebrew will automatically pick the best one to install.
> remove note on Apple Silicon support

- app/assets/stylesheets/public/_docs.scss
- app/assets/stylesheets/public/utils/_text_content.scss
Updates the colour of the inline code blocks, the sidebar subheading and any other elements using the .dark-gray class, in order to meet the 4.5:1 contrast ratio required to meet WCAG AA accessibility requirements.
> Update text contrast for accessibility

- pages/integrations/sso/okta.md.erb
Our Okta instructions were a bit out of data, and some folks were having trouble getting set up! I added a new Okta app to our test account to run through it again while I updated this doc, so it should be all good now.
This PR removes the mention of an org slug field and adds in a couple of points about adding your user account before testing.
> Update to match latest Okta app install instructions

- config/initializers/content_security_policy.rb
The `.com` ones are not behind dsn.
- appid-dsn.algolia.net
- appid-1.algolianet.com
- appid-2.algolianet.com
- appid-3.algolianet.com
https://www.algolia.com/doc/guides/scaling/distributed-search-network-dsn/#technical-details
> Update policy connect_src for Algolia

- config/initializers/content_security_policy.rb
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/connect-src
Either use `*.algolianet.com` or be specific with each host.
> Fix incorrect use of wildcard for host source

- pages/integrations/amazon_eventbridge.md.erb
Using the original example raised the following error in EventBridge:
`
Event pattern is not valid. Reason: "slug" must be an object or an array at [Source: (String)"{ "detail-type": [ "Build Started", "Build Finished" ], "detail": { "pipeline": { "slug": "some-pipeline" } } }"; line: 5, column: 16]
`
It turns out the correct pattern is `"pipeline": { "slug": [ "some-pipeline" ] }` according to [Event Patterns docs](https://docs.aws.amazon.com/eventbridge/latest/userguide/filtering-examples-structure.html)
> [Amazon EventBridge] Fix event pattern rule

- Rakefile
If the sed command doesn't find a match it would push to production. :-(
The new jq command explicitly replaces the value of `index_name`, which seems better.
> Safer index selection

- config/algolia.json
Make sure that old agent v2 posts aren't indexed. The starting `/` was preventing the match.
https://docsearch.algolia.com/docs/config-file/#stop_urls-optional
> Tweak agent v2 indexing

- pages/plugins/writing.md.erb
This primarily fixes the stub syntax in the Writing Plugins guide, which was incorrect, as well as adding a few missing filenames to the code blocks.
Fixes #868
> Fix the stub example in the Writing Plugins guide

- app/assets/stylesheets/public/_docs.scss
- pages/agent/v3/docker.md.erb
- pages/agent/v3/osx.md.erb
- pages/agent/v3/securing.md.erb
- pages/apis/rest_api.md.erb
- pages/apis/rest_api/artifacts.md.erb
- pages/apis/rest_api/pipelines.md.erb
- pages/pipelines/branch_configuration.md.erb
- pages/pipelines/conditionals.md.erb
- pages/pipelines/controlling_concurrency.md.erb
- pages/pipelines/dependencies.md.erb
- pages/pipelines/environment_variables.md.erb
- pages/pipelines/ignoring_a_commit.md.erb
- pages/pipelines/my_builds.md.erb
- pages/pipelines/writing_build_scripts.md.erb
Update stylesheet and content for the orange troubleshooting headers from H1s (typically used once on a page, for page title) to H3s.
Resolves #878
> Update troubleshooting headers from h1s to h3s

- pages/tutorials/bazel.md.erb
Previously all Bazel documentation links pointed to the docs for Bazel 2.2.0, which was released in March 2020 and is thus unlikely to be used by people new to Buildkite & Bazel. Consequently, this PR changes the links to always point to the documentation of the *latest* Bazel release.
> Link to docs of the latest Bazel release

- Dockerfile
This fixes the following error:
```
GPG error: http://dl.yarnpkg.com/debian stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 23E7166788B63E1E
```
which is currently breaking our build 😅
> Fix yarn error building docker image

- pages/pipelines/defining_steps.md.erb
This fixes the single issue.
we should be able to implement a vale rule a little like
```yml
extends: existence
message: You need to escape emoji colons in codeblocks
level: error
nonword: True
scope: code
tokens:
- ':[a-z]*:'
```
to check for this, but it currently detects emoji that aren't in codeblocks as well. :-(
> Escape emoji in codeblock

- pages/pipelines/defining_steps.md.erb
- pages/pipelines/example_pipelines.md.erb
Make things easier to find.
See https://forum.buildkite.community/t/how-to-restrict-steps-to-specific-agents/1411
Are we ok to just link to the example in the gist? Seems overkill to add a repo for it.
> Highlight Agent targeting

- Dockerfile
Reverts buildkite/docs#913
The original `ADD` command should have noticed the update, but didn't for some reason, so the change to a `RUN` busted the cache. But the `RUN` will never have the opportunity to notice upstream changes and so will cause the same problem in the future, whereas the `ADD` should notice updates and also creates lighter layers and maintains consistency.
> Revert "Fix yarn error building docker image"

- pages/plugins/_tutorial_readme.html
This error had been fixed in other places on the tutorial, but I ran the linter and found we are getting errors in the README.md
```
Creating file-counter-buildkite-plugin_lint_run ... done
TAP version 13
ok 1 - plugin.yml is valid
not ok 2 - Plugins list should be an array, not a map
---
example:
steps:
- command: ls
plugins:
a-github-user/file-counter#v1.0.0:
pattern: "*.md"
...
```
> Fix - plugins list should be an array error

- pages/agent/v3/debian.md.erb
- pages/agent/v3/freebsd.md.erb
- pages/agent/v3/linux.md.erb
- pages/agent/v3/osx.md.erb
- pages/agent/v3/redhat.md.erb
- pages/agent/v3/ubuntu.md.erb
- pages/agent/v3/windows.md.erb
Added links to clarify where to find the agent token to pages that dealt with OSystems.
> Agent token links for OS pages

- pages/agent/v3/debian.md.erb
- pages/agent/v3/redhat.md.erb
- pages/agent/v3/ubuntu.md.erb
Add `unstable`, `experimental` installation options to Debian, Ubuntu and Red Hat.
Add `aarch64` to Red Hat.
Fixes #775 
Fixes #774
> Update installation instructions

- pages/plugins/writing.md.erb
New changes are lines 47-54,
the rest is content moved around to be more clear.
Fixes #588
> Mention .git referenced env vars

- pages/agent/v3/configuration.md.erb
- pages/pipelines/environment_variables.md.erb
Referencing recent agent release (3.27.0) and https://github.com/buildkite/agent/pull/1273
> Provide tracing-datadog-addr option

- pages/plugins/writing.md.erb
Fails with `bash: PWD: command not found`.  Should either be $PWD or
$(pwd), I've opted for the former.
> Fix invalid command substitution in plugin docs.

- pages/apis/rest_api/meta.md.erb
> Fix typo of meta endpoint

- pages/apis/rest_api/meta.md.erb
Also clarify that the Meta API might grow more properties which describe Buildkite over time as required.
> Clarify IP address policy in meta api docs

- app/views/layouts/application.html.erb
- pages/agent/v3/cli_annotate.md.erb
- pages/agent/v3/cli_annotation.md.erb
- pages/agent/v3/help/_annotation_remove.txt
Note that the referenced v3.28.0 agent version doesn't exist yet, so this shouldn't be merged until we've made a call on releasing that version.
Context: buildkite/agent#1364, buildkite/buildkite#5948.
> Add documentation for the `buildkite-agent annotation remove` command.

- pages/agent/v3/help/_annotation_remove.txt
- pages/agent/v3/help/_bootstrap.txt
- pages/agent/v3/help/_start.txt
- scripts/update-agent-help.sh
Following on from #954, this updates the docs for [v3.28.1](https://github.com/buildkite/agent/releases/tag/v3.28.1) of the Agent
> Update command help for agent 3.28.1

- pages/agent/v3/gcloud.md.erb
Our GKE docs suggest a kubernetes Deployment with type "extensions/v1beta1/Deployment", however Deployments moved to "apps/v1/Deployment" sometime ago and the old namespace is [unavailable from kuberentes 1.16](https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/) (released mid 2019).
Our GKE docs in general are a bit dated and need an overhaul, but this is a worthwhile quick-fix that'll save customers hitting a confusing error.
I've also added matchLabels, because I think Deployment's are supposed to have them.
This diff is mostly whitespace - I recommend viewing [with whitespace changes hidden](https://github.com/buildkite/docs/pull/973/files?diff=split&w=1).
> Update suggested manifest for deploying the agent to GKE

- pages/pipelines/managing_log_output.md.erb
I just [noticed](https://github.com/buildkite/docs/pull/966/files#r599194738) the docs say `experiment="redacted-vars"` rather than `experiment="output-redactor"`:
```go
if experiments.IsEnabled("output-redactor") {
```
https://github.com/buildkite/agent/blob/decbc9df4ecad2004ad4ed0cc8af8d18582f2106/bootstrap/bootstrap.go#L1804
> Managing Log Output: fix output-redactor experiment name

- app/models/page.rb
- config/initializers/bugsnag.rb
- config/routes.rb
- pages/agent/v3/cli_annotate.md.erb
- pages/agent/v3/cli_annotation.md.erb
- pages/agent/v3/cli_artifact.md.erb
- pages/agent/v3/cli_bootstrap.md.erb
- pages/agent/v3/cli_meta_data.md.erb
- pages/agent/v3/cli_pipeline.md.erb
- pages/agent/v3/cli_start.md.erb
- pages/agent/v3/cli_step.md.erb
The rails development log was full of junk, so @yob and I paired on trimming it.
If anyone knows *exactly* what is going on with the arguments in `app/models/page.rb` might be good to know, otherwise it seems to work and tests pass :-p.
* Stop Bugsnag complaining about an api key `config/initializers/bugsnag.rb`
* Stop Rails 6 complaining about `.` in render in `app/models/page.rb` and update docs to match in `pages/*`
* Stop CSP noise in `config/routes.rb`
> Fix Deprecation warnings

- config/initializers/trailing_slash_middleware.rb
- spec/requests/remove_trailing_slashes_middleware_spec.rb
In our ahrefs.com SEO site audit report it shows that we're internally linking to both https://buildkite.com/docs/pipelines and https://buildkite.com/docs/pipelines/ but don't set any canonical URL, so we're leaving up to search engines to figure out what the right URL is.
https://help.ahrefs.com/en/articles/2596742-duplicate-pages-without-canonical-error-in-site-audit
This adds a 301 redirect rule to ensure we only have a single URL for a unique page on the docs.
> 301 redirect paths with trailing slashes

- app/assets/stylesheets/public/_docs.scss
- pages/pipelines/managing_log_output.md.erb
The requirement here was a style to flag when a given feature was experimental/WIP.
Turns out there was an existing style there for pretty much exactly this use case — it wasn't in use anywhere, so I've refactored it very slightly to avoid a dependence on its headings being H1's, and have updated the existing example page ("Managing Log Output") to use this class instead.
> Add styling for Experimental/WIP feature callouts

- .alexrc.yml
- README.md
- package.json
- pages/agent/v2/aws.md.erb
- pages/agent/v2/cli_artifact.md.erb
- pages/agent/v2/docker.md.erb
- pages/agent/v2/freebsd.md.erb
- pages/agent/v2/github_ssh_keys.md.erb
- pages/agent/v2/installation.md.erb
- pages/agent/v2/linux.md.erb
- pages/agent/v2/osx.md.erb
- pages/agent/v2/queues.md.erb
- pages/agent/v2/upgrading_to_v2.md.erb
- pages/agent/v2/upgrading_to_v3.md.erb
- pages/agent/v3/aws.md.erb
- pages/agent/v3/cli_artifact.md.erb
- pages/agent/v3/cli_step.md.erb
- pages/agent/v3/freebsd.md.erb
- pages/agent/v3/github_ssh_keys.md.erb
- pages/agent/v3/installation.md.erb
- pages/agent/v3/linux.md.erb
- pages/agent/v3/osx.md.erb
- pages/agent/v3/tokens.md.erb
- pages/apis/webhooks/integrations.md.erb
- pages/deployments.md.erb
- pages/pipelines.md.erb
Pronfanity has been there forever I think. Who lints the linters?
More importantly, the missing quotes around the regex do affect things badly, and leaves us an extra 25 "simply" type things to fix up. 
When we're done we can add the `--diff` back, so it only runs on changed files.
> Fix errors in linter

- pages/pipelines/block_step.md.erb
While setting up dependencies for steps, I found this article which describes an undocumented feature of the block step.
https://forum.buildkite.community/t/step-dependencies-and-block/862
I added in a basic row to call this out
> adding in missing documentation for using a key as part of a block step

- pages/pipelines/dependencies.md.erb
Adding an example of using block _without_ input fields to set subsequent dependencies
> Adding an example using depends_on with block steps

- pages/pipelines/conditionals.md.erb
It looks like `build.state` has been around a while as a conditional, no idea how I managed to leave it off the list 😅 😬
This PR adds the state conditional to the 'Supported Variables' section of the Using Conditionals page. It is already used in examples on the Notifications page.
> Add build.state to conditional list

- config/algolia.json
When I pushed [the update to the sidebar](https://github.com/buildkite/docs/pull/999) last week, the changes in markup broke our Algolia config, and gave us useless categories that look like this:
This PR updates the selector that Algolia uses to determine the `lvl0` (ie, root category) for a given record, to match the current markup. Algolia should then update and go back to normal the next time its scraper runs (which happens ["every 24 hours"](https://docsearch.algolia.com/docs/scraper)).
I've also manually excluded the content categories that live on the new docs landing page, so they won't be indexed for search.
> Update Algolia config to match new sidebar structure

- pages/agent/v3/cli_annotate.md.erb
I believe the sense of the documentation could be improved by this PR.
I know there is debate whether to use singular or plural verbs when referring to a company's actions, but according to the sources cited [here](https://www.grammarphobia.com/blog/2018/01/it-or-they.html), British English allows either singular or plural and American English uses singular verbs "unless you wish to emphasize the individuals who make up the organization; in that case, use the plural" (quoted [here](https://www.grammarphobia.com/blog/2018/01/it-or-they.html)).
> Fixing minor typo in docs

- app/views/layouts/_sidebar.html.erb
The selector I used for the fix from last week in #1014 worked fine client-side, but the logic to add the "current" class to the relevant sidebar content was in javascript, so wasn't getting triggered by Algolia's crawler. 
This PR shifts that logic and to happen server-side, which makes the markup a little more complex, but should resolve the Algolia issue properly and let it determine categories again.
> Algolia fix, part two: Add class to each sidebar container based on path match

- pages/integrations/source_control.md.erb
I missed a menu when adding the bitbucket server docs: https://buildkite.com/docs/integrations/source-control
> add bitbucket server to the list on source_control

- pages/apis/rest_api/pipelines.md.erb
This PR replaces #1013
The env key in the returned body does show env vars *if* you supply them in the YAML. I've added an example there, and removed the `env` parameter that doesn't work in the request. The `env` paramter does still work if you're creating a visual pipeline.
Let me know if if anything is still unclear @unrealcloud
> Clarify env vars in YAML pipelines

- vale/vocab.txt
Yes, there is such a word & it is featured in one of the documents 3 times, with no way to create a less wordy workaround.
> Adding 'sandboxed' to vocabulary

- pages/integrations/github_enterprise.md.erb
The docs for GitHub Enterprise Firewalled Installations referenced one
specific IP address, which I think is the old egress IP address from
before [the new IPs](https://buildkite.com/changelog/118-new-outbound-ip-addresses) were
allocated.
This PR adds the new (current) IPs, as well as a reference to where one
can find the updated list (the meta API)
> Update GHEnterprise Firewalled Installation IP

- pages/agent/v3/configuration.md.erb
These are sent in milliseconds according to the agent codebase, however without trawling through a bunch of Go this is not very clear.
> Mention Datadog metric unit

- app/assets/stylesheets/public/_docs.scss
- app/assets/stylesheets/public/_site_header.scss
- app/assets/stylesheets/public/utils/_standard_top_section.scss
- app/views/layouts/_sidebar.html.erb
- app/views/layouts/application.html.erb
- app/views/layouts/homepage.html.erb
- app/views/pages/index.html.erb
- pages/agent/v3/configuration.md.erb
- public/404.html
This PR cleans up a number of warnings from Google Lighthouse that I spotted when viewing the Google crawler warnings for our site via Google Search Console.
The biggest change is that it improves the navigation on mobile, so it isn't as large and expanded by default… which means people can get to the documentation they're reading much faster (especially when navigating between pages, which would involving scrolling past the navigation each time).
| Before | After |
| -- | -- |
| <img width="855" alt="image" src="https://user-images.githubusercontent.com/153/120432020-a6860100-c3bc-11eb-8232-76bc16851caa.png"> | <img width="855" alt="image" src="https://user-images.githubusercontent.com/153/120432037-aab21e80-c3bc-11eb-8e06-e75c3476a52c.png"> |
It also makes sure the up arrow is available …
> Mobile experience improvements (and other Google lighthouse fixups)

- pages/apis/rest_api/pipelines.md.erb
I've just added a [new REST endpoint](https://github.com/buildkite/buildkite/pull/6615) for archiving a pipeline, so here's the documentation for it
> Document the new archive pipeline endpoint

- pages/agent/v3/debian.md.erb
- pages/agent/v3/osx.md.erb
- pages/agent/v3/redhat.md.erb
- pages/agent/v3/ubuntu.md.erb
- pages/agent/v3/windows.md.erb
This changes the docs for each operating system (I only changed the agent v3 docs and didn’t touch the v2 ones) to steer folks towards which operating systems we support rather than the oldest operating system the agent can be installed on.
This doesn’t practically change where the agent can be installed, e.g. it probably still works on Windows XP we’re just saying that if it _happens to_ we can’t guarantee support when it goes wrong as we have to focus our efforts.
For Debian, Red Hat, and Ubuntu we can also drop the docs for using Upstart, as presently in service and supported versions of these all use systemd 🎉
> Update agent OS support policy

- app/views/layouts/_sidebar.html.erb
- pages/agent/v3/aws/secrets_manager.md
- vale/vocab.txt
This adds a guide for using AWS Secrets Manager to store (and potentially multi-region replicate) your Buildkite Agent token.
I put this in an Agent > v3 > AWS but haven’t linked to it or inserted it into the sidebar hierarchy yet and thought I’d leave that up to the fine docs folks to find a home for it that fits in with how you want to structure things for the Elastic CI Stack(s) going forward 😊
Moved from https://github.com/buildkite/elastic-ci-stack-for-aws/pull/855
> Add AWS Secrets manager guide

- pages/agent/v3.md.erb
- pages/agent/v3/configuration.md.erb
- pages/pipelines/managing_log_output.md.erb
This will land as default feature in v3.31 so we can remove the experimental caveats from these docs.
@plaindocs should we note the agent minimum version required for the feature anywhere?
> Remove 'experiment' from output redactor docs

- pages/agent/v3/aws/secrets_manager.md
I missed this in my first pass on these because I used a static auto scale group of one instance and only tested that the agent booted. To allow the scaling Lambda to poll the Buildkite API when using a token in Secrets Manager we also need to grant permission to the Lambda execution role.
cc @lox
> Update secretmanager docs to include adding permission for the scaling lambda role

- pages/tutorials/parallel_builds.md.erb
This was renamed and the repository moved. GitHub does redirect but it’s better to link to our actual repository.
> Rename and link buildkite-metrics to buildkite-agent-metrics

- README.md
Added a little more detail, to flag Ruby versions and Node requirement.
Have also spelled out need to be in docs directory - possibly too basic for our users though?
Also: I never got it running on Windows directly, had to resort to WSL. Wondering if we should flag this? You might get another windows user in a year or two . . .
> updated details on running locally

- pages/apis/webhooks.md.erb
Update the Webhook doc to include information about the new `X-Buildkite-Signature` header and how to verify signatures
> Update docs on webhooks

- pages/apis/webhooks.md.erb
I was writing the changelog for HMAC this evening and thought that we needed some more info in the docs section. 
In this PR I have:
- Split out the HTTP Headers table into two sections so that I could add an intro to say that token and signature are an either/or deal
- Capitalised the title and fixed some formatting in the note block of HTTP Request body
- Added a section for webhook tokens so that I could mention that they're passed in clear text
- Renamed the verifying signatures section to the broader 'Webhook Signature'
- Reformatted/expanded/simplified the intro paragraphs about signatures
- Add info about where to find the signature/token settings in the BK UI
- Added a new subheading for the info about verifying signatures
- Added a text description of the steps to verify that …
> Update and expand HMAC docs

- pages/agent/v2/cli_artifact.md.erb
- pages/agent/v2/gcloud.md.erb
- pages/agent/v3/gcloud.md.erb
- pages/apis/managing_api_tokens.md.erb
- pages/pipelines/conditionals.md.erb
- pages/pipelines/example_pipelines.md.erb
- vale/vocab.txt
Super interesting tool called codespell that finds common spelling errors, rather than comparing files to a dictionary.
` ~/.local/bin/codespell -L iterm pages/`
From https://til.simonwillison.net/python/codespell
> Typo fixes

- pages/agent/v2/_apt_locations.md.erb
- pages/agent/v2/cli_artifact.md.erb
- pages/agent/v2/freebsd.md.erb
- pages/agent/v2/linux.md.erb
- pages/agent/v2/osx.md.erb
- pages/agent/v2/redhat.md.erb
- pages/agent/v3/_apt_locations.md.erb
- pages/agent/v3/cli_artifact.md.erb
- pages/agent/v3/configuration.md.erb
- pages/agent/v3/docker.md.erb
- pages/agent/v3/freebsd.md.erb
- pages/agent/v3/hooks.md.erb
- pages/agent/v3/linux.md.erb
- pages/agent/v3/macos.md.erb
- pages/agent/v3/redhat.md.erb
- pages/agent/v3/securing.md.erb
- pages/agent/v3/ssh_keys.md.erb
- pages/agent/v3/windows.md.erb
- pages/apis/rest_api/metrics.md.erb
- pages/integrations/bitbucket.md.erb
- pages/pipelines/environment_variables.md.erb
- pages/pipelines/permissions.md.erb
- pages/pipelines/secrets.md.erb
- pages/pipelines/writing_build_scripts.md.erb
- pages/plugins/using.md.erb
- pages/tutorials/docker_containerized_builds.md.erb
Presently, the term **agent hooks** can be used to refer to either the _buildkite-agent feature_ or the _location that hooks are stored in the file system_.
With the new `pre-bootstrap` and arguably `agent-shutdown` hooks we have introduced a new _category_ of hook, one that is run outside the step/job lifecycle and that is _executed_ rather than _sourced_.
I’d like to make that distinction clear and think introducing new terminology is the way to do that.
This feels like a significant change to the product area. ~I’m **not** tied to this particular terminology or this particular slicing of things, but I wanted to have something written down for us to discuss pros and cons 😄~ Edit: I have since discussed this with others and am fairly tied to this new naming. How I’ve named and sliced …
> Differentiate agent lifecycle vs job lifecycle hooks

- app/assets/stylesheets/public/_variables.scss
- app/assets/stylesheets/public/utils/_link.scss
- app/assets/stylesheets/public/utils/_text_content.scss
- app/models/page/renderer.rb
The links in the app were imported from Buildkite app in 2019 and
haven't been updated since.
We had an issue with `code` that are links or part of link text looking
odd or not consistently like a link. This commit re-styles links across
the whole site (!) but makes them consistent, including those with
`code`.
The main side-effect of these changes is that all links now have underlines. Except the sidebar menu links. These now highlight with the brand green for consistency. If any of this is a step too far, please let me know!
> Improve link styles

- app/assets/stylesheets/public/utils/_text_content.scss
- pages/pipelines/defining_steps.md.erb
> Update table styling for more flexibility

- app/assets/stylesheets/public/utils/_text_content.scss
Sometimes we want to make lists more compact by spreading them out in
columns. On small screens (<500px) these will revert to a single column.
Technically this is just a class and so could be used on any element. It'll apply a basic columnar CSS Grid.
These examples are just for the screenshots, I didn't actually commit the addition of these classes to this list:
> Update list styling to make columns possible

- app/assets/stylesheets/public/_docs.scss
Resolves #1147 
The third one down shows the hover state.
> Style the example repo links to look better with the new link styles

- deploy/task-definition-template.json
I've noticed the steady state for the docs Fargate tasks has memory utilization on ~95%. That seems a little close to the wire, so I've doubled the available memory.
CPU utilization is mostly OK,  but we do get occasional spikes up nearly 100%. Docs are important, I reckon it's reasonable to give them a full core to work with in each task.
> increase the CPU and memory we have available on ECS/Fargate

- pages/integrations/pagerduty.md.erb
Now that PagerDuty have [nicer Change Events docs](https://support.pagerduty.com/docs/change-events) we should link to it, so this updates our integration guide to use that, as well as updating our support email address.
> Small PagerDuty Change Events integration link improvements

- pages/plugins/writing.md.erb
1. The `tests: ...` line is unnecessary and causes an error if pasted directly into the file. IMO better to omit as we'll be adding tests below anyway.
2. Missing space between words in line 220
> minor formatting update

- pages/integrations/sso/okta.md.erb
The Okta SSO code stuffs are ready to be announced and our "in-progress" note on the guide can be removed 🎉 I've also popped an extra heading in there so that the SAML part of it is a bit more noticable.
> Remove the "in-progress" note from Okta SSO

- pages/integrations/sso/azure_ad.md.erb
- pages/integrations/sso/okta.md.erb
Adding/updating the words about the Enterprise account gating for the SCIM providers - Okta and AzureAD.
I've also moved the note under the Okta Supported Features into its own note block.
> Add words about enterprise-only to SCIM guides

- app/assets/stylesheets/public/utils/_text_content.scss
Nested ordered lists in Markdown weren't numbered. And the whitespace was inconsistent beween ordered and unordered lists when nesting. This PR corrects both.
Mobile list styles are unaffected (as in they're consistent with these changes).
> Tidying up nested lists for uniform styling and whitespace

- pages/tutorials/getting_started.md.erb
Using a private repository --> Use a private repository
For consistency's sake (Install, Add, Invite, Use in headings).
This fix was supposed to be merged alongside the Enterprise description but goes solo while that one is on hold.
> Tiny consistency fix

- pages/agent/v3/aws.md.erb
- pages/agent/v3/elastic_mac_aws/autoscaling_mac_metal.md.erb
This was missing from the elastic-mac and non-elastic-mac docs. Disabling system sleep shouldn’t be required in elastic-mac with https://github.com/buildkite/elastic-mac-for-aws/pull/2.
> Add instruction to disable the screen saver and system sleep

- pages/tutorials/elastic_ci_stack_aws.md.erb
We build these AMI and mark them as public for customers to boot instances with.
> Clarify AMIs don’t have to be built

- pages/agent/v3/configuration.md.erb
- pages/apis/rest_api/builds.md.erb
- pages/integrations/github.md.erb
This adds a section about a quirk when triggering builds against tags through the API or a schedule (anything but a webhook from GitHub).
The section looks like:
I also updated the agent configuration page in the `BUILDKITE_GIT_FETCH_FLAGS` section to link to this page and the same from the API page for creating a build section
> Add documentation for quirks when building tags

- pages/agent/v3/macos.md.erb
Add option of using `buildkite-agent.cfg` file to launch multiple agents on MacOS (already mentioned for the others SO).
> Update running multiple agents on MacOS

- pages/apis/graphql_api.md.erb
This adds a link to the cookbook from the overview page.
Something weird is happening when I try build and test this - even though it just worked last week. I'll try get back to that to figure it out soon
> Add link to GraphQL cookbook from GraphQL overview page

- pages/pipelines/group_step.md.erb
Following https://forum.buildkite.community/t/group-steps-missing-commands/1790, updating the example to reflect the fact that `commands` does work in group step.
> Update group step documentation with `commands` use examples

- pages/pipelines/links_and_images_in_log_output.md.erb
This adds a note about inlining private artifacts in log output. It either needs to be base64 encoded or uploaded to a public location.
The note looks like:
I wasn't sure if it should be rendered with this class. Let me know
> Add note about inlining private artifacts

- pages/pipelines/notifications.md.erb
- pages/pipelines/wait_step.md.erb
Removed the statement about 'build.state' (as it was focussed on one particular if-condition) and replaced it with a statement about all supported variables for the 'if' attribute.
This is for: https://trello.com/c/BdNUeiy6/406-from-helpscout-general-zsperske-hello-im-wondering-if-it-is-possible-to-set-up-email-notifications-when
**Now:**
**In the PR:**
> Added about 'Supported variables' for 'if' attribute

- pages/pipelines/_block_wait.md.erb
- pages/pipelines/block_step.md.erb
- pages/pipelines/wait_step.md.erb
Added about wait and block steps when they are placed one after another.
Issue context: When a wait step is surrounded by a block step, the wait step is ignored. This has been previously reported by our customers a few times. So updating in our docs, so it is obvious that it's a limitation.
Here is the most recent observation from our customer: https://secure.helpscout.net/conversation/1696682218/27449/
**The following section is added in the PR:**
> Adding info about wait and block steps when they are placed together

- pages/pipelines/conditionals.md.erb
This adds a note section to the conditional page to let users know conditionals are evaluated at pipeline upload time. 
Eg:
I had a hard time trying to decide whether this is a note or just a normal paragraph or sentence somewhere else in the page. 
And also whether an example is useful. But I couldn't think of one either.
Let me know what you think and if it needs more/restructuring.
> Add note about when conditionals are evaluated

- pages/integrations/amazon_eventbridge.md.erb
Added references to Build and Job states to the amazon eventbridge page
In the PR:
> added reference to Job and Build states to the amazon eventbride page

- pages/agent/v3/configuration.md.erb
The default value for the configuration `no-plugin-validation` is actually [true](https://github.com/buildkite/agent/blob/5335389cb4649b86b6478ac542a40480500c6cca/clicommand/agent_start.go#L389). Change the default behavior on the agent would be more problematic than it seems, so we are updating the docs according in the meantime.
So if you actually want to have plugin validation you should specify `--no-plugin-validation=false` (the double-negative is confusing)
> no-plugin-validation default value

- pages/pipelines/writing_build_scripts.md.erb
Brief one-liner example added to the `Unbound variable errors` warning message to show an example of usage to https://buildkite.com/docs/pipelines/writing-build-scripts#configuring-bash
Current:
Updated:
> add example usage for wrapping shell commands in set

- pages/apis/rest_api/builds.md.erb
- Add a clarification on builds timestamp attribute:
> Timestamp attribute

- pages/pipelines/conditionals.md.erb
We always get questions around executing a step conditionally based on the result of another step. This is not directly possible using the if-conditionals. But we do achieve this by checking the result of the previous step in an ‘if’ condition **within a ‘command’ step** and then adding the other steps into the pipeline.
Please change the words/phrases as needed :)
Added the following in the PR:
> About executing step conditionally based on the result of another step

- .alexrc.yml
- pages/agent/v3/securing.md.erb
This clarifies the purpose of the `BUILDKITE_NO_COMMAND_EVAL` option.
It adds this section:
> Clarify the purpose of BUILDKITE_NO_COMMAND_EVAL

- pages/pipelines/managing_priorities.md.erb
Add a note that the value of `scheduled_at` in Job Prioritization that cannot be changed.
> Clarification about scheduled_at

- pages/pipelines/managing_log_output.md.erb
I added a note that by default the last group it's going to be expanded (always)
I didn't mention a workaround for this, but if someone wants that **all** groups to be collapsed, an option is to add a new group that does nothing.
> Note about default expanded group

- pages/apis/webhooks.md.erb
- pages/apis/webhooks/_agent_events_table.md.erb
- pages/apis/webhooks/agent_events.md.erb
- pages/integrations/amazon_eventbridge.md.erb
- vale/vocab.txt
Turns agent events into reusable snippet & updated the Amazon EventBridge documentation page.
> Reuse descriptions of agent events

- Dockerfile
I _think_ this does the right thing.
With the original code:
And with the PR:
> Remove deprecated bundler option

- pages/agent/v3/configuration.md.erb
The agent code actually lists the `build-path` configuration option as required but the documentation for it is listed under optional. So this moves it to the required section.
See https://github.com/buildkite/agent/blob/6d052d212ab633e37bdd023a8c17e6a7d955402f/clicommand/agent_start.go#L65
Also mention `BUILDKITE_AGENT_CONFIG` env var for specifying configuration file location.
> Move `build-path` agent config to required attributes

- app/assets/stylesheets/public/_docs.scss
- app/assets/stylesheets/public/_site_header.scss
- app/views/layouts/_sidebar.html.erb
This fixes DOC-180: https://linear.app/buildkite/issue/DOC-180/hide-site-menu-on-mobile
Let me know how you feel about thickness of the lines, the animation, and the speed of transition.
I've deliberately not done any extra styling to the menu as yet to keep this small, but we can always adjust the look of it too.
> DOC-180: Add hamburger menu for small screens

- pages/pipelines/group_step.md.erb
These attributes currently do nothing when used with the group step.
> Remove invalid group step attributes

- pages/deployments/deploying_to_heroku.md.erb
- pages/deployments/deploying_to_kubernetes.md.erb
And provide a one-sentence explanation before the TOC.
> Remove estimated time icon from the Deploying to Kubernetes page

- pages/pipelines/conditionals.md.erb
The "fixed state" is only supported for notification services  & means that a build passed, but the previous build on the same branch failed. Adding a note about it as a follow up to https://github.com/buildkite/docs/issues/1329
> Note on fixed state

- pages/pipelines/group_step.md.erb
Doc says "If you upload a pipeline that has a group or label already present in your YAML configuration file, the groups will be merged together in the Buildkite UI"
But group merge happens only when the group name in the child pipeline is same as the group name that uploaded this pipeline and not when this group is already present.
So updated the doc as below. Please feel free to change the words for anything better :)
Now:
In the PR:
> updated group merging info

- pages/pipelines/controlling_concurrency.md.erb
This is just to start adding some extra clarity around concurrency groups
> add some extra explanation around concurrency groups

- pages/pipelines/command_step.md.erb
There has been some confusion about a default value for the `concurrency` attribute when trying to define a concurrency group. Both `concurrency` and `concurrency_group` must be specified for it to work, and there is no error if one is omitted. This attempts to clarify that.
Existing page: https://buildkite.com/docs/pipelines/command-step
Before:
After:
Perhaps the API should enforce this but for now, a docs update would be good. I'm not sure if this change makes enough sense or whether we should add more to the `concurrency` row on this page to say something like: 
| There is no default value. You must specify a limit for concurrency limits to take effect.
> Clarify `concurrency` must be used with `concurrency_group`

- pages/agent/v2/debian.md.erb
- pages/agent/v2/ubuntu.md.erb
- pages/agent/v3/debian.md.erb
- pages/agent/v3/ubuntu.md.erb
@yob would you mind casting an eye on this when you have a moment (no rush)
Probably worth applying to the `Dockerfile` as well, what do you think? 
Context https://blog.cloudflare.com/dont-use-apt-key/
> Deprecate apt-key

- pages/agent/v3/windows.md.erb
We had a ticket today asking for the format of the shell path. So updated the doc for future users.
Now:
In the PR:
> Added real example path to powershell

- pages/pipelines/environment_variables.md.erb
BUILDKITE_BUILD_NUMBER can be accessed if interpolated at runtime when using YAML editor. Added this clarification to the doc and also updated the flow a little.
> Added details on how to access buildkite-build-number when using YAML editor

- pages/integrations/cc_menu.md.erb
- vale/vocab.txt
Let's merge this fix for the time being. The reason why CCTray refuses to cooperate is still unknown.
> Prettify the link that was colliding with navbar

- pages/agent/v3/cli_pipeline.md.erb
The insertion order section applies to the pipeline upload command and not to the environment subsection so I have moved it out and increased its header.
Docs page: https://buildkite.com/docs/agent/v3/cli-pipeline#environment-variable-substitution-insertion-order
Before:
After:
> Move insertion order section out from environment section

- app/assets/stylesheets/public/_docs.scss
This also changes the margin behaviour on last-child `p` elements in
attribute tables.
This fixes DOC-236: https://linear.app/buildkite/issue/DOC-236/experiment-feature-margins-too-large-inside-tables
> Update margins on Experiment Feature blocks inside attribute tables

- pages/pipelines/managing_log_output.md.erb
This adds instruction on how to enable a private location for build log archives in AWS S3. Only applicable to Enterprise users.
> Private S3 location for build log archives

- app/controllers/quick_reference_controller.rb
The sidebar content for the in-product Steps Editor (shown below) is sourced from the docs app, with the root pages specified in `app/controllers/quick_reference_controller.rb`.
This adds the new `group_step` type to the list of top-level pages, it renders successfully at `/docs/quick-reference/pipelines.json`, though some of the content might need an additional set of eyes (ie, the description looks more verbose than for other step types)
> Add group_step to the quick reference controller

- pages/pipelines/command_step.md.erb
- pages/pipelines/group_step.md.erb
Removed the extra colon from the group and command steps.
> Remove an extra character from attribute examples

- pages/pipelines/managing_log_output.md.erb
This made the example policy wrong:
https://buildkite.com/docs/pipelines/managing-log-output#private-build-log-archive-storage
verified fixed: https://docs-review-pr-1377.herokuapp.com/docs/pipelines/managing-log-output#private-build-log-archive-storage
> Fix wrong escape of the colon in example policy

- pages/apis/rest_api/artifacts.md.erb
Update the Artifacts REST API docs to mention the `expired` state that was introduced late last year.
Artifacts hosted by Buildkite become `expired` after six months.
> Artifact has an expired state

- pages/pipelines/notifications.md.erb
The misaligned `YAML` for the heredoc causes the example code to fail.
Fixing the alignment resolves the issue and the example build runs as expected.
> Update YAML heredoc in `notifications.md.erb`

- pages/apis/rest_api/jobs.md.erb
Jobs in the REST API (and also outbound webhooks) now have a new field:
```
"retry_type": "automatic" | "manual" | null
```
I don't think we have such granular field-level documentation that there's somewhere to add more details, but this PR at least adds it to the one example response that also has `"retried": "true"` etc.
The Job Webhook Events docs link back to this Jobs REST API doc for details, so nothing to update over there.
> Jobs REST API has retry_type attribute.

- pages/integrations/sso/_saml_user_attributes.md.erb
This resolves [DOC-286](https://linear.app/buildkite/issue/DOC-286):
https://linear.app/buildkite/issue/DOC-286/render-issue-for-team-settings-reference-in-saml-attributes-table
> Fixing `em` render issue for OKTA SSO SAML table

- Gemfile
- Gemfile.lock
Heroku build previews were breaking because it wasn't using `.ruby-version`. This does mean we have two places to update the Ruby version though. :/
> Add Ruby to Gemfile

- app/assets/stylesheets/public/_docs.scss
This resolves DOC-221:
https://linear.app/buildkite/issue/DOC-221/toc-fixes
- Increased font-size to 16px
- Removed link underline
- Changed font colour to the same grey as the sidebar menu
> Styling RH TOC to be more like sidebar menu

- Dockerfile
- Gemfile
Heroku wants it in the Gemfile, we want it in `.ruby-version` and to only update it in one place.
> Update Gemfile to read version from `.ruby-version`

- pages/pipelines/build_matrix.md.erb
Reading through the docs on this great new feature and noticed this small typo 😁
> Fix indentation in build matrix example

- pages/pipelines/conditionals.md.erb
Update to include the `soft_failed` build state that is available to the `build.state` conditional.
> include `soft_failed` as an option in build.state

- pages/pipelines/conditionals.md.erb
`fixed` state is not available on conditionals. We have the concept of "fixed" on Notifications (to indicate that a build on the same branch passed after failing), but only through this page:
You can't use `build.state = 'fixed'`
> fixed state not available in conditionals

- pages/agent/v3/linux.md.erb
Currently in Linux installation steps documentation, in file locations we do not have any mention about agent logs so adding a note to explain how to access agent logs in such scenarios.
> Add a note about agent logs for linux install

- pages/agent/v3/cli_annotate.md.erb
Adds a link to the Basscss colour utility classes, as these can be used in annotations (and on first pass, I missed these)
Related [Slack thread](https://buildkite-community.slack.com/archives/C02T53V9H/p1648255244980119) for context.
> docs: add link to basscss color classes

- pages/apis/agent_api.md.erb
Agent API uses HTTP Authorization header with "Token" instead of "Bearer". This PR fixes this in the agent API docs
> Fix Authorization header for Agent API

- app/models/page/renderer.rb
This resolves DOC-288:
https://linear.app/buildkite/issue/DOC-288/fix-nokogiri-warning
> Simplify filename rendering for Figures

- pages/pipelines/_build_states.md.erb
Currently, it is not obvious when a build would go to  _**not-run**_  build state. So added this little detail.
> Added details about not-run build state

- pages/pipelines/notifications.md.erb
step-level notification examples had wrong indentation. The pipeline was not correct.
> fix indentation issue around step-level notifications examples

- pages/tutorials/parallel_builds.md.erb
I have included the 3 parallel job label helpers that exist for users.
* `%n`
* `%N`
* `%t`
I have only added "words" to document them, I was planning to include screenshots I created but it felt a bit heavy handed in this section of the tutorial.
If there are any changes or additions feel free to make them or give me feedback!
> Include parallel job count step label helpers

- pages/agent/v3.md.erb
Adds a link to https://buildkite.com/docs/agent/v3/cli-step in https://buildkite.com/docs/agent/v3#usage. This link is in the left sidebar but was missing from the main `Usage` section.
> Add usage link for buildkite-agent step

- app/assets/stylesheets/public/_docs.scss
- app/controllers/pages_controller.rb
- app/models/beta_pages.rb
- app/models/page.rb
- app/models/page/renderer.rb
- app/views/layouts/_sidebar.html.erb
- app/views/layouts/application.html.erb
- app/views/pages/index.html.erb
- spec/models/page/renderer_spec.rb
- spec/models/page_spec.rb
- styleguide/STYLE.md
This resolves DOC-92:
https://linear.app/buildkite/issue/DOC-92/make-a-stripped-down-beta-page-template-theme
Add docs MD files as usual and add the path in `app/models/beta_pages.rb`. Any path there will have `beta?` true when rendered, allowing us to add content or styles to consistently indicate the BETA state. 
Promoting a doc from BETA is done by removing its path from the list.
The homepage and sidebar both require a `beta-link` class added directly to the link. In the sidebar, this can work for either a whole section (like Test Analytics) or an individual link. I recommend always rolling up to the nearest parent to avoid having a bunch of the BETA pills as much as possible.
BETA flag can be seen on https://docs-review-pr-1411.herokuapp.com/docs/test-analytics
> WIP: Add POC for Beta styles

- pages/integrations/github.md.erb
Much like this PR https://github.com/buildkite/docs/pull/1246, I have just tweaked the explanation slightly to be explicit about the event we trigger the build off as it came through as a question in support.
It does mention it in the pipeline, you can see the pick from the changelog https://buildkite.com/changelog/116-build-only-branches-tags-or-both, but I think it's worth making it a little clearer.
I think the wording will need some tweaking, I put in a ref to the Github docs. I will leave it in your capable hands
Looks like:
> Update documentation for building from tags

- app/assets/stylesheets/public/_docs.scss
- app/assets/stylesheets/public/_homepage.scss
- app/assets/stylesheets/public/utils/_beta-pill.scss
- app/views/layouts/_sidebar.html.erb
- app/views/pages/index.html.erb
- styleguide/STYLE.md
Resolves #1484 
- 💄 Apply badge CSS class to a non-link element
- ♻️ Rename badge to pill and refactor as a utility class
- 📄 Updated docs in STYLE.md to reflect the new. styling usage
> 💄 Fix badge link hover effect

- styleguide/STYLE.md
The link to the article about the differences between en-US, en-GB, and en-AU seems to have gone missing. I've replaced the link to the same article on the Wayback Machine.
> Fix broken style guide English variants link

- pages/agent/v3/macos.md.erb
If you run `brew install buildkite/buildkite/buildkite-agent` without having tapped `buildkite/buildkite` before, then you get a warning while Homebrew taps anyway. I've put an explicit `tap` command in to suppress this warning and to make it a little more clear that Buildkite's tooling is not part of the core Homebrew formulae.
Truthfully, I'm not sure this is a real suggestion, but it was the smallest thing I could think of to change so far and I'm really here just exercising the docs contribution workflow for @plaindocs.
> Prefix `brew install` with explicit `tap`

- app/assets/stylesheets/public/_docs.scss
- app/assets/stylesheets/public/utils/_text_content.scss
- public/404.html
The app and marketing site uses `1.4` ratio for text line-height. I've also tweaked this on Docs for consistency. Furthermore, although subtle, `1.4` line-height is more legible as it gives the different lines of text more breathing room.
Example:
| Before | After |
| ------ | ----- |
| <img width="630" alt="Screen Shot 2022-05-16 at 5 18 12 pm" src="https://user-images.githubusercontent.com/7202667/168539408-36b93041-51fc-4dab-99bd-4e13da558f59.png"> | <img width="627" alt="Screen Shot 2022-05-16 at 5 18 19 pm" src="https://user-images.githubusercontent.com/7202667/168539450-fc1302c3-993e-4009-8a55-57c818ce46fc.png"> |
| <img width="616" alt="Screen Shot 2022-05-16 at 5 14 18 pm" src="https://user-images.githubusercontent.com/7202667/168538788-6fe49b5d-d44e-45db-83eb-382f0fb58702.png"> | …
> 💄 Better consistency and legibility for body text

- styleguide/STYLE.md
This adds a section to the style guide that describes how the docs site's Markdown differs from more popular Markdown variants.
> Style guide: document the Markdown variant

- pages/agent/v3/windows.md.erb
- pages/pipelines/environment_variables.md.erb
GitHub have [deprecated the unauthenticated git protocol](https://github.blog/2021-09-01-improving-git-protocol-security-github/) and have switched to https, but we still supply git:// URIs to the `$BUILDKITE_PULL_REQUEST_REPO` environment variable. We're deprecating that, and so need to update the docs for the variable. I've included a note that anything using the value should be able to handle any protocol.
Fixes PIP-619
> Clarify pull request repo protocols vary

- pages/test_analytics/ruby_collectors.md.erb
This PR:
- Adds a missing ` tick (and then evens up the table view to compensate)
- Changes the link that jumps people to info about env vars because it's the intro part that people seem to be missing as they set up Test Analytics
- Pulls our note about some parts of Test Analytics not working without passing through all the env vars up earlier in the explainer to hopefully help make that clearer
> Copyedit and link update about Ruby env vars

- pages/test_analytics.md.erb
There's a linting error that's causing a failed build. I've pushed up the fix by explicitly [omit TOC](https://github.com/buildkite/docs/pull/1521) on the TA Landing Page.
I forgot to rebase `main` when I merged the [TA Landing Page PR](https://github.com/buildkite/docs/pull/1523).
> 💚 Explicitly opt-out of toc on the TA Landing Page

- pages/test_analytics/ruby_collectors.md.erb
Fix the following user-reported typos:
- "BUILDKITE_JOB_ID" is repeated for "message". It should be "BUILDKITE_MESSAGE".
- Probably a typo in "BUILDKITE_ANANLYTICS_MESSAGE".
> Fix typos in env vars

- pages/test_analytics/ruby_collectors.md.erb
Got more detail on our env vars via a comment in a different PR:
> This isn't quite right, and it's not the easiest thing to communicate 😅
> 
> On Buildkite they need to ensure BUILDKITE_BUILD_ID is passed through, or they can set BUILDKITE_ANALYTICS_KEY to something of their choosing. For the other supported platforms there's a similar thing going on.
> 
> Perhaps all that's needed is to drop the var in the brackets?
> 
> `<p>The only required environment variable is the unique key for the build that initiated the Test Analytics run, but some features will not work if the other environment variables are not set.</p>`
Might be that we also need to add different word to make the relationship between BUILD_ID and ANALYTICS_KEY clear, but for now, this PR makes the more straightforward part …
> Remove incorrect env var reference

- pages/apis/webhooks/integrations.md.erb
- vale/vocab.txt
JavaScript is, regretfully, Pascal case. `vocab.txt` contains the exceptional "Javascript" for one instance in the docs, so I've fixed that and dropped the exception.
Discovered in the course of #1526.
> Correct "Javascript" to "JavaScript"

- app/assets/stylesheets/public/_docs.scss
- app/assets/stylesheets/public/_homepage.scss
- app/assets/stylesheets/public/_site_header.scss
- app/assets/stylesheets/public/_variables.scss
- app/assets/stylesheets/public/utils/_bootstrap_form.scss
- app/views/layouts/application.html.erb
- app/views/layouts/homepage.html.erb
Link Buildkite logo in the header to the homepage. 
This makes it easier for customers to find the link back to our homepage. This is an interim design improvement until we have a new header design (which we may adopt from the Marketing site, but to be discussed or confirmed later).
https://www.loom.com/share/101d5aaa93644424b0c665cb4cd7523c
Changes:
- Add hyperlink to logos
- "Buildkite Docs" header text still links to the Docs index page
- a11y improvements
- Hover effect on logo to indicate these are linkable
- Refactor: use `$transition-speed` variable for all transition instances
> 💄 Link logo to homepage

- pages/test_analytics/importing_json.md.erb
- pages/test_analytics/importing_junit_xml.md.erb
The API has changed a bit for importing JSON and JUnit XML, from a JSON payload to a `multipart/form-data` payload, this PR attempts to capture that change.
There's some duplication here which is rather unpleasant (namely, the tables ought to either consume already existing YAML or be YAML themselves). I propose we do not attempt to deal with that today.
Since it made sense to do so, I've also rolled up the JSON format reference from #1545, rather than try to wrangle it separately.
The supersedes the following PRs:
- closes https://github.com/buildkite/docs/pull/1548
- closes https://github.com/buildkite/docs/pull/1545
> Rewrite Test Analytics import docs for multipart form

- app/assets/stylesheets/public/utils/_button.scss
- app/views/layouts/_sidebar.html.erb
- data/tiles.yml
- pages/test_analytics.md.erb
- pages/test_analytics/golang_collectors.md.erb
- pages/test_analytics/other_collectors.md.erb
- pages/test_analytics/python_collectors.md.erb
- vale/styles/vocab.txt
Add Golang and Python collectors pages, as they can be configured with Test Analytics.
Here's the advice from @toolmantim 
> If we wanted to add Golang to the languages, here's the rough instructions: https://gist.github.com/toolmantim/4d65c4d3209500a0565cc999da88ea5f
> Python actually follows the same pattern, except it's built into pytest:
> `pytest testing/ --junitxml="result.xml"`
> That will run all your tests and output the JUnit XML file
I've created the two pages based on the above [instructions](https://gist.github.com/toolmantim/4d65c4d3209500a0565cc999da88ea5f). I'm unsure how polished these are as I don't have experience working with Golang and Python test frameworks.
> Add Golang and Python collectors

- pages/test_analytics/ruby_collectors.md.erb
Changed `Collector` to `TestCollector`
> Fix typo in module name in ruby collector docs

- pages/agent/v3/tracing.md.erb
Soften the experimental disclaimer, and cross-link to experiment and configuration pages.
> Update opentelemetry docs with clearer next steps and cross-links

- pages/test_analytics/other_collectors.md.erb
Fixes a typo in the Slack channel name - should be #test-analytics channel
> Fix typo in Slack channel name

- pages/test_analytics/ruby_collectors.md.erb
https://buildkite.com/docs/test-analytics/ruby-collectors#minitest-collector
> Fix typo in Minitest doc

- pages/test_analytics/importing_json.md.erb
The object identifier is actually required.
I'm also not so sure about the current description, but I think it will need some changes so it's clear that is required
> Set identifier as required

- app/views/pages/index.html.erb
Links to APIs now (looks like a typo). Needs to link to Integrations. Links now.
> Fix faulty Integrations link on the Docs homepage

- app/assets/stylesheets/public/_docs.scss
- app/assets/stylesheets/public/_search.scss
- app/assets/stylesheets/public/_site_header.scss
- app/views/layouts/_sidebar.html.erb
- app/views/layouts/_site_header.html.erb
Position absolute children within a `overflow-y: scroll;` element get clipped. The search pop up is wider than the scrolling sidebar and got clipped, making the search unusable.
To fix this, I've moved the search box into the header.
> 🚑 HOTFIX: Search pop up should not be clipped

- .github/dependabot.yml
Dependabot errors out on one of the root Dockerfiles (because `public.ecr.aws` doesn't support an API it requires, see
https://github.com/dependabot/dependabot-core/issues/4212). To avoid this, I've changed the dependabot configuration to only upgrade Vale.
This is a follow-up to https://github.com/buildkite/docs/pull/1538.
> Exclude some Dockerfiles from Dependabot upgrades

- app/views/layouts/_footer.html.erb
Missed this template logic. The support email address should be `support+analytics@buildkite.com` when we're on any on the Test Analytics pages.
> 👔 Should use support+analytics email

- pages/test_analytics/elixir_collectors.md.erb
- pages/test_analytics/js_collectors.md.erb
- pages/test_analytics/ruby_collectors.md.erb
- pages/test_analytics/rust_collectors.md.erb
- pages/test_analytics/swift_collectors.md.erb
Pushing up a suggestion to link Collectors to the respective GitHub repo.
I've chatted with different people who agree that linking Collectors on Docs to the respective GitHub repo is helpful. Customers can see the Collectors' source code if needed and there are additional information on the repo as well.
That being said, there's an argument to having a 'single source of truth' for documentation, which is helpful for docs findability and maintainability.
I'm trying out a small improvement here to simply add a text link, nothing fancy for now.
Open to your thoughts on this.
> 💬 Link to offical collector GitHub repo

- spec/rails_helper.rb
- spec/support/time_helper.rb
This Pull Request sets up RSpec to use https://edgeapi.rubyonrails.org/classes/ActiveSupport/Testing/TimeHelpers.html in the tests.
> Make TimeHelpers from ActiveSupport in RSpec

- pages/integrations/pagerduty.md.erb
- Removes mention of a PagerDuty Integration key provided as plaintext
- Adds recommended reading on handling secrets
> Update PD integration page with security info

- data/agent_attributes.yaml
- pages/agent/v2/configuration.md.erb
- pages/agent/v3/configuration.md.erb
- pages/plugins/using.md.erb
- pages/tutorials/parallel_builds.md.erb
The `%spawn` is the recommended way to configure agent name.
We stopped using [`%n` in the default agent config 1.5 years ago](https://github.com/buildkite/elastic-ci-stack-for-aws/pull/794) and plan to phase it out.
If your agents have unique names already (with a unique hostname) then using the `-%n` is also redundant.
> Change Agent example configurations to use %spawn

- data/agent_attributes.yaml
- pages/agent/v2/configuration.md.erb
Add documentation for the new `%random` parameter available in agent names.
For the moment this is 6 alphanumeric characters, but that's not guaranteed. It will remain around there. I feel like the other items are vague enough that these words are sufficient.
An example would be: `agent-%random` becomes `agent-RXo43u`.
I've also updated the agent v2 example because it never supported `%spawn`, but it does support `%random` because the latter is done server-side.
Fixes DOC-397.
> Agent name %random

- pages/test_analytics/ruby_collectors.md.erb
This PR addresses feedback from a customer re: updates we previously made that removed the specific reference to which env var to set in our Ruby setup instructions. Our in-app instructions are specific on this point; let's port that info over here as well 🎉
> Make env var specific in our Ruby collector setup instructions

- app/models/test_analytics_json.rb
- data/test_analytics_json_fields.schema.yaml
- data/test_analytics_json_fields_history.yaml
- data/test_analytics_json_fields_span.yaml
- data/test_analytics_json_fields_test_result.yaml
- pages/test_analytics/importing_json.md.erb
I'm not sure this is genuinely good, but it does eliminate some Markdown tables (🤮) and CSV-filled comments with something a little less awful. There are more opportunities to refactor here, but this is my attempt at starting that process.
> Structure Test Analytics JSON format reference

- app/assets/stylesheets/public/_docs.scss
- app/assets/stylesheets/public/_nav.scss
- app/assets/stylesheets/public/_responsive-table.scss
- app/assets/stylesheets/public/_search.scss
- app/assets/stylesheets/public/_toc.scss
- app/assets/stylesheets/public/utils/_button.scss
- app/models/page/renderer.rb
- pages/agent/v3/cli_artifact.md.erb
- pages/pipelines/environment_variables.md.erb
- spec/features/toc_rendering_spec.rb
- spec/models/page/renderer_spec.rb
Small styling tweak for table of contents (TOC) so it aligns better with the overall sidebar look and feel.
- Drop shadow 
- Body font
- No overflow scroll for exceedingly long TOC
Visual tweaks as shown on my local dev:
- Consistent look and feel as per left sidebar nav
- System font
- Position fixed with overflow scrolling
> 💄Improve table of contents styling

- pages/test_analytics/test_suites.md.erb
This PR generalizes our language around unique build key because the exact env var will be different depending on CI (Build ID was a little Buildkite-specific, and perhaps hard to match up on the CI page).
For example:
- For Buildkite, it is BUILDKITE_BUILD_ID
- For Circle, it is CIRCLE_WORKFLOW_ID-$CIRCLE_BUILD_NUM
- For GH Actions, it is GITHUB_ACTION-$GITHUB_RUN_NUMBER-$GITHUB_RUN_ATTEMPT
- For generic CI, it is BUILDKITE_ANALYTICS_KEY
Happy for wordsmith humans to suggest better words in place of the ones I chose, should inspiration strike ⚡💡. Like, would `unique build key` be better than `unique build identifier`? 🤷🏻‍♂️
> Generalize build key description re: parallelized builds

- pages/pipelines/skipping.md.erb
Some customers are not aware that we support a few different forms of `skip ci` to tell Buildkite to not create a build on a commit, such as:
```
[skip-ci]
[ci-skip]
[ci skip]
[skip ci]
```
It'd be great if we could add that extra bit of clarification for future travellers!
> add various combinations of "skip ci" that are accepted by Buildkite

- pages/agent/v2/cli_artifact.md.erb
- pages/agent/v2/cli_meta_data.md.erb
- pages/agent/v2/cli_pipeline.md.erb
- pages/agent/v2/cli_start.md.erb
- pages/agent/v2/securing.md.erb
- pages/agent/v2/upgrading_to_v3.md.erb
- pages/agent/v3/aws/secrets_manager.md.erb
- pages/agent/v3/cli_annotate.md.erb
- pages/agent/v3/cli_annotation.md.erb
- pages/agent/v3/cli_artifact.md.erb
- pages/agent/v3/cli_bootstrap.md.erb
- pages/agent/v3/cli_meta_data.md.erb
- pages/agent/v3/cli_pipeline.md.erb
- pages/agent/v3/cli_start.md.erb
- pages/agent/v3/cli_step.md.erb
- pages/agent/v3/securing.md.erb
- pages/agent/v3/upgrading.md.erb
- pages/apis/graphql/graphql_cookbook.md.erb
- pages/apis/graphql/graphql_tutorial.md.erb
- pages/integrations/sso/google_workspace.md.erb
- pages/pipelines/archiving_and_deleting_pipelines.md.erb
- pages/pipelines/build_meta_data.md.erb
- pages/pipelines/permissions.md.erb
- pages/pipelines/skipping.md.erb
- pages/test_analytics/other_collectors.md.erb
- pages/test_analytics/permissions.md.erb
- vale/styles/Buildkite/h1_title_case.yml
The style guide calls for title case H1s, in contrast to sentence case H2s elsewhere. Speculatively, I've written a Vale rule to require this and fixed up the handful of cases where this convention wasn't already followed.
If this is desirable, I can create a corresponding rule for sentence case on H2+ headings.
Prompted by @karensawrey in https://github.com/buildkite/docs/pull/1615#discussion_r911041368.
> Add Vale rule to require title-case H1s

- pages/test_analytics/javascript_collectors.md.erb
- pages/test_analytics/python_collectors.md.erb
Python and JavaScript Test Analytics collector pages currently only have one collector. Like the Swift page, we can remove visual clutter and duplicate headings by disabling Table of Contents.
> 💬 Remove TOC on pages with one collector

- pages/agent/v3/elastic_ci_aws.md.erb
I was amazed to learn this when i dug into it.  It turns out that you can reference a local file as your bootstrap script - it doesn't have to live in S3! It's currently poorly documented, but the way Buildkite grabs the bootstrap script (this happens [here](https://github.com/buildkite/elastic-ci-stack-for-aws/blob/7104fe450cb5a22414ee5bbb4ed8e7fe0e65d3a2/packer/linux/conf/bin/bk-install-elastic-stack.sh#L201-L205)) is to use `aws s3 cp`, except if it's not an `s3://` URL, it'll call `curl` ([here](https://github.com/buildkite/elastic-ci-stack-for-aws/blob/7104fe450cb5a22414ee5bbb4ed8e7fe0e65d3a2/packer/linux/conf/bin/bk-fetch.sh#L12)), which can be convinced to just cat out a local file.
> elastic_ci_aws: `BootstrapScriptUrl` needn't be S3!

- pages/pipelines/_job_states.md.erb
- pages/pipelines/conditionals.md.erb
Revamped  #1353
`Finished` as a state is an alias used for a group of build states, but is not used in all the places.
> Remove finished

- app/assets/stylesheets/public/_nav.scss
- app/helpers/application_helper.rb
- app/models/page.rb
- app/views/layouts/_nav.html.erb
- app/views/layouts/_nav_children.html.erb
- app/views/layouts/_nav_link.html.erb
- app/views/pages/index.html.erb
- data/nav.yml
- pages/pipelines/conditionals.md.erb
- pages/pipelines/environment_variables.md.erb
- pages/pipelines/permissions.md.erb
- spec/features/reading_pages_spec.rb
A series of quick fixes to clear the backlog:
I've manually checked the above in Chrome. Let me know if you're good with the above or need further fixes.
> ⚡️ Quick fixes Thursday 7 Jul 2022

- app/views/layouts/application.html.erb
- docker-compose.production.yml
Checking that we do know how to change ENV VARs in production. I'll
remove both lines in a later commit once this has been confirmed.
If this works, it confirms the approach in #1609 works in production.
> Production ENV VARs test

- pages/tutorials/parallel_builds.md.erb
> I've simplified the agent instructions a bit, and tried to provide a
> journey through vertical to horizontal and then auto scaling.
> And then grouped together the parallel jobs bits.
> I don't think the note is neccessary any more, given ordering is
> addressed in the beginning.
by @sj26
> Re-arranging the parallel builds page

- pages/integrations/github.md.erb
To help users when adding new GitHub repository providers, add a note here about what permissions are required on both
Buildkite and GitHub
> Add note about permissions for github provider

- pages/agent/v3/hooks.md.erb
This tries to do a few things, so that readers don't attempt to go against the grain with hooks (e.g., trying to use the agent-shutdown hook to clean up after individual jobs).
Mainly, I tried to emphasize:
- The minimalist nature of the `pre-bootstrap` and `agent-shutdown` hooks
- The job details exposed to job hooks
- Applications for agent and job hooks
Things I did _not_ attempt to do despite being tempted: rewriting the whole thing or challenging the distinction between agent and job lifecycles.
> Emphasize difference between agent and job lifecycles

- pages/agent/v3/installation.md.erb
- pages/agent/v3/macos.md.erb
- pages/agent/v3/ssh_keys.md.erb
According to the docs' user feedback, the docs were unclear on where the Buildkite agent is actually run. Adding info and a link to the page in question + fixing a faulty capital letter on the agent installation page.
> Addressing the feedback

- pages/apis/api_differences.md.erb
- pages/apis/graphql_api.md.erb
* Changes the link in the GraphQL overview to make GraphQL appear first
* Implements new feedback from @sj26
> APT disparity page improvements

- pages/agent/v2.md.erb
- pages/agent/v2/gcloud.md.erb
- pages/agent/v2/upgrading_to_v2.md.erb
- pages/agent/v3.md.erb
- pages/agent/v3/aws/vpc.md.erb
- pages/agent/v3/cli_annotate.md.erb
- pages/agent/v3/configuration.md.erb
- pages/agent/v3/debian.md.erb
- pages/agent/v3/elastic_ci_aws.md.erb
- pages/agent/v3/elastic_ci_stack_for_ec2_mac/autoscaling_mac_metal.md.erb
- pages/agent/v3/gcloud.md.erb
- pages/agent/v3/tracing.md.erb
- pages/agent/v3/ubuntu.md.erb
- pages/integrations/artifactory.md.erb
- pages/integrations/docker_hub.md.erb
- pages/integrations/sso/azure_ad.md.erb
- pages/tutorials/getting_started.md.erb
- vale/styles/Buildkite/existence-case-sensitive.yml
- vale/styles/Buildkite/existence.yml
- vale/styles/Buildkite/h2-h6_sentence_case.yml
This PR makes fixes for H2s sentence-case linting for the remainder of the `pages/agent` tree (plus some consistency fixes that flow from that).
Highlights from this round:
- 🇺🇸 Caught some non-American English-isms (customise → customize)
- 🔪 Slashes in headings seem to break Vale a little
> H2 sentence-case linting (round 4)

- data/agent_attributes.yaml
- data/environment_variables.yaml
Adding docs for the feature added in https://github.com/buildkite/agent/pull/1564
Preview:
**Agent configuration**
**Environment variables**
> Add docs for enable-job-log-tmpfile

- render.yaml
To bring the cost of inactive open PRs down. If it's annoying we can revert.
> Keep render previews for 2 days after the last commit instead of 5

- pages/agent/v3/debian.md.erb
- pages/agent/v3/ubuntu.md.erb
I was setting up the agent for the first time today, using the Ubuntu install instructions, and felt somewhat confused/intimidated by the fairly involved set of commands we had in place for downloading the GPG key for our apt repo:
```
wget -O- https://keys.openpgp.org/vks/v1/by-fingerprint/32A37959C2FA5C3C99EFBC32A79206696452D198 | tee /tmp/buildkite-agent-archive-keyring.gpg && sudo bash -c "cat /tmp/buildkite-agent-archive-keyring.gpg | gpg --dearmor > /usr/share/keyrings/buildkite-agent-archive-keyring.gpg"
```
Fortunately, I'd also just followed Docker's [Ubuntu install instructions](https://docs.docker.com/engine/install/ubuntu/), which included a much more concise command for doing the same:
```
curl -fsSL https://keys.openpgp.org/vks/v1/by-fingerprint/32A37959C2FA5C3C99EFBC32A79206 …
```
> Use tidier GPG key download command on Debian/Ubuntu

- pages/apis/graphql/graphql_cookbook.md.erb
Current query is giving below error when used:
```
"errors": [
{
"message": "Field 'jobs' doesn't accept argument 'createdAtFrom'",
"locations": [
{
"line": 11,
"column": 86
}
],
```
This error is because "createdAtFrom" is not a valid field for jobs object as we can see from documentation here https://buildkite.com/user/graphql/documentation/type/Build
This PR is to fix this bad query
> Fixing bad query in cookbook
